using System.Collections.Generic;
using Andastra.Parsing;
using Andastra.Parsing.Resource;
using JetBrains.Annotations;
using Andastra.Parsing.Common;

namespace Andastra.Parsing.Resource.Generics
{
    /// <summary>
    /// Stores module information.
    ///
    /// IFO files are GFF-based format files that store module information including
    /// entry points, script hooks, area lists, and module metadata.
    /// </summary>
    [PublicAPI]
    public sealed class IFO
    {
        // Matching PyKotor implementation at Libraries/PyKotor/src/pykotor/resource/generics/ifo.py:36
        // Original: BINARY_TYPE = ResourceType.IFO
        public static readonly ResourceType BinaryType = ResourceType.IFO;

        // Module ID: 16-byte unique identifier generated by toolset
        public byte[] ModId { get; set; } = new byte[16];

        // Localized module name displayed in-game
        public LocalizedString Name { get; set; } = LocalizedString.FromInvalid();

        // Matching PyKotor implementation at Libraries/PyKotor/src/pykotor/resource/generics/ifo.py:51
        // Original: self.mod_name: LocalizedString = LocalizedString.from_invalid()
        public LocalizedString ModName { get; set; } = LocalizedString.FromInvalid();

        // Matching PyKotor implementation at Libraries/PyKotor/src/pykotor/resource/generics/ifo.py:56
        // Original: self.area_name: ResRef = ResRef.from_blank()
        public ResRef AreaName { get; set; } = ResRef.FromBlank();

        // Matching PyKotor implementation at Libraries/PyKotor/src/pykotor/resource/generics/ifo.py:62
        // Original: self.resref: ResRef = ResRef.from_blank()
        public ResRef ResRef { get; set; } = ResRef.FromBlank();

        // Module tag identifier
        public string Tag { get; set; } = string.Empty;

        // Entry area ResRef (starting area)
        public ResRef EntryArea { get; set; } = ResRef.FromBlank();

        // Entry X position
        public float EntryX { get; set; }

        // Entry Y position
        public float EntryY { get; set; }

        // Entry Z position
        public float EntryZ { get; set; }

        // Entry direction (facing)
        public float EntryDirectionX { get; set; }
        public float EntryDirectionY { get; set; }
        public float EntryDirectionZ { get; set; }

        // Module script hooks
        public ResRef OnClientEnter { get; set; } = ResRef.FromBlank();
        public ResRef OnClientLeave { get; set; } = ResRef.FromBlank();
        public ResRef OnHeartbeat { get; set; } = ResRef.FromBlank();
        public ResRef OnUserDefined { get; set; } = ResRef.FromBlank();
        public ResRef OnActivateItem { get; set; } = ResRef.FromBlank();
        public ResRef OnAcquireItem { get; set; } = ResRef.FromBlank();
        public ResRef OnUnacquireItem { get; set; } = ResRef.FromBlank();
        public ResRef OnPlayerDeath { get; set; } = ResRef.FromBlank();
        public ResRef OnPlayerDying { get; set; } = ResRef.FromBlank();
        public ResRef OnPlayerRespawn { get; set; } = ResRef.FromBlank();
        public ResRef OnPlayerRest { get; set; } = ResRef.FromBlank();
        public ResRef OnPlayerLevelUp { get; set; } = ResRef.FromBlank();
        public ResRef OnPlayerCancelCutscene { get; set; } = ResRef.FromBlank();

        // Area list (areas in this module)
        public List<ResRef> AreaList { get; set; } = new List<ResRef>();

        // Expansion pack requirements
        public int ExpansionPack { get; set; }

        // Module description
        public LocalizedString Description { get; set; } = LocalizedString.FromInvalid();

        // Module version
        public int ModVersion { get; set; }

        // Module Vault ID (for multiplayer)
        public int VaultId { get; set; }

        // Matching PyKotor implementation at Libraries/PyKotor/src/pykotor/resource/generics/ifo.py:86
        // Original: self.vo_id: str = ""
        public string VoId { get; set; } = string.Empty;

        // Matching PyKotor implementation at Libraries/PyKotor/src/pykotor/resource/generics/ifo.py:113
        // Original: self.hak: str = ""
        public string Hak { get; set; } = string.Empty;

        // Matching PyKotor implementation at Libraries/PyKotor/src/pykotor/resource/generics/ifo.py:115-122
        // Original: Time settings
        public int DawnHour { get; set; }
        public int DuskHour { get; set; }
        public int TimeScale { get; set; }
        public int StartMonth { get; set; }
        public int StartDay { get; set; }
        public int StartHour { get; set; }
        public int StartYear { get; set; }
        public int XpScale { get; set; }

        // Matching PyKotor implementation at Libraries/PyKotor/src/pykotor/resource/generics/ifo.py:123-124
        // Original: Additional script hooks
        public ResRef StartMovie { get; set; } = ResRef.FromBlank();

        // Additional script hooks from Python
        public ResRef OnLoad { get; set; } = ResRef.FromBlank();
        public ResRef OnStart { get; set; } = ResRef.FromBlank();

        // Entry direction as angle (computed from X/Y components)
        public float EntryDirection { get; set; }

        public IFO()
        {
        }
    }
}