using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Andastra.Parsing.Namespaces;
using Andastra.Parsing.Reader;
using FluentAssertions;
using IniParser.Model;
using Xunit;

namespace Andastra.Parsing.Tests.Reader
{
    /// <summary>
    /// Tests for NamespaceReader functionality.
    ///
    /// These tests verify parsing of namespaces.ini files, including:
    /// - Parsing the [Namespaces] section and namespace definitions
    /// - Handling empty DataPath values
    /// - Preserving relative paths with ../ syntax
    /// - Handling comments and blank lines
    /// - Case-insensitive key matching
    /// - Error handling for missing required fields and sections
    ///
    /// Note: The error "Failed to load namespace config: Value was either too large or too small for an Int32"
    /// occurs when ConfigReader loads the namespace config files (changes.ini), not when parsing namespaces.ini.
    /// The Int32 overflow happens in ConfigReader.ParseIntValue() when parsing values from changes.ini files.
    /// Int32 overflow testing should be added to ConfigReader tests, not here, as NamespaceReader only parses
    /// namespaces.ini structure and doesn't parse integer values.
    /// </summary>
    public class NamespaceReaderTests : IDisposable
    {
        private readonly string _tempDir;
        private readonly string _iniFilePath;

        public NamespaceReaderTests()
        {
            _tempDir = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString());
            Directory.CreateDirectory(_tempDir);
            _iniFilePath = Path.Combine(_tempDir, "namespaces.ini");
        }

        public void Dispose()
        {
            if (Directory.Exists(_tempDir))
            {
                try
                {
                    Directory.Delete(_tempDir, true);
                }
                catch
                {
                    // Ignore cleanup errors
                }
            }
        }

        [Fact(Timeout = 120000)] // 2 minutes timeout
        public void Load_WithK1CPNamespacesFile_ShouldParseSuccessfully()
        {
            // Arrange - Create INI file with the exact content from the user
            string iniContent = @"; ===================================================================
; TSLPATCHER - GENERATED NAMESPACES FILE (8/04/2024)
; ===================================================================
; This file is automatically generated and as such has no formatting
; to speak of. You can insert blank lines between [sections] (but NOT
; between keys within a section) and add comment lines starting
; with semicolon to make it more readable without breaking anything.
; -------------------------------------------------------------------
[Namespaces]
Namespace1=Base_English
Namespace2=Translation_French
Namespace3=Translation_Russian
; ===================================================================
[Base_English]
IniName=changes.ini
InfoName=info.rtf
DataPath=
Name=K1CP v1.10 (English)
Description=Installs the English version of K1CP (default)
[Translation_French]
IniName=../tslpatchdata/translation_french/changes.ini
InfoName=../tslpatchdata/translation_french/info.rtf
DataPath=
Name=K1CP v1.10 (Traduction en Francais)
Description=Installe la version francaise de K1CP
[Translation_Russian]
IniName=../tslpatchdata/translation_russian/changes.ini
InfoName=../tslpatchdata/translation_russian/info.rtf
DataPath=
Name=K1CP v1.10 (Russkogo Perevoda)
Description=Ustanovite russkuyu versiyu K1CP
";
            File.WriteAllText(_iniFilePath, iniContent);

            // Act
            IniData ini = ConfigReader.ParseIniText(iniContent, caseInsensitive: true);
            var reader = new NamespaceReader(ini);
            List<PatcherNamespace> namespaces = reader.Load();

            // Assert
            namespaces.Should().NotBeNull();
            namespaces.Should().HaveCount(3);

            PatcherNamespace baseEnglish = namespaces.FirstOrDefault(n => n.NamespaceId == "Base_English");
            baseEnglish.Should().NotBeNull();
            baseEnglish.IniFilename.Should().Be("changes.ini");
            baseEnglish.InfoFilename.Should().Be("info.rtf");
            baseEnglish.DataFolderPath.Should().BeEmpty();
            baseEnglish.Name.Should().Be("K1CP v1.10 (English)");
            baseEnglish.Description.Should().Be("Installs the English version of K1CP (default)");

            PatcherNamespace translationFrench = namespaces.FirstOrDefault(n => n.NamespaceId == "Translation_French");
            translationFrench.Should().NotBeNull();
            translationFrench.IniFilename.Should().Be("../tslpatchdata/translation_french/changes.ini");
            translationFrench.InfoFilename.Should().Be("../tslpatchdata/translation_french/info.rtf");
            translationFrench.DataFolderPath.Should().BeEmpty();
            translationFrench.Name.Should().Be("K1CP v1.10 (Traduction en Francais)");
            translationFrench.Description.Should().Be("Installe la version francaise de K1CP");

            PatcherNamespace translationRussian = namespaces.FirstOrDefault(n => n.NamespaceId == "Translation_Russian");
            translationRussian.Should().NotBeNull();
            translationRussian.IniFilename.Should().Be("../tslpatchdata/translation_russian/changes.ini");
            translationRussian.InfoFilename.Should().Be("../tslpatchdata/translation_russian/info.rtf");
            translationRussian.DataFolderPath.Should().BeEmpty();
            translationRussian.Name.Should().Be("K1CP v1.10 (Russkogo Perevoda)");
            translationRussian.Description.Should().Be("Ustanovite russkuyu versiyu K1CP");
        }

        [Fact(Timeout = 120000)] // 2 minutes timeout
        public void FromFilePath_WithK1CPNamespacesFile_ShouldParseSuccessfully()
        {
            // Arrange - Create INI file with the exact content from the user
            string iniContent = @"; ===================================================================
; TSLPATCHER - GENERATED NAMESPACES FILE (8/04/2024)
; ===================================================================
; This file is automatically generated and as such has no formatting
; to speak of. You can insert blank lines between [sections] (but NOT
; between keys within a section) and add comment lines starting
; with semicolon to make it more readable without breaking anything.
; -------------------------------------------------------------------
[Namespaces]
Namespace1=Base_English
Namespace2=Translation_French
Namespace3=Translation_Russian
; ===================================================================
[Base_English]
IniName=changes.ini
InfoName=info.rtf
DataPath=
Name=K1CP v1.10 (English)
Description=Installs the English version of K1CP (default)
[Translation_French]
IniName=../tslpatchdata/translation_french/changes.ini
InfoName=../tslpatchdata/translation_french/info.rtf
DataPath=
Name=K1CP v1.10 (Traduction en Francais)
Description=Installe la version francaise de K1CP
[Translation_Russian]
IniName=../tslpatchdata/translation_russian/changes.ini
InfoName=../tslpatchdata/translation_russian/info.rtf
DataPath=
Name=K1CP v1.10 (Russkogo Perevoda)
Description=Ustanovite russkuyu versiyu K1CP
";
            File.WriteAllText(_iniFilePath, iniContent);

            // Act
            List<PatcherNamespace> namespaces = NamespaceReader.FromFilePath(_iniFilePath);

            // Assert
            namespaces.Should().NotBeNull();
            namespaces.Should().HaveCount(3);

            PatcherNamespace baseEnglish = namespaces.FirstOrDefault(n => n.NamespaceId == "Base_English");
            baseEnglish.Should().NotBeNull();
            baseEnglish.IniFilename.Should().Be("changes.ini");
            baseEnglish.InfoFilename.Should().Be("info.rtf");
            baseEnglish.DataFolderPath.Should().BeEmpty();
            baseEnglish.Name.Should().Be("K1CP v1.10 (English)");
            baseEnglish.Description.Should().Be("Installs the English version of K1CP (default)");

            PatcherNamespace translationFrench = namespaces.FirstOrDefault(n => n.NamespaceId == "Translation_French");
            translationFrench.Should().NotBeNull();
            translationFrench.IniFilename.Should().Be("../tslpatchdata/translation_french/changes.ini");
            translationFrench.InfoFilename.Should().Be("../tslpatchdata/translation_french/info.rtf");
            translationFrench.DataFolderPath.Should().BeEmpty();
            translationFrench.Name.Should().Be("K1CP v1.10 (Traduction en Francais)");
            translationFrench.Description.Should().Be("Installe la version francaise de K1CP");

            PatcherNamespace translationRussian = namespaces.FirstOrDefault(n => n.NamespaceId == "Translation_Russian");
            translationRussian.Should().NotBeNull();
            translationRussian.IniFilename.Should().Be("../tslpatchdata/translation_russian/changes.ini");
            translationRussian.InfoFilename.Should().Be("../tslpatchdata/translation_russian/info.rtf");
            translationRussian.DataFolderPath.Should().BeEmpty();
            translationRussian.Name.Should().Be("K1CP v1.10 (Russkogo Perevoda)");
            translationRussian.Description.Should().Be("Ustanovite russkuyu versiyu K1CP");
        }

        [Fact(Timeout = 120000)] // 2 minutes timeout
        public void Load_WithEmptyDataPath_ShouldParseSuccessfully()
        {
            // Arrange - Test that empty DataPath values are handled correctly
            string iniContent = @"[Namespaces]
Namespace1=TestNamespace

[TestNamespace]
IniName=changes.ini
InfoName=info.rtf
DataPath=
Name=Test Mod
Description=Test Description
";
            File.WriteAllText(_iniFilePath, iniContent);

            // Act
            IniData ini = ConfigReader.ParseIniText(iniContent, caseInsensitive: true);
            var reader = new NamespaceReader(ini);
            List<PatcherNamespace> namespaces = reader.Load();

            // Assert
            namespaces.Should().HaveCount(1);
            namespaces[0].DataFolderPath.Should().BeEmpty();
        }

        [Fact(Timeout = 120000)] // 2 minutes timeout
        public void Load_WithRelativePaths_ShouldPreservePaths()
        {
            // Arrange - Test that relative paths with ../ are preserved correctly
            string iniContent = @"[Namespaces]
Namespace1=TestNamespace

[TestNamespace]
IniName=../tslpatchdata/subfolder/changes.ini
InfoName=../tslpatchdata/subfolder/info.rtf
DataPath=
Name=Test Mod
Description=Test Description
";
            File.WriteAllText(_iniFilePath, iniContent);

            // Act
            IniData ini = ConfigReader.ParseIniText(iniContent, caseInsensitive: true);
            var reader = new NamespaceReader(ini);
            List<PatcherNamespace> namespaces = reader.Load();

            // Assert
            namespaces.Should().HaveCount(1);
            namespaces[0].IniFilename.Should().Be("../tslpatchdata/subfolder/changes.ini");
            namespaces[0].InfoFilename.Should().Be("../tslpatchdata/subfolder/info.rtf");
        }

        [Fact(Timeout = 120000)] // 2 minutes timeout
        public void Load_WithCommentsAndBlankLines_ShouldParseSuccessfully()
        {
            // Arrange - Test that comments and blank lines don't break parsing
            string iniContent = @"; This is a comment
; Another comment

[Namespaces]
; Comment before key
Namespace1=TestNamespace
; Comment after key

; Comment before section
[TestNamespace]
; Comment in section
IniName=changes.ini
InfoName=info.rtf
DataPath=
Name=Test Mod
Description=Test Description
";
            File.WriteAllText(_iniFilePath, iniContent);

            // Act
            IniData ini = ConfigReader.ParseIniText(iniContent, caseInsensitive: true);
            var reader = new NamespaceReader(ini);
            List<PatcherNamespace> namespaces = reader.Load();

            // Assert
            namespaces.Should().HaveCount(1);
            namespaces[0].NamespaceId.Should().Be("TestNamespace");
            namespaces[0].IniFilename.Should().Be("changes.ini");
        }

        [Fact(Timeout = 120000)] // 2 minutes timeout
        public void Load_WithCaseInsensitiveKeys_ShouldParseSuccessfully()
        {
            // Arrange - Test case-insensitive key matching
            string iniContent = @"[Namespaces]
Namespace1=TestNamespace

[TestNamespace]
ininame=changes.ini
infoname=info.rtf
datapath=
name=Test Mod
description=Test Description
";
            File.WriteAllText(_iniFilePath, iniContent);

            // Act
            IniData ini = ConfigReader.ParseIniText(iniContent, caseInsensitive: true);
            var reader = new NamespaceReader(ini);
            List<PatcherNamespace> namespaces = reader.Load();

            // Assert
            namespaces.Should().HaveCount(1);
            namespaces[0].IniFilename.Should().Be("changes.ini");
            namespaces[0].InfoFilename.Should().Be("info.rtf");
            namespaces[0].Name.Should().Be("Test Mod");
        }

        [Fact(Timeout = 120000)] // 2 minutes timeout
        public void Load_WithMissingRequiredField_ShouldThrowKeyNotFoundException()
        {
            // Arrange - Missing IniName
            string iniContent = @"[Namespaces]
Namespace1=TestNamespace

[TestNamespace]
InfoName=info.rtf
";
            File.WriteAllText(_iniFilePath, iniContent);

            // Act
            IniData ini = ConfigReader.ParseIniText(iniContent, caseInsensitive: true);
            var reader = new NamespaceReader(ini);

            // Assert
            Action act = () => reader.Load();
            act.Should().Throw<KeyNotFoundException>()
                .WithMessage("*IniName not found*");
        }

        [Fact(Timeout = 120000)] // 2 minutes timeout
        public void Load_WithMissingNamespaceSection_ShouldThrowKeyNotFoundException()
        {
            // Arrange - Missing namespace section referenced in [Namespaces]
            string iniContent = @"[Namespaces]
Namespace1=NonExistentNamespace
";
            File.WriteAllText(_iniFilePath, iniContent);

            // Act
            IniData ini = ConfigReader.ParseIniText(iniContent, caseInsensitive: true);
            var reader = new NamespaceReader(ini);

            // Assert
            Action act = () => reader.Load();
            act.Should().Throw<KeyNotFoundException>()
                .WithMessage("*'[NonExistentNamespace]' section was not found*");
        }
    }
}

