using Avalonia.Markup.Xaml;

namespace HolocronToolset.Dialogs
{
    // Matching PyKotor implementation at Tools/HolocronToolset/src/toolset/gui/dialogs/insert_instance.py:38
    // Original: class InsertInstanceDialog(QDialog):
    public partial class InsertInstanceDialog
    {
        // This file is auto-generated by Avalonia XAML compiler
        // All implementation is in InsertInstanceDialog.cs
    }
}
