//------------------------------------------------------------------------------
// <auto-generated> — hand-maintained to match UIResources.resx
//------------------------------------------------------------------------------
#pragma warning disable CS1591

namespace KPatcher.UI.Resources
{
    using System.Globalization;
    using System.Resources;

    /// <summary>Localized strings for KPatcher UI (menus, dialogs, update, RTE editor).</summary>
    public static class UIResources
    {
        private static ResourceManager _resourceManager;
        private static CultureInfo _resourceCulture;

        public static ResourceManager ResourceManager
        {
            get
            {
                if (_resourceManager == null)
                {
                    _resourceManager = new ResourceManager(
                        "KPatcher.UI.Resources.UIResources",
                        typeof(UIResources).Assembly);
                }
                return _resourceManager;
            }
        }

        public static CultureInfo Culture
        {
            get => _resourceCulture;
            set => _resourceCulture = value;
        }

        public static string MenuTools => ResourceManager.GetString(nameof(MenuTools), _resourceCulture);
        public static string MenuHelp => ResourceManager.GetString(nameof(MenuHelp), _resourceCulture);
        public static string HelpWindowTitle => ResourceManager.GetString(nameof(HelpWindowTitle), _resourceCulture);
        public static string OK => ResourceManager.GetString(nameof(OK), _resourceCulture);
        public static string MenuAbout => ResourceManager.GetString(nameof(MenuAbout), _resourceCulture);
        public static string MenuLanguage => ResourceManager.GetString(nameof(MenuLanguage), _resourceCulture);
        public static string LanguageEnglish => ResourceManager.GetString(nameof(LanguageEnglish), _resourceCulture);
        public static string LanguageSpanish => ResourceManager.GetString(nameof(LanguageSpanish), _resourceCulture);
        public static string LanguageGerman => ResourceManager.GetString(nameof(LanguageGerman), _resourceCulture);
        public static string LanguageFrench => ResourceManager.GetString(nameof(LanguageFrench), _resourceCulture);
        public static string LanguageRussian => ResourceManager.GetString(nameof(LanguageRussian), _resourceCulture);
        public static string LanguagePolish => ResourceManager.GetString(nameof(LanguagePolish), _resourceCulture);
        public static string ValidateIni => ResourceManager.GetString(nameof(ValidateIni), _resourceCulture);
        public static string UninstallModRestoreBackup => ResourceManager.GetString(nameof(UninstallModRestoreBackup), _resourceCulture);
        public static string FixPermissionsToFileFolder => ResourceManager.GetString(nameof(FixPermissionsToFileFolder), _resourceCulture);
        public static string FixIOSCaseSensitivity => ResourceManager.GetString(nameof(FixIOSCaseSensitivity), _resourceCulture);
        public static string DeadlyStream => ResourceManager.GetString(nameof(DeadlyStream), _resourceCulture);
        public static string Discord => ResourceManager.GetString(nameof(Discord), _resourceCulture);
        public static string Website => ResourceManager.GetString(nameof(Website), _resourceCulture);
        public static string KOTORCommunityPortal => ResourceManager.GetString(nameof(KOTORCommunityPortal), _resourceCulture);
        public static string PCGamingWiki => ResourceManager.GetString(nameof(PCGamingWiki), _resourceCulture);
        public static string KOTOR1 => ResourceManager.GetString(nameof(KOTOR1), _resourceCulture);
        public static string KOTOR2TSL => ResourceManager.GetString(nameof(KOTOR2TSL), _resourceCulture);
        public static string CheckForUpdates => ResourceManager.GetString(nameof(CheckForUpdates), _resourceCulture);
        public static string KPatcherHome => ResourceManager.GetString(nameof(KPatcherHome), _resourceCulture);
        public static string GitHubSource => ResourceManager.GetString(nameof(GitHubSource), _resourceCulture);
        public static string Exit => ResourceManager.GetString(nameof(Exit), _resourceCulture);
        public static string Browse => ResourceManager.GetString(nameof(Browse), _resourceCulture);
        public static string PlaceholderSelectMod => ResourceManager.GetString(nameof(PlaceholderSelectMod), _resourceCulture);
        public static string PlaceholderSelectKotor => ResourceManager.GetString(nameof(PlaceholderSelectKotor), _resourceCulture);
        public static string AlphaBannerText => ResourceManager.GetString(nameof(AlphaBannerText), _resourceCulture);
        public static string AlphaWarningTitle => ResourceManager.GetString(nameof(AlphaWarningTitle), _resourceCulture);
        public static string AlphaWarningMessageFormat => ResourceManager.GetString(nameof(AlphaWarningMessageFormat), _resourceCulture);
        public static string MainWindowTitle => ResourceManager.GetString(nameof(MainWindowTitle), _resourceCulture);
        public static string WindowTitleFormat => ResourceManager.GetString(nameof(WindowTitleFormat), _resourceCulture);
        public static string WindowTitleAlphaSuffix => ResourceManager.GetString(nameof(WindowTitleAlphaSuffix), _resourceCulture);
        public static string KOTORPatcherUpdate => ResourceManager.GetString(nameof(KOTORPatcherUpdate), _resourceCulture);
        public static string Cancel => ResourceManager.GetString(nameof(Cancel), _resourceCulture);
        public static string WelcomeToKPatcher => ResourceManager.GetString(nameof(WelcomeToKPatcher), _resourceCulture);
        public static string SelectModAndKotorToBegin => ResourceManager.GetString(nameof(SelectModAndKotorToBegin), _resourceCulture);
        public static string StartingInstallation => ResourceManager.GetString(nameof(StartingInstallation), _resourceCulture);
        public static string PatcherFinishedTitle => ResourceManager.GetString(nameof(PatcherFinishedTitle), _resourceCulture);
        public static string SelectModDirectory => ResourceManager.GetString(nameof(SelectModDirectory), _resourceCulture);
        public static string SelectKotorDirectory => ResourceManager.GetString(nameof(SelectKotorDirectory), _resourceCulture);
        public static string ThisModRequiresConfirmation => ResourceManager.GetString(nameof(ThisModRequiresConfirmation), _resourceCulture);
        public static string StartPatchingButtonLabel => ResourceManager.GetString(nameof(StartPatchingButtonLabel), _resourceCulture);
        public static string Error => ResourceManager.GetString(nameof(Error), _resourceCulture);
        public static string WarningTitle => ResourceManager.GetString(nameof(WarningTitle), _resourceCulture);
        public static string WarningNotAToy => ResourceManager.GetString(nameof(WarningNotAToy), _resourceCulture);
        public static string SelectDirectoryFixPermissions => ResourceManager.GetString(nameof(SelectDirectoryFixPermissions), _resourceCulture);
        public static string PleaseWaitMayTakeAWhile => ResourceManager.GetString(nameof(PleaseWaitMayTakeAWhile), _resourceCulture);
        public static string SuccessfullyAcquiredPermission => ResourceManager.GetString(nameof(SuccessfullyAcquiredPermission), _resourceCulture);
        public static string OperationSuccessfulFormat => ResourceManager.GetString(nameof(OperationSuccessfulFormat), _resourceCulture);
        public static string FilesAndFoldersProcessedFormat => ResourceManager.GetString(nameof(FilesAndFoldersProcessedFormat), _resourceCulture);
        public static string CouldNotAcquirePermission => ResourceManager.GetString(nameof(CouldNotAcquirePermission), _resourceCulture);
        public static string PermissionsDeniedCheckLogsFormat => ResourceManager.GetString(nameof(PermissionsDeniedCheckLogsFormat), _resourceCulture);
        public static string SelectDirectoryFixCaseSensitivity => ResourceManager.GetString(nameof(SelectDirectoryFixCaseSensitivity), _resourceCulture);
        public static string NothingToChangeCase => ResourceManager.GetString(nameof(NothingToChangeCase), _resourceCulture);
        public static string IOSCaseRenameTaskCompleted => ResourceManager.GetString(nameof(IOSCaseRenameTaskCompleted), _resourceCulture);
        public static string UpdateError => ResourceManager.GetString(nameof(UpdateError), _resourceCulture);
        public static string UnableToFetchUpdateInfo => ResourceManager.GetString(nameof(UnableToFetchUpdateInfo), _resourceCulture);
        public static string UpdateAvailable => ResourceManager.GetString(nameof(UpdateAvailable), _resourceCulture);
        public static string UpdateAvailableMessageFormat => ResourceManager.GetString(nameof(UpdateAvailableMessageFormat), _resourceCulture);
        public static string UpdateButton => ResourceManager.GetString(nameof(UpdateButton), _resourceCulture);
        public static string ManualDownloadButton => ResourceManager.GetString(nameof(ManualDownloadButton), _resourceCulture);
        public static string NoUpdatesFound => ResourceManager.GetString(nameof(NoUpdatesFound), _resourceCulture);
        public static string NoUpdatesFoundMessageFormat => ResourceManager.GetString(nameof(NoUpdatesFoundMessageFormat), _resourceCulture);
        public static string ReinstallButton => ResourceManager.GetString(nameof(ReinstallButton), _resourceCulture);
        public static string NoNamespaceSelected => ResourceManager.GetString(nameof(NoNamespaceSelected), _resourceCulture);
        public static string PleaseSelectNamespaceFirst => ResourceManager.GetString(nameof(PleaseSelectNamespaceFirst), _resourceCulture);
        public static string NoDescriptionAvailable => ResourceManager.GetString(nameof(NoDescriptionAvailable), _resourceCulture);
        public static string CouldNotFindModAtFolderFormat => ResourceManager.GetString(nameof(CouldNotFindModAtFolderFormat), _resourceCulture);
        public static string TaskAlreadyRunning => ResourceManager.GetString(nameof(TaskAlreadyRunning), _resourceCulture);
        public static string WaitForPreviousTask => ResourceManager.GetString(nameof(WaitForPreviousTask), _resourceCulture);
        public static string NoModChosen => ResourceManager.GetString(nameof(NoModChosen), _resourceCulture);
        public static string SelectModDirectoryFirst => ResourceManager.GetString(nameof(SelectModDirectoryFirst), _resourceCulture);
        public static string NoGameFolder => ResourceManager.GetString(nameof(NoGameFolder), _resourceCulture);
        public static string InvalidGameFolder => ResourceManager.GetString(nameof(InvalidGameFolder), _resourceCulture);
        public static string PreparingUpdate => ResourceManager.GetString(nameof(PreparingUpdate), _resourceCulture);
        public static string EstimatedTimeRemainingFormat => ResourceManager.GetString(nameof(EstimatedTimeRemainingFormat), _resourceCulture);
        public static string Downloaded => ResourceManager.GetString(nameof(Downloaded), _resourceCulture);
        public static string ByteB => ResourceManager.GetString(nameof(ByteB), _resourceCulture);
        public static string ByteKB => ResourceManager.GetString(nameof(ByteKB), _resourceCulture);
        public static string ByteMB => ResourceManager.GetString(nameof(ByteMB), _resourceCulture);
        public static string ByteGB => ResourceManager.GetString(nameof(ByteGB), _resourceCulture);
        public static string DownloadingKPatcherFormat => ResourceManager.GetString(nameof(DownloadingKPatcherFormat), _resourceCulture);
        public static string DownloadComplete => ResourceManager.GetString(nameof(DownloadComplete), _resourceCulture);
        public static string ExtractingUpdatePackage => ResourceManager.GetString(nameof(ExtractingUpdatePackage), _resourceCulture);
        public static string ArchiveExtracted => ResourceManager.GetString(nameof(ArchiveExtracted), _resourceCulture);
        public static string FinalizingUpdate => ResourceManager.GetString(nameof(FinalizingUpdate), _resourceCulture);
        public static string RestartingToCompleteUpdate => ResourceManager.GetString(nameof(RestartingToCompleteUpdate), _resourceCulture);
        public static string DownloadFailedFromFormat => ResourceManager.GetString(nameof(DownloadFailedFromFormat), _resourceCulture);
        public static string AllUpdateMirrorsFailed => ResourceManager.GetString(nameof(AllUpdateMirrorsFailed), _resourceCulture);
        public static string UnsavedChanges => ResourceManager.GetString(nameof(UnsavedChanges), _resourceCulture);
        public static string UnsavedChangesDiscardPrompt => ResourceManager.GetString(nameof(UnsavedChangesDiscardPrompt), _resourceCulture);
        public static string FailedToLoadRtfContent => ResourceManager.GetString(nameof(FailedToLoadRtfContent), _resourceCulture);
        public static string Untitled => ResourceManager.GetString(nameof(Untitled), _resourceCulture);
        public static string MenuFile => ResourceManager.GetString(nameof(MenuFile), _resourceCulture);
        public static string MenuNew => ResourceManager.GetString(nameof(MenuNew), _resourceCulture);
        public static string MenuOpen => ResourceManager.GetString(nameof(MenuOpen), _resourceCulture);
        public static string MenuSave => ResourceManager.GetString(nameof(MenuSave), _resourceCulture);
        public static string MenuSaveAs => ResourceManager.GetString(nameof(MenuSaveAs), _resourceCulture);
        public static string MenuClose => ResourceManager.GetString(nameof(MenuClose), _resourceCulture);
        public static string Bold => ResourceManager.GetString(nameof(Bold), _resourceCulture);
        public static string Italic => ResourceManager.GetString(nameof(Italic), _resourceCulture);
        public static string Underline => ResourceManager.GetString(nameof(Underline), _resourceCulture);
        public static string Strike => ResourceManager.GetString(nameof(Strike), _resourceCulture);
        public static string AlignLeft => ResourceManager.GetString(nameof(AlignLeft), _resourceCulture);
        public static string AlignCenter => ResourceManager.GetString(nameof(AlignCenter), _resourceCulture);
        public static string AlignRight => ResourceManager.GetString(nameof(AlignRight), _resourceCulture);
        public static string ColorBlack => ResourceManager.GetString(nameof(ColorBlack), _resourceCulture);
        public static string ColorRed => ResourceManager.GetString(nameof(ColorRed), _resourceCulture);
        public static string ColorGreen => ResourceManager.GetString(nameof(ColorGreen), _resourceCulture);
        public static string ColorBlue => ResourceManager.GetString(nameof(ColorBlue), _resourceCulture);
        public static string ColorGray => ResourceManager.GetString(nameof(ColorGray), _resourceCulture);
        public static string ColorTransparent => ResourceManager.GetString(nameof(ColorTransparent), _resourceCulture);
        public static string ColorYellow => ResourceManager.GetString(nameof(ColorYellow), _resourceCulture);
        public static string ColorLightBlue => ResourceManager.GetString(nameof(ColorLightBlue), _resourceCulture);
        public static string ColorLightGreen => ResourceManager.GetString(nameof(ColorLightGreen), _resourceCulture);
        public static string InstallationCompleteWithErrorsAndWarningsFormat => ResourceManager.GetString(nameof(InstallationCompleteWithErrorsAndWarningsFormat), _resourceCulture);
        public static string UnexpectedErrorDuringInstallationFormat => ResourceManager.GetString(nameof(UnexpectedErrorDuringInstallationFormat), _resourceCulture);
        public static string ConfigReaderTestComplete => ResourceManager.GetString(nameof(ConfigReaderTestComplete), _resourceCulture);
        public static string UninstallProcessFinished => ResourceManager.GetString(nameof(UninstallProcessFinished), _resourceCulture);
        public static string PermissionsFixerTaskCompleted => ResourceManager.GetString(nameof(PermissionsFixerTaskCompleted), _resourceCulture);
        public static string AtLeastOneOptionRequired => ResourceManager.GetString(nameof(AtLeastOneOptionRequired), _resourceCulture);
        public static string DefaultInstallation => ResourceManager.GetString(nameof(DefaultInstallation), _resourceCulture);
        public static string LoadedNamespacesCountFormat => ResourceManager.GetString(nameof(LoadedNamespacesCountFormat), _resourceCulture);
        public static string DetectedKotorInstallationsFormat => ResourceManager.GetString(nameof(DetectedKotorInstallationsFormat), _resourceCulture);
        public static string AutoOpeningModFromFormat => ResourceManager.GetString(nameof(AutoOpeningModFromFormat), _resourceCulture);
        public static string InstallationCancelled => ResourceManager.GetString(nameof(InstallationCancelled), _resourceCulture);
        public static string NoBackupDirectoryFoundFormat => ResourceManager.GetString(nameof(NoBackupDirectoryFoundFormat), _resourceCulture);
        public static string UninstallFailedFormat => ResourceManager.GetString(nameof(UninstallFailedFormat), _resourceCulture);
        public static string UnableToLocateWindowForUpdater => ResourceManager.GetString(nameof(UnableToLocateWindowForUpdater), _resourceCulture);
        public static string FailedToLoadModFormat => ResourceManager.GetString(nameof(FailedToLoadModFormat), _resourceCulture);
        public static string FailedToLoadNamespaceConfigFormat => ResourceManager.GetString(nameof(FailedToLoadNamespaceConfigFormat), _resourceCulture);
        public static string PleaseSelectModAndGameDirectory => ResourceManager.GetString(nameof(PleaseSelectModAndGameDirectory), _resourceCulture);
        public static string InstallationFailedFormat => ResourceManager.GetString(nameof(InstallationFailedFormat), _resourceCulture);
        public static string ValidationFailedFormat => ResourceManager.GetString(nameof(ValidationFailedFormat), _resourceCulture);
        public static string FailedToFixPermissionsFormat => ResourceManager.GetString(nameof(FailedToFixPermissionsFormat), _resourceCulture);
        public static string FailedToFixCaseSensitivityFormat => ResourceManager.GetString(nameof(FailedToFixCaseSensitivityFormat), _resourceCulture);
        public static string FailedToOpenUrlFormat => ResourceManager.GetString(nameof(FailedToOpenUrlFormat), _resourceCulture);
        public static string NoBackupsFoundTitle => ResourceManager.GetString(nameof(NoBackupsFoundTitle), _resourceCulture);
        public static string NoBackupsFoundMessageFormat => ResourceManager.GetString(nameof(NoBackupsFoundMessageFormat), _resourceCulture);
        public static string BackupOutOfDateOrMismatched => ResourceManager.GetString(nameof(BackupOutOfDateOrMismatched), _resourceCulture);
        public static string BackupMismatchMessageFormat => ResourceManager.GetString(nameof(BackupMismatchMessageFormat), _resourceCulture);
        public static string Confirmation => ResourceManager.GetString(nameof(Confirmation), _resourceCulture);
        public static string ReallyUninstallConfirmFormat => ResourceManager.GetString(nameof(ReallyUninstallConfirmFormat), _resourceCulture);
        public static string FailedToRestoreBackupFormat => ResourceManager.GetString(nameof(FailedToRestoreBackupFormat), _resourceCulture);
        public static string UninstallCompletedTitle => ResourceManager.GetString(nameof(UninstallCompletedTitle), _resourceCulture);
        public static string UninstallCompletedDeleteBackupFormat => ResourceManager.GetString(nameof(UninstallCompletedDeleteBackupFormat), _resourceCulture);
        public static string PermissionErrorTitle => ResourceManager.GetString(nameof(PermissionErrorTitle), _resourceCulture);
        public static string UnableToDeleteBackupPermissionFormat => ResourceManager.GetString(nameof(UnableToDeleteBackupPermissionFormat), _resourceCulture);
        public static string GainingPermissionPleaseWait => ResourceManager.GetString(nameof(GainingPermissionPleaseWait), _resourceCulture);
    }
}

#pragma warning restore CS1591
