using System.Collections.Generic;

namespace BioWareCSharp.Common.Extract
{
    // Minimal registry matching PyKotor extract/twoda.py structure.
    // Matching PyKotor extract/twoda.py StrRefs/ResRefs mappings (K1)
    public static class TwoDARegistry
    {
        private static readonly Dictionary<string, HashSet<string>> StrRefColumns = new Dictionary<string, HashSet<string>>
        {
            ["actions.2da"] = new HashSet<string> { "string_ref" },
            ["aiscripts.2da"] = new HashSet<string> { "name_strref", "description_strref" },
            ["ambientsound.2da"] = new HashSet<string> { "description" },
            ["appearance.2da"] = new HashSet<string> { "string_ref" },
            ["bindablekeys.2da"] = new HashSet<string> { "keynamestrref" },
            ["classes.2da"] = new HashSet<string> { "name", "description" },
            ["crtemplates.2da"] = new HashSet<string> { "strref" },
            ["creaturesize.2da"] = new HashSet<string> { "strref" },
            ["doortypes.2da"] = new HashSet<string> { "stringrefgame" },
            ["effecticons.2da"] = new HashSet<string> { "strref" },
            ["encdifficulty.2da"] = new HashSet<string> { "strref" },
            ["environment.2da"] = new HashSet<string> { "strref" },
            ["feat.2da"] = new HashSet<string> { "name", "description" },
            ["feedbacktext.2da"] = new HashSet<string> { "strref" },
            ["fractionalcr.2da"] = new HashSet<string> { "displaystrref" },
            ["gamespyrooms.2da"] = new HashSet<string> { "str_ref" },
            ["genericdoors.2da"] = new HashSet<string> { "strref" },
            ["hen_companion.2da"] = new HashSet<string> { "strref" },
            ["iprp_abilities.2da"] = new HashSet<string> { "name" },
            ["iprp_acmodtype.2da"] = new HashSet<string> { "name" },
            ["iprp_aligngrp.2da"] = new HashSet<string> { "name" },
            ["iprp_alignment.2da"] = new HashSet<string> { "name" },
            ["iprp_ammocost.2da"] = new HashSet<string> { "name" },
            ["iprp_ammotype.2da"] = new HashSet<string> { "name" },
            ["iprp_amount.2da"] = new HashSet<string> { "name" },
            ["iprp_bonuscost.2da"] = new HashSet<string> { "name" },
            ["iprp_chargecost.2da"] = new HashSet<string> { "name" },
            ["iprp_color.2da"] = new HashSet<string> { "name" },
            ["iprp_combatdam.2da"] = new HashSet<string> { "name" },
            ["iprp_damagecost.2da"] = new HashSet<string> { "name" },
            ["iprp_damagetype.2da"] = new HashSet<string> { "name" },
            ["iprp_damvulcost.2da"] = new HashSet<string> { "name" },
            ["iprp_feats.2da"] = new HashSet<string> { "name" },
            ["iprp_immuncost.2da"] = new HashSet<string> { "name" },
            ["iprp_immunity.2da"] = new HashSet<string> { "name" },
            ["iprp_lightcost.2da"] = new HashSet<string> { "name" },
            ["iprp_meleecost.2da"] = new HashSet<string> { "name" },
            ["iprp_monstcost.2da"] = new HashSet<string> { "name" },
            ["iprp_monsterhit.2da"] = new HashSet<string> { "name" },
            ["iprp_neg10cost.2da"] = new HashSet<string> { "name" },
            ["iprp_neg5cost.2da"] = new HashSet<string> { "name" },
            ["iprp_onhit.2da"] = new HashSet<string> { "name" },
            ["iprp_onhitcost.2da"] = new HashSet<string> { "name" },
            ["iprp_onhitdc.2da"] = new HashSet<string> { "name" },
            ["iprp_onhitdur.2da"] = new HashSet<string> { "name" },
            ["iprp_paramtable.2da"] = new HashSet<string> { "name" },
            ["iprp_poison.2da"] = new HashSet<string> { "name" },
            ["iprp_protection.2da"] = new HashSet<string> { "name" },
            ["iprp_redcost.2da"] = new HashSet<string> { "name" },
            ["iprp_resistcost.2da"] = new HashSet<string> { "name" },
            ["iprp_saveelement.2da"] = new HashSet<string> { "name" },
            ["iprp_savingthrow.2da"] = new HashSet<string> { "name" },
            ["iprp_soakcost.2da"] = new HashSet<string> { "name" },
            ["iprp_spellcost.2da"] = new HashSet<string> { "name" },
            ["iprp_spellvcost.2da"] = new HashSet<string> { "name" },
            ["iprp_spellvlimm.2da"] = new HashSet<string> { "name" },
            ["iprp_spells.2da"] = new HashSet<string> { "name" },
            ["iprp_spellshl.2da"] = new HashSet<string> { "name" },
            ["iprp_srcost.2da"] = new HashSet<string> { "name" },
            ["iprp_trapcost.2da"] = new HashSet<string> { "name" },
            ["iprp_traps.2da"] = new HashSet<string> { "name" },
            ["iprp_walk.2da"] = new HashSet<string> { "name" },
            ["iprp_weightcost.2da"] = new HashSet<string> { "name" },
            ["iprp_weightinc.2da"] = new HashSet<string> { "name" },
            ["itempropdef.2da"] = new HashSet<string> { "name" },
            ["itemprops.2da"] = new HashSet<string> { "stringref" },
            ["keymap.2da"] = new HashSet<string> { "actionstrref" },
            ["loadscreenhints.2da"] = new HashSet<string> { "gameplayhint", "storyhint" },
            ["masterfeats.2da"] = new HashSet<string> { "strref" },
            ["modulesave.2da"] = new HashSet<string> { "areaname" },
            ["movies.2da"] = new HashSet<string> { "strrefname", "strrefdesc" },
            ["placeables.2da"] = new HashSet<string> { "strref" },
            ["planetary.2da"] = new HashSet<string> { "name", "description" },
            ["soundset.2da"] = new HashSet<string> { "strref" },
            ["stringtokens.2da"] = new HashSet<string> { "strref1", "strref2", "strref3", "strref4" },
            ["texpacks.2da"] = new HashSet<string> { "strrefname" },
            ["tutorial.2da"] = new HashSet<string> { "message0", "message1", "message2" },
            ["tutorial_old.2da"] = new HashSet<string> { "message0", "message1", "message2" },
            ["skills.2da"] = new HashSet<string> { "name", "description" },
            ["spells.2da"] = new HashSet<string> { "name", "spelldesc" },
            ["traps.2da"] = new HashSet<string> { "trapname", "name" },
        };

        private static readonly Dictionary<string, HashSet<string>> ResRefColumns = new Dictionary<string, HashSet<string>>
        {
            ["appearance.2da"] = new HashSet<string> { "race" },
            ["droiddischarge.2da"] = new HashSet<string> { ">>##HEADER##<<" },
            ["hen_companion.2da"] = new HashSet<string> { "baseresref" },
            ["hen_familiar.2da"] = new HashSet<string> { "baseresref" },
            ["iprp_paramtable.2da"] = new HashSet<string> { "tableresref" },
            ["itempropdef.2da"] = new HashSet<string> { "subtyperesref", "param1resref", "gamestrref", "description" },
            ["minglobalrim.2da"] = new HashSet<string> { "moduleresref" },
            ["modulesave.2da"] = new HashSet<string> { "modulename" },
            // Models
            ["ammunitiontypes.2da"] = new HashSet<string> { "model", "model0", "model1", "model2", "muzzleflash" },
            ["baseitems.2da"] = new HashSet<string> { "defaultmodel" },
            ["placeables.2da"] = new HashSet<string> { "modelname" },
            ["planetary.2da"] = new HashSet<string> { "model" },
            ["upcrystals.2da"] = new HashSet<string> { "shortmdlvar", "longmdlvar", "doublemdlvar" },
            ["doortypes.2da"] = new HashSet<string> { "model" },
            ["genericdoors.2da"] = new HashSet<string> { "modelname" },
            // Sounds
            ["aliensound.2da"] = new HashSet<string> { "filename" },
            ["ambientsound.2da"] = new HashSet<string> { "resource" },
            ["ammunitiontypes.2da-snd"] = new HashSet<string> { "shotsound0", "shotsound1", "impactsound0", "impactsound1" },
            ["appearancesndset.2da"] = new HashSet<string> { "falldirt", "fallhard", "fallmetal", "fallwater" },
            ["baseitems.2da-snd"] = new HashSet<string> { "powerupsnd", "powerdownsnd", "poweredsnd" },
            ["footstepsounds.2da"] = new HashSet<string>
            {
                "rolling",
                "dirt0", "dirt1", "dirt2",
                "grass0", "grass1", "grass2",
                "stone0", "stone1", "stone2",
                "wood0", "wood1", "wood2",
                "water0", "water1", "water2",
                "carpet0", "carpet1", "carpet2",
                "metal0", "metal1", "metal2",
                "puddles0", "puddles1", "puddles2",
                "leaves0", "leaves1", "leaves2",
                "force1", "force2", "force3"
            },
            ["grenadesnd.2da"] = new HashSet<string> { "sound" },
            ["guisounds.2da"] = new HashSet<string> { "soundresref" },
            ["inventorysnds.2da"] = new HashSet<string> { "inventorysound" },
            // Music
            ["ambientmusic.2da"] = new HashSet<string> { "resource", "stinger1", "stinger2", "stinger3" },
            ["loadscreens.2da-music"] = new HashSet<string> { "musicresref" },
            // Textures
            ["actions.2da"] = new HashSet<string> { "iconresref" },
            ["appearance.2da-tex"] = new HashSet<string> { "racetex", "texa", "texb", "texc", "texd", "texe", "texf", "texg", "texh", "texi", "texj", "headtexve", "headtexe", "headtexvg", "headtexg" },
            ["baseitems.2da-tex"] = new HashSet<string> { "defaulticon" },
            ["effecticon.2da"] = new HashSet<string> { "iconresref" },
            ["heads.2da"] = new HashSet<string> { "head", "headtexvvve", "headtexvve", "headtexve", "headtexe", "headtexg", "headtexvg" },
            ["iprp_spells.2da"] = new HashSet<string> { "icon" },
            ["loadscreens.2da"] = new HashSet<string> { "bmpresref" },
            ["planetary.2da-tex"] = new HashSet<string> { "icon" },
            // Items / GUIs / Scripts
            ["baseitems.2da-item"] = new HashSet<string> { "itemclass", "baseitemstatref" },
            ["chargenclothes.2da"] = new HashSet<string> { "itemresref" },
            ["feat.2da-icon"] = new HashSet<string> { "icon" },
            ["cursors.2da"] = new HashSet<string> { "resref" },
            ["areaeffects.2da"] = new HashSet<string> { "onenter", "heartbeat", "onexit" },
            ["disease.2da"] = new HashSet<string> { "end_incu_script", "24_hour_script" },
            ["spells.2da-script"] = new HashSet<string> { "impactscript" },
        };

        // K2 StrRef columns
        private static readonly Dictionary<string, HashSet<string>> StrRefColumnsK2 = new Dictionary<string, HashSet<string>>
        {
            ["aiscripts.2da"] = new HashSet<string> { "name_strref" },
            ["ambientsound.2da"] = new HashSet<string> { "description" },
            ["appearance.2da"] = new HashSet<string> { "string_ref" },
            ["bindablekeys.2da"] = new HashSet<string> { "keynamestrref" },
            ["classes.2da"] = new HashSet<string> { "name", "description" },
            ["credits.2da"] = new HashSet<string> { "name" },
            ["crtemplates.2da"] = new HashSet<string> { "strref" },
            ["creaturesize.2da"] = new HashSet<string> { "strref" },
            ["difficultyo p.2da"] = new HashSet<string> { "name" },
            ["disease.2da"] = new HashSet<string> { "name" },
            ["doortypes.2da"] = new HashSet<string> { "stringrefgame" },
            ["effecticons.2da"] = new HashSet<string> { "strref" },
            ["encdifficulty.2da"] = new HashSet<string> { "strref" },
            ["environment.2da"] = new HashSet<string> { "strref" },
            ["feat.2da"] = new HashSet<string> { "name", "description" },
            ["feedbacktext.2da"] = new HashSet<string> { "strref" },
            ["fractionalcr.2da"] = new HashSet<string> { "displaystrref" },
            ["gamespyrooms.2da"] = new HashSet<string> { "str_ref" },
            ["genericdoors.2da"] = new HashSet<string> { "strref" },
            ["hen_companion.2da"] = new HashSet<string> { "strref" },
            ["iprp_abilities.2da"] = new HashSet<string> { "name" },
            ["iprp_acmodtype.2da"] = new HashSet<string> { "name" },
            ["iprp_aligngrp.2da"] = new HashSet<string> { "name" },
            ["iprp_alignment.2da"] = new HashSet<string> { "name" },
            ["iprp_ammocost.2da"] = new HashSet<string> { "name" },
            ["iprp_ammotype.2da"] = new HashSet<string> { "name" },
            ["iprp_amount.2da"] = new HashSet<string> { "name" },
            ["iprp_bonuscost.2da"] = new HashSet<string> { "name" },
            ["iprp_chargecost.2da"] = new HashSet<string> { "name" },
            ["iprp_color.2da"] = new HashSet<string> { "name" },
            ["iprp_combatdam.2da"] = new HashSet<string> { "name" },
            ["iprp_damagecost.2da"] = new HashSet<string> { "name" },
            ["iprp_damagetype.2da"] = new HashSet<string> { "name" },
            ["iprp_damvulcost.2da"] = new HashSet<string> { "name" },
            ["iprp_feats.2da"] = new HashSet<string> { "name" },
            ["iprp_immuncost.2da"] = new HashSet<string> { "name" },
            ["iprp_immunity.2da"] = new HashSet<string> { "name" },
            ["iprp_lightcost.2da"] = new HashSet<string> { "name" },
            ["iprp_meleecost.2da"] = new HashSet<string> { "name" },
            ["iprp_monstcost.2da"] = new HashSet<string> { "name" },
            ["iprp_monsterhit.2da"] = new HashSet<string> { "name" },
            ["iprp_neg10cost.2da"] = new HashSet<string> { "name" },
            ["iprp_neg5cost.2da"] = new HashSet<string> { "name" },
            ["iprp_onhit.2da"] = new HashSet<string> { "name" },
            ["iprp_onhitcost.2da"] = new HashSet<string> { "name" },
            ["iprp_onhitdc.2da"] = new HashSet<string> { "name" },
            ["iprp_onhitdur.2da"] = new HashSet<string> { "name" },
            ["iprp_paramtable.2da"] = new HashSet<string> { "name" },
            ["iprp_poison.2da"] = new HashSet<string> { "name" },
            ["iprp_protection.2da"] = new HashSet<string> { "name" },
            ["iprp_redcost.2da"] = new HashSet<string> { "name" },
            ["iprp_resistcost.2da"] = new HashSet<string> { "name" },
            ["iprp_saveelement.2da"] = new HashSet<string> { "name" },
            ["iprp_savingthrow.2da"] = new HashSet<string> { "name" },
            ["iprp_soakcost.2da"] = new HashSet<string> { "name" },
            ["iprp_spellcost.2da"] = new HashSet<string> { "name" },
            ["iprp_spellvcost.2da"] = new HashSet<string> { "name" },
            ["iprp_spellvlimm.2da"] = new HashSet<string> { "name" },
            ["iprp_spells.2da"] = new HashSet<string> { "name" },
            ["iprp_spellshl.2da"] = new HashSet<string> { "name" },
            ["iprp_srcost.2da"] = new HashSet<string> { "name" },
            ["iprp_trapcost.2da"] = new HashSet<string> { "name" },
            ["iprp_traps.2da"] = new HashSet<string> { "name" },
            ["iprp_walk.2da"] = new HashSet<string> { "name" },
            ["iprp_weightcost.2da"] = new HashSet<string> { "name" },
            ["iprp_weightinc.2da"] = new HashSet<string> { "name" },
            ["itempropdef.2da"] = new HashSet<string> { "name" },
            ["itemprops.2da"] = new HashSet<string> { "stringref" },
            ["keymap.2da"] = new HashSet<string> { "actionstrref" },
            ["loadscreenhints.2da"] = new HashSet<string> { "gameplayhint", "storyhint" },
            ["masterfeats.2da"] = new HashSet<string> { "strref" },
            ["modulesave.2da"] = new HashSet<string> { "areaname" },
            ["movies.2da"] = new HashSet<string> { "strrefname", "strrefdesc" },
            ["placeables.2da"] = new HashSet<string> { "strref" },
            ["planetary.2da"] = new HashSet<string> { "name", "description" },
            ["soundset.2da"] = new HashSet<string> { "strref" },
            ["stringtokens.2da"] = new HashSet<string> { "strref1", "strref2", "strref3", "strref4" },
            ["texpacks.2da"] = new HashSet<string> { "strrefname" },
            ["tutorial.2da"] = new HashSet<string> { "message0", "message1", "message2" },
            ["tutorial_old.2da"] = new HashSet<string> { "message0", "message1", "message2" },
            ["skills.2da"] = new HashSet<string> { "name", "description" },
            ["spells.2da"] = new HashSet<string> { "name", "spelldesc" },
            ["traps.2da"] = new HashSet<string> { "trapname", "name" },
        };

        // K2 ResRef columns
        private static readonly Dictionary<string, HashSet<string>> ResRefColumnsK2 = new Dictionary<string, HashSet<string>>
        {
            ["ammunitiontypes.2da"] = new HashSet<string> { "muzzleflash" },
            ["appearance.2da"] = new HashSet<string> { "race" },
            ["droiddischarge.2da"] = new HashSet<string> { ">>##HEADER##<<" },
            ["hen_companion.2da"] = new HashSet<string> { "baseresref" },
            ["hen_familiar.2da"] = new HashSet<string> { "baseresref" },
            ["iprp_paramtable.2da"] = new HashSet<string> { "tableresref" },
            ["itempropdef.2da"] = new HashSet<string> { "subtyperesref", "param1resref", "gamestrref", "description" },
            ["minglobalrim.2da"] = new HashSet<string> { "moduleresref" },
            ["modulesave.2da"] = new HashSet<string> { "modulename" },
            // Models
            ["ammunitiontypes.2da-model"] = new HashSet<string> { "model", "model0", "model1" },
            ["appearance.2da-model"] = new HashSet<string> { "modela", "modelb", "modelc", "modeld", "modele", "modelf", "modelg", "modelh", "modeli", "modelj" },
            ["baseitems.2da"] = new HashSet<string> { "defaultmodel" },
            ["placeables.2da"] = new HashSet<string> { "modelname" },
            ["planetary.2da-model"] = new HashSet<string> { "model" },
            ["upcrystals.2da"] = new HashSet<string> { "shortmdlvar", "longmdlvar", "doublemdlvar" },
            ["doortypes.2da"] = new HashSet<string> { "model" },
            ["genericdoors.2da"] = new HashSet<string> { "modelname" },
            // Sounds
            ["aliensound.2da"] = new HashSet<string> { "filename" },
            ["alienvo.2da"] = new HashSet<string>
            {
                "angry_long", "angry_medium", "angry_short",
                "comment_generic_long", "comment_generic_medium", "comment_generic_short",
                "greeting_medium", "greeting_short",
                "happy_thankful_long", "happy_thankful_medium", "happy_thankful_short",
                "laughter_normal", "laughter_mocking_medium", "laughter_mocking_short", "laughter_long", "laughter_short",
                "pleading_medium", "pleading_short",
                "question_long", "question_medium", "question_short",
                "sad_long", "sad_medium", "sad_short",
                "scared_long", "scared_medium", "scared_short",
                "seductive_long", "seductive_medium", "seductive_short",
                "silence",
                "wounded_medium", "wounded_small",
                "screaming_medium", "screaming_small"
            },
            ["ambientsound.2da"] = new HashSet<string> { "resource" },
            ["ammunitiontypes.2da-snd"] = new HashSet<string> { "shotsound0", "shotsound1", "impactsound0", "impactsound1" },
            ["appearancesndset.2da"] = new HashSet<string> { "falldirt", "fallhard", "fallmetal", "fallwater" },
            ["baseitems.2da-snd"] = new HashSet<string> { "powerupsnd", "powerdownsnd", "poweredsnd" },
            ["footstepsounds.2da"] = new HashSet<string>
            {
                "rolling",
                "dirt0", "dirt1", "dirt2",
                "grass0", "grass1", "grass2",
                "stone0", "stone1", "stone2",
                "wood0", "wood1", "wood2",
                "water0", "water1", "water2",
                "carpet0", "carpet1", "carpet2",
                "metal0", "metal1", "metal2",
                "puddles0", "puddles1", "puddles2",
                "leaves0", "leaves1", "leaves2",
                "force1", "force2", "force3"
            },
            ["grenadesnd.2da"] = new HashSet<string> { "sound" },
            ["guisounds.2da"] = new HashSet<string> { "soundresref" },
            ["inventorysnds.2da"] = new HashSet<string> { "inventorysound" },
            ["ambientmusic.2da"] = new HashSet<string> { "resource", "stinger1", "stinger2", "stinger3" },
            ["loadscreens.2da-music"] = new HashSet<string> { "musicresref" },
            // Textures
            ["actions.2da"] = new HashSet<string> { "iconresref" },
            ["appearance.2da-tex"] = new HashSet<string> { "racetex", "texa", "texb", "texc", "texd", "texe", "texf", "texg", "texh", "texi", "texj", "headtexve", "headtexe", "headtexvg", "headtexg" },
            ["cursors.2da"] = new HashSet<string> { "resref" },
            ["baseitems.2da-tex"] = new HashSet<string> { "defaulticon" },
            ["effecticon.2da"] = new HashSet<string> { "iconresref" },
            ["heads.2da"] = new HashSet<string> { "head", "headtexvvve", "headtexvve", "headtexve", "headtexe", "headtexg", "headtexvg" },
            ["iprp_spells.2da"] = new HashSet<string> { "icon" },
            ["loadscreens.2da"] = new HashSet<string> { "bmpresref" },
            ["planetary.2da-tex"] = new HashSet<string> { "icon" },
            // Items / GUIs / Scripts
            ["baseitems.2da-item"] = new HashSet<string> { "itemclass", "baseitemstatref" },
            ["chargenclothes.2da"] = new HashSet<string> { "itemresref" },
            ["feat.2da-icon"] = new HashSet<string> { "icon" },
            ["cursors.2da-gui"] = new HashSet<string> { "resref" },
            ["areaeffects.2da"] = new HashSet<string> { "onenter", "heartbeat", "onexit" },
            ["disease.2da-script"] = new HashSet<string> { "end_incu_script", "24_hour_script" },
            ["spells.2da-script"] = new HashSet<string> { "impactscript" },
        };

        public static Dictionary<string, HashSet<string>> ColumnsFor(string dataType, bool useK2 = false)
        {
            if (dataType == "strref")
            {
                return useK2 ? StrRefColumnsK2 : StrRefColumns;
            }

            return useK2 ? ResRefColumnsK2 : ResRefColumns;
        }

        public static HashSet<string> Files(bool useK2 = false)
        {
            var files = new HashSet<string>();
            var strref = useK2 ? StrRefColumnsK2 : StrRefColumns;
            var resref = useK2 ? ResRefColumnsK2 : ResRefColumns;
            foreach (var k in strref.Keys) files.Add(k);
            foreach (var k in resref.Keys) files.Add(k);
            return files;
        }

        // Matching PyKotor implementation at Libraries/PyKotor/src/pykotor/extract/twoda.py:596-599
        // Original: @classmethod def gff_field_mapping(cls) -> dict[str, ResourceIdentifier]:
        /// <summary>
        /// Get the mapping from GFF field names to 2DA ResourceIdentifiers.
        /// </summary>
        public static Dictionary<string, Resources.ResourceIdentifier> GffFieldMapping()
        {
            // Matching PyKotor implementation at Libraries/PyKotor/src/pykotor/extract/twoda.py:521-594
            // Centralize the GFF field mapping here
            return new Dictionary<string, Resources.ResourceIdentifier>
            {
                ["SoundSetFile"] = new Resources.ResourceIdentifier("soundset", Resources.ResourceType.TwoDA),
                ["PortraitId"] = new Resources.ResourceIdentifier("portraits", Resources.ResourceType.TwoDA),
                ["Appearance_Type"] = new Resources.ResourceIdentifier("appearance", Resources.ResourceType.TwoDA),
                ["Phenotype"] = new Resources.ResourceIdentifier("phenotype", Resources.ResourceType.TwoDA),
                ["FactionID"] = new Resources.ResourceIdentifier("faction", Resources.ResourceType.TwoDA),
                ["Faction"] = new Resources.ResourceIdentifier("faction", Resources.ResourceType.TwoDA),
                ["Subrace"] = new Resources.ResourceIdentifier("subrace", Resources.ResourceType.TwoDA),
                ["SubraceIndex"] = new Resources.ResourceIdentifier("subrace", Resources.ResourceType.TwoDA),
                ["Race"] = new Resources.ResourceIdentifier("racialtypes", Resources.ResourceType.TwoDA),
                ["Class"] = new Resources.ResourceIdentifier("classes", Resources.ResourceType.TwoDA),
                ["Gender"] = new Resources.ResourceIdentifier("gender", Resources.ResourceType.TwoDA),
                ["PerceptionRange"] = new Resources.ResourceIdentifier("perception", Resources.ResourceType.TwoDA),
                ["WalkRate"] = new Resources.ResourceIdentifier("walkrate", Resources.ResourceType.TwoDA),
                ["PaletteID"] = new Resources.ResourceIdentifier("palette", Resources.ResourceType.TwoDA),
                ["BodyBag"] = new Resources.ResourceIdentifier("bodybag", Resources.ResourceType.TwoDA),
                ["BaseItem"] = new Resources.ResourceIdentifier("baseitems", Resources.ResourceType.TwoDA),
                ["ModelVariation"] = new Resources.ResourceIdentifier("baseitems", Resources.ResourceType.TwoDA),
                ["BodyVariation"] = new Resources.ResourceIdentifier("bodyvariation", Resources.ResourceType.TwoDA),
                ["TextureVar"] = new Resources.ResourceIdentifier("textures", Resources.ResourceType.TwoDA),
                ["UpgradeType"] = new Resources.ResourceIdentifier("upcrystals", Resources.ResourceType.TwoDA),
                ["Appearance"] = new Resources.ResourceIdentifier("placeables", Resources.ResourceType.TwoDA),
                ["GenericType"] = new Resources.ResourceIdentifier("genericdoors", Resources.ResourceType.TwoDA),
                ["Cursor"] = new Resources.ResourceIdentifier("cursors", Resources.ResourceType.TwoDA),
                ["MusicDay"] = new Resources.ResourceIdentifier("ambientmusic", Resources.ResourceType.TwoDA),
                ["MusicNight"] = new Resources.ResourceIdentifier("ambientmusic", Resources.ResourceType.TwoDA),
                ["MusicBattle"] = new Resources.ResourceIdentifier("ambientmusic", Resources.ResourceType.TwoDA),
                ["MusicDelay"] = new Resources.ResourceIdentifier("ambientmusic", Resources.ResourceType.TwoDA),
                ["LoadScreenID"] = new Resources.ResourceIdentifier("loadscreens", Resources.ResourceType.TwoDA),
                ["CameraStyle"] = new Resources.ResourceIdentifier("camera", Resources.ResourceType.TwoDA),
                ["Animation"] = new Resources.ResourceIdentifier("dialoganim", Resources.ResourceType.TwoDA),
                ["Emotion"] = new Resources.ResourceIdentifier("emotion", Resources.ResourceType.TwoDA),
                ["FacialAnim"] = new Resources.ResourceIdentifier("facialanim", Resources.ResourceType.TwoDA),
                ["AlienRaceOwner"] = new Resources.ResourceIdentifier("racialtypes", Resources.ResourceType.TwoDA),
                ["AlienRaceNode"] = new Resources.ResourceIdentifier("racialtypes", Resources.ResourceType.TwoDA),
                ["CamVidEffect"] = new Resources.ResourceIdentifier("videoeffects", Resources.ResourceType.TwoDA),
                ["CameraID"] = new Resources.ResourceIdentifier("camera", Resources.ResourceType.TwoDA),
                ["Subtype"] = new Resources.ResourceIdentifier("spells", Resources.ResourceType.TwoDA),
                ["SpellId"] = new Resources.ResourceIdentifier("spells", Resources.ResourceType.TwoDA),
                ["Spell"] = new Resources.ResourceIdentifier("spells", Resources.ResourceType.TwoDA),
                ["FeatID"] = new Resources.ResourceIdentifier("feat", Resources.ResourceType.TwoDA),
                ["Feat"] = new Resources.ResourceIdentifier("feat", Resources.ResourceType.TwoDA),
                ["SkillID"] = new Resources.ResourceIdentifier("skills", Resources.ResourceType.TwoDA),
                ["MarkUp"] = new Resources.ResourceIdentifier("merchants", Resources.ResourceType.TwoDA),
                ["MarkDown"] = new Resources.ResourceIdentifier("merchants", Resources.ResourceType.TwoDA),
                ["Difficulty"] = new Resources.ResourceIdentifier("encdifficulty", Resources.ResourceType.TwoDA),
                ["DifficultyIndex"] = new Resources.ResourceIdentifier("encdifficulty", Resources.ResourceType.TwoDA),
                ["TrapType"] = new Resources.ResourceIdentifier("traps", Resources.ResourceType.TwoDA),
                ["PlanetID"] = new Resources.ResourceIdentifier("planetary", Resources.ResourceType.TwoDA),
                ["PlotIndex"] = new Resources.ResourceIdentifier("plot", Resources.ResourceType.TwoDA),
                ["VideoResRef"] = new Resources.ResourceIdentifier("videoeffects", Resources.ResourceType.TwoDA),
                ["AIStyle"] = new Resources.ResourceIdentifier("ai_styles", Resources.ResourceType.TwoDA),
                ["DamageType"] = new Resources.ResourceIdentifier("iprp_damagetype", Resources.ResourceType.TwoDA),
                ["DamageVsType"] = new Resources.ResourceIdentifier("iprp_damagevs", Resources.ResourceType.TwoDA),
                ["AttackModifier"] = new Resources.ResourceIdentifier("iprp_attackmod", Resources.ResourceType.TwoDA),
                ["ACModifierType"] = new Resources.ResourceIdentifier("iprp_acmodtype", Resources.ResourceType.TwoDA),
                ["BonusFeatID"] = new Resources.ResourceIdentifier("iprp_bonusfeat", Resources.ResourceType.TwoDA),
                ["CastSpell"] = new Resources.ResourceIdentifier("iprp_spells", Resources.ResourceType.TwoDA),
                ["LightColor"] = new Resources.ResourceIdentifier("iprp_lightcol", Resources.ResourceType.TwoDA),
                ["MonsterDamage"] = new Resources.ResourceIdentifier("iprp_monstdam", Resources.ResourceType.TwoDA),
                ["OnHit"] = new Resources.ResourceIdentifier("iprp_onhit", Resources.ResourceType.TwoDA),
                ["Param1"] = new Resources.ResourceIdentifier("iprp_paramtable", Resources.ResourceType.TwoDA),
                ["Param1Value"] = new Resources.ResourceIdentifier("iprp_paramtable", Resources.ResourceType.TwoDA),
                ["SkillBonus"] = new Resources.ResourceIdentifier("iprp_skillcost", Resources.ResourceType.TwoDA),
                ["SpecialWalk"] = new Resources.ResourceIdentifier("iprp_walk", Resources.ResourceType.TwoDA),
                ["WeightIncrease"] = new Resources.ResourceIdentifier("iprp_weightinc", Resources.ResourceType.TwoDA),
                ["Trap"] = new Resources.ResourceIdentifier("iprp_traptype", Resources.ResourceType.TwoDA),
                ["DamageReduction"] = new Resources.ResourceIdentifier("iprp_damagered", Resources.ResourceType.TwoDA),
                ["ImmunityType"] = new Resources.ResourceIdentifier("iprp_immunity", Resources.ResourceType.TwoDA),
                ["SavedGame"] = new Resources.ResourceIdentifier("saves", Resources.ResourceType.TwoDA),
                ["SaveType"] = new Resources.ResourceIdentifier("iprp_saveelement", Resources.ResourceType.TwoDA),
                ["SpellResistance"] = new Resources.ResourceIdentifier("iprp_spellres", Resources.ResourceType.TwoDA),
                ["VisualType"] = new Resources.ResourceIdentifier("visualeffects", Resources.ResourceType.TwoDA),
            };
        }
    }
}

