# -*- coding: utf-8 -*-
"""Generate UIResources.{es,de,fr,ru,pl,...}.resx from translation tables."""

from __future__ import annotations

from pathlib import Path

HEADER = """<?xml version="1.0" encoding="utf-8"?>
<root>
  <resheader name="resmimetype"><value>text/microsoft-resx</value></resheader>
  <resheader name="version"><value>2.0</value></resheader>
  <resheader name="reader"><value>System.Resources.ResXResourceReader, System.Resources.Extensions, Version=9.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51</value></resheader>
  <resheader name="writer"><value>System.Resources.ResXResourceWriter, System.Resources.Extensions, Version=9.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51</value></resheader>
"""


# English keys/values from UIResources.resx; values are replaced per language
def _en():
    return {
        "MenuTools": "Tools",
        "MenuHelp": "Help",
        "HelpWindowTitle": "Help",
        "OK": "OK",
        "MenuAbout": "About",
        "MenuLanguage": "Language",
        "LanguageEnglish": "English",
        "LanguageSpanish": "Español",
        "LanguageGerman": "Deutsch",
        "LanguageFrench": "Français",
        "LanguageRussian": "Русский",
        "LanguagePolish": "Polski",
        "ValidateIni": "Validate INI",
        "UninstallModRestoreBackup": "Uninstall Mod / Restore Backup",
        "FixPermissionsToFileFolder": "Fix permissions to file/folder...",
        "FixIOSCaseSensitivity": "Fix iOS Case Sensitivity",
        "CreateInfoRte": "Create info.rte...",
        "DeadlyStream": "DeadlyStream",
        "Discord": "Discord",
        "Website": "Website",
        "KOTORCommunityPortal": "KOTOR Community Portal",
        "PCGamingWiki": "PCGamingWiki",
        "KOTOR1": "KOTOR 1",
        "KOTOR2TSL": "KOTOR 2: TSL",
        "CheckForUpdates": "Check for Updates",
        "KPatcherHome": "KPatcher Home",
        "GitHubSource": "GitHub Source",
        "Exit": "Exit",
        "Browse": "Browse",
        "PlaceholderSelectMod": "Select the mod to install",
        "PlaceholderSelectKotor": "Select your KOTOR directory path",
        "AlphaBannerText": "⚠️ ALPHA VERSION - NOT FOR PRODUCTION USE ⚠️",
        "AlphaWarningTitle": "ALPHA VERSION WARNING",
        "AlphaWarningMessageFormat": "⚠️ WARNING: This is an ALPHA version ({0}) of KOTORPatcher\n\nThis version is for testing and demonstration purposes only.\nIt is NOT intended for production use.\n\nFeatures may be incomplete, unstable, or contain bugs.\nUse at your own risk.\n\nFor production use, please use the stable release.",
        "MainWindowTitle": "TSLPatcher",
        "WindowTitleFormat": "KOTORPatcher {0}",
        "WindowTitleAlphaSuffix": " [ALPHA - NOT FOR PRODUCTION USE]",
        "KOTORPatcherUpdate": "KOTORPatcher Update",
        "Cancel": "Cancel",
        "WelcomeToKPatcher": "Welcome to KPatcher!",
        "SelectModAndKotorToBegin": "Select a mod and your KOTOR directory to begin.",
        "StartingInstallation": "Starting installation...",
        "PatcherFinishedTitle": "Patcher finished",
        "SelectModDirectory": "Select Mod Directory",
        "SelectKotorDirectory": "Select KOTOR Directory",
        "ThisModRequiresConfirmation": "This mod requires confirmation",
        "StartPatchingButtonLabel": "&Start patching",
        "Error": "Error",
        "WarningTitle": "Warning!",
        "WarningNotAToy": "This is not a toy. Really continue?",
        "SelectDirectoryFixPermissions": "Select Directory to Fix Permissions",
        "PleaseWaitMayTakeAWhile": "Please wait, this may take awhile...",
        "SuccessfullyAcquiredPermission": "Successfully acquired permission",
        "OperationSuccessfulFormat": "The operation was successful. {0}",
        "FilesAndFoldersProcessedFormat": "{0} files and {1} folders finished processing.",
        "CouldNotAcquirePermission": "Could not acquire permission!",
        "PermissionsDeniedCheckLogsFormat": "Permissions denied! Check the logs for more details.{0}{1}",
        "SelectDirectoryFixCaseSensitivity": "Select Directory to Fix Case Sensitivity",
        "NothingToChangeCase": "Nothing to change - all files/folders already correct case.",
        "IOSCaseRenameTaskCompleted": "iOS case rename task completed.",
        "UpdateError": "Update Error",
        "UnableToFetchUpdateInfo": "Unable to fetch update information. Please try again later.",
        "UpdateAvailable": "Update Available",
        "UpdateAvailableMessageFormat": "A newer version of KPatcher ({0}) is available.{1}{1}{2}",
        "UpdateButton": "Update",
        "ManualDownloadButton": "Manual Download",
        "NoUpdatesFound": "No Updates Found",
        "NoUpdatesFoundMessageFormat": "You are already running the latest version of KPatcher ({0}).",
        "ReinstallButton": "Reinstall",
        "NoNamespaceSelected": "No namespace selected",
        "PleaseSelectNamespaceFirst": "Please select a namespace first.",
        "NoDescriptionAvailable": "No description available.",
        "CouldNotFindModAtFolderFormat": "Could not find a mod located at the given folder.{0}{1}",
        "TaskAlreadyRunning": "Task already running",
        "WaitForPreviousTask": "Wait for the previous task to finish.",
        "NoModChosen": "No mod chosen",
        "SelectModDirectoryFirst": "Select your mod directory first.",
        "NoGameFolder": "No game folder",
        "InvalidGameFolder": "Invalid game folder",
        "PreparingUpdate": "Preparing update...",
        "EstimatedTimeRemainingFormat": "Estimated time remaining: {0}",
        "Downloaded": "downloaded",
        "ByteB": "B",
        "ByteKB": "KB",
        "ByteMB": "MB",
        "ByteGB": "GB",
        "DownloadingKPatcherFormat": "Downloading KPatcher {0}...",
        "DownloadComplete": "Download complete.",
        "ExtractingUpdatePackage": "Extracting update package...",
        "ArchiveExtracted": "Archive extracted.",
        "FinalizingUpdate": "Finalizing update...",
        "RestartingToCompleteUpdate": "Restarting to complete the update...",
        "DownloadFailedFromFormat": "Download failed from {0}: {1}",
        "AllUpdateMirrorsFailed": "All update mirrors failed.",
        "RteEditorTitle": "RTE Editor",
        "OpenInfoRte": "Open info.rte",
        "SaveInfoRte": "Save info.rte",
        "RteFileFilter": "Rich Text Editor (*.rte)",
        "UnsavedChanges": "Unsaved changes",
        "UnsavedChangesDiscardPrompt": "You have unsaved changes. Do you want to discard them?",
        "FailedToLoadRtfContent": "Failed to load RTF content. Please check the console for details.",
        "Untitled": "Untitled",
        "MenuFile": "_File",
        "MenuNew": "_New",
        "MenuOpen": "_Open...",
        "MenuSave": "_Save",
        "MenuSaveAs": "Save _As...",
        "MenuClose": "_Close",
        "Bold": "Bold",
        "Italic": "Italic",
        "Underline": "Underline",
        "Strike": "Strike",
        "AlignLeft": "Align Left",
        "AlignCenter": "Align Center",
        "AlignRight": "Align Right",
        "ColorBlack": "Black",
        "ColorRed": "Red",
        "ColorGreen": "Green",
        "ColorBlue": "Blue",
        "ColorGray": "Gray",
        "ColorTransparent": "Transparent",
        "ColorYellow": "Yellow",
        "ColorLightBlue": "LightBlue",
        "ColorLightGreen": "LightGreen",
        "InstallationCompleteWithErrorsAndWarningsFormat": "The installation is complete with {0} errors and {1} warnings.{2}Total install time: {3}{2}Total patches: {4}",
        "UnexpectedErrorDuringInstallationFormat": "An unexpected error occurred during the installation and the installation was forced to terminate.{0}{0}{1}",
        "ConfigReaderTestComplete": "Config reader test is complete.",
        "UninstallProcessFinished": "Uninstall process finished.",
        "PermissionsFixerTaskCompleted": "File/Folder permissions fixer task completed.",
        "AtLeastOneOptionRequired": "At least one option is required.",
        "DefaultInstallation": "Default installation",
        "LoadedNamespacesCountFormat": "Loaded {0} namespace(s).",
        "DetectedKotorInstallationsFormat": "Detected {0} KOTOR installation(s).",
        "AutoOpeningModFromFormat": "Auto-opening mod from: {0}",
        "InstallationCancelled": "Installation was cancelled.",
        "NoBackupDirectoryFoundFormat": "No backup directory found at {0}",
        "UninstallFailedFormat": "Uninstall failed: {0}",
        "UnableToLocateWindowForUpdater": "Unable to locate window for updater UI.",
        "UnableToOpenRteEditorWindow": "Unable to open RTE editor: window not available.",
        "FailedToLoadRteContentFormat": "Failed to load RTE content: {0}",
        "FailedToLoadModFormat": "Failed to load mod: {0}",
        "FailedToLoadNamespaceConfigFormat": "Failed to load namespace config: {0}",
        "PleaseSelectModAndGameDirectory": "Please select both a mod and game directory.",
        "InstallationFailedFormat": "Installation failed: {0}",
        "ValidationFailedFormat": "Validation failed: {0}",
        "FailedToFixPermissionsFormat": "Failed to fix permissions: {0}",
        "FailedToFixCaseSensitivityFormat": "Failed to fix case sensitivity: {0}",
        "FailedToOpenUrlFormat": "Failed to open URL: {0}",
        "NoBackupsFoundTitle": "No backups found!",
        "NoBackupsFoundMessageFormat": "No backups found at '{0}'!{1}KPatcher cannot uninstall KPatcher.exe installations.",
        "BackupOutOfDateOrMismatched": "Backup out of date or mismatched",
        "BackupMismatchMessageFormat": "This backup doesn't match your current KOTOR installation. Files are missing/changed in your KOTOR install.{0}It is important that you uninstall all mods in their installed order when utilizing this feature.{0}Also ensure you selected the right mod, and the right KOTOR folder.{0}Continue anyway?",
        "Confirmation": "Confirmation",
        "ReallyUninstallConfirmFormat": "Really uninstall {0} files and restore the most recent backup (containing {1} files and {2} folders)?{3}Note: This uses the most recent mod-specific backup, the namespace option displayed does not affect this tool.",
        "FailedToRestoreBackupFormat": "Failed to restore backup because of exception.{0}{0}{1}",
        "UninstallCompletedTitle": "Uninstall completed!",
        "UninstallCompletedDeleteBackupFormat": "Deleted {0} files and successfully restored backup created on {1}{2}{2}Would you like to delete the backup created on {1} since it now has been restored?",
        "PermissionErrorTitle": "Permission Error",
        "UnableToDeleteBackupPermissionFormat": "Unable to delete the restored backup due to permission issues. Would you like to gain permission and try again?",
        "GainingPermissionPleaseWait": "Gaining permission, please wait...",
        "TimeUnitDay": "day",
        "TimeUnitDays": "days",
        "TimeUnitHour": "hour",
        "TimeUnitHours": "hours",
        "TimeUnitMinute": "minute",
        "TimeUnitMinutes": "minutes",
        "TimeUnitSecond": "second",
        "TimeUnitSeconds": "seconds",
        "DownloadEndedPrematurely": "The download ended prematurely.",
        "UnsupportedArchiveFormat": "Unsupported archive format: {0}",
        "UnableToLocateCurrentProcessPath": "Unable to locate current process path.",
        "UnableToDetermineApplicationDirectory": "Unable to determine application directory.",
        "SelectedNamespaceNotFound": "Selected namespace not found.",
        "UnsupportedOsForAutomaticUpdates": "Unsupported operating system for automatic updates.",
        "RemoteUpdatePayloadEmpty": "Remote update payload was empty.",
        "FailedToParseRemoteUpdatePayload": "Failed to parse remote update payload.",
        "InstallLocationUserSelected": "Install location: User selected.",
        "MakeBackupsBeforeModifying": "Make backups: Before modifying/overwriting existing files.",
        "LogLevelNothing": "Nothing: No feedback.",
        "LogLevelGeneral": "General: Progress only.",
        "LogLevelErrors": "Errors: Progress and errors.",
        "LogLevelWarnings": "Standard: Progress, errors and warnings.",
        "LogLevelFull": "Full: Verbose progress (debugging).",
        "NoNamespacesOrChangesFoundInFormat": "No namespaces.ini, namespaces.yaml, changes.ini, or changes.yaml (or localized variants) found in {0}",
        "NamespaceNotFoundInListFormat": "Namespace '{0}' not found in namespaces list",
        "InvalidKotorDirectoryFormat": "Invalid KOTOR directory: {0}",
        "BackupFolderNotFoundFormat": "Backup folder not found: {0}",
        "ChangesIniFileNotFoundFormat": "Changes INI file not found: {0}",
        "NoContentInGitHubApiResponse": "No content found in GitHub API response",
        "JsonDataNotFoundOrMarkersIncorrect": "JSON data not found or markers are incorrect",
        "FailedToDeserializeRemoteInfo": "Failed to deserialize remote info",
        "TarGzRequiresNet8OrGreater": "tar.gz extraction requires .NET 8 or greater",
        "NoDirectDownloadLinksForFormat": "No direct download links were provided for {0}/{1}.",
        "FlowDocumentNotInitialized": "FlowDocument is not initialized",
        "ConfigSummaryTitle": "TSLPatcher - CONFIGURATION SUMMARY",
        "ConfigSummarySettings": "Settings:",
        "ConfigFileLabel": "Config file: ",
        "InformationFileLabel": "Information file: ",
        "LogLevelLabel": "Log level: ",
        "DialogTlkAppending": "dialog tlk appending:",
        "NewEntriesLabel": "New entries: ",
        "ConfigSummaryTwoDAFileChanges": "2DA file changes:",
        "ConfigSummaryGffFileChanges": "GFF file changes:",
        "ConfigSummaryNcsIntegerHacks": "NCS file integer hacks:",
        "ConfigSummaryModifiedRecompiledScripts": "Modified & recompiled scripts:",
        "ConfigSummaryNewModifiedSoundsetFiles": "New/modified Soundset files:",
        "ConfigSummaryUnpatchedFilesToInstall": "Unpatched files to install:",
        "ConfigSummaryNone": "  (none)",
        "ConfigSummaryNewRows": " - new rows: ",
        "ConfigSummaryModifiedRows": ", modified rows: ",
        "ConfigSummaryNewColumns": ", new columns: ",
        "ConfigSummaryModifyExistingLocation": " - modify existing, location: ",
        "ConfigSummaryLocation": " * Location: ",
        "ConfigSummaryOverwrite": "overwrite",
        "ConfigSummarySkipExisting": "skip existing",
        "ConfigurationSummaryToolTip": "Configuration summary",
    }


def _es():
    t = _en().copy()
    t.update(
        {
            "MenuTools": "Herramientas",
            "MenuHelp": "Ayuda",
            "HelpWindowTitle": "Ayuda",
            "OK": "Aceptar",
            "MenuAbout": "Acerca de",
            "MenuLanguage": "Idioma",
            "ValidateIni": "Validar INI",
            "UninstallModRestoreBackup": "Desinstalar mod / Restaurar copia de seguridad",
            "FixPermissionsToFileFolder": "Corregir permisos de archivo/carpeta...",
            "FixIOSCaseSensitivity": "Corregir sensibilidad de mayúsculas iOS",
            "CreateInfoRte": "Crear info.rte...",
            "DeadlyStream": "DeadlyStream",
            "Discord": "Discord",
            "Website": "Sitio web",
            "PCGamingWiki": "PCGamingWiki",
            "KOTOR1": "KOTOR 1",
            "KOTOR2TSL": "KOTOR 2: TSL",
            "KOTORCommunityPortal": "Portal de la comunidad KOTOR",
            "CheckForUpdates": "Buscar actualizaciones",
            "KPatcherHome": "Inicio de KPatcher",
            "GitHubSource": "Código fuente en GitHub",
            "Exit": "Salir",
            "Browse": "Examinar",
            "PlaceholderSelectMod": "Seleccione el mod a instalar",
            "PlaceholderSelectKotor": "Seleccione la ruta de su directorio KOTOR",
            "AlphaBannerText": "⚠️ VERSIÓN ALFA - NO PARA USO EN PRODUCCIÓN ⚠️",
            "AlphaWarningTitle": "AVISO DE VERSIÓN ALFA",
            "AlphaWarningMessageFormat": "⚠️ AVISO: Esta es una versión ALFA ({0}) de KPatcher\n\nEsta versión es solo para pruebas y demostración.\nNO está destinada a uso en producción.\n\nLas funciones pueden estar incompletas, ser inestables o contener errores.\nÚsela bajo su propio riesgo.\n\nPara uso en producción, utilice la versión estable.",
            "WindowTitleFormat": "KOTORPatcher {0}",
            "WindowTitleAlphaSuffix": " [ALFA - NO PARA USO EN PRODUCCIÓN]",
            "KOTORPatcherUpdate": "Actualización de KOTORPatcher",
            "Cancel": "Cancelar",
            "WelcomeToKPatcher": "¡Bienvenido a KPatcher!",
            "SelectModAndKotorToBegin": "Seleccione un mod y su directorio de KOTOR para comenzar.",
            "StartingInstallation": "Iniciando instalación...",
            "PatcherFinishedTitle": "Parcheador finalizado",
            "SelectModDirectory": "Seleccionar directorio del mod",
            "SelectKotorDirectory": "Seleccionar directorio de KOTOR",
            "ThisModRequiresConfirmation": "Este mod requiere confirmación",
            "StartPatchingButtonLabel": "&Iniciar parcheo",
            "Error": "Error",
            "WarningTitle": "¡Aviso!",
            "WarningNotAToy": "Esto no es un juego. ¿Continuar de todos modos?",
            "SelectDirectoryFixPermissions": "Seleccionar directorio para corregir permisos",
            "PleaseWaitMayTakeAWhile": "Espere, puede tardar un poco...",
            "SuccessfullyAcquiredPermission": "Permiso obtenido correctamente",
            "OperationSuccessfulFormat": "La operación se completó correctamente. {0}",
            "FilesAndFoldersProcessedFormat": "{0} archivos y {1} carpetas procesados.",
            "CouldNotAcquirePermission": "¡No se pudo obtener el permiso!",
            "PermissionsDeniedCheckLogsFormat": "¡Permisos denegados! Consulte los registros para más detalles.{0}{1}",
            "SelectDirectoryFixCaseSensitivity": "Seleccionar directorio para corregir sensibilidad de mayúsculas",
            "NothingToChangeCase": "Nada que cambiar: archivos y carpetas ya tienen la capitalización correcta.",
            "IOSCaseRenameTaskCompleted": "Tarea de cambio de mayúsculas iOS completada.",
            "UpdateError": "Error de actualización",
            "UnableToFetchUpdateInfo": "No se pudo obtener la información de actualización. Inténtelo más tarde.",
            "UpdateAvailable": "Actualización disponible",
            "UpdateAvailableMessageFormat": "Hay una versión más reciente de KPatcher ({0}).{1}{1}{2}",
            "UpdateButton": "Actualizar",
            "ManualDownloadButton": "Descarga manual",
            "NoUpdatesFound": "No hay actualizaciones",
            "NoUpdatesFoundMessageFormat": "Ya tiene la última versión de KPatcher ({0}).",
            "ReinstallButton": "Reinstalar",
            "NoNamespaceSelected": "Ningún espacio de nombres seleccionado",
            "PleaseSelectNamespaceFirst": "Seleccione primero un espacio de nombres.",
            "NoDescriptionAvailable": "No hay descripción disponible.",
            "CouldNotFindModAtFolderFormat": "No se encontró un mod en la carpeta indicada.{0}{1}",
            "TaskAlreadyRunning": "Ya hay una tarea en ejecución",
            "WaitForPreviousTask": "Espere a que termine la tarea anterior.",
            "NoModChosen": "Ningún mod elegido",
            "SelectModDirectoryFirst": "Seleccione primero el directorio del mod.",
            "NoGameFolder": "Sin carpeta del juego",
            "InvalidGameFolder": "Carpeta del juego no válida",
            "PreparingUpdate": "Preparando actualización...",
            "EstimatedTimeRemainingFormat": "Tiempo restante estimado: {0}",
            "Downloaded": "descargado",
            "ByteB": "B",
            "ByteKB": "KB",
            "ByteMB": "MB",
            "ByteGB": "GB",
            "DownloadingKPatcherFormat": "Descargando KPatcher {0}...",
            "DownloadComplete": "Descarga completada.",
            "ExtractingUpdatePackage": "Extrayendo paquete de actualización...",
            "ArchiveExtracted": "Archivo extraído.",
            "FinalizingUpdate": "Finalizando actualización...",
            "RestartingToCompleteUpdate": "Reiniciando para completar la actualización...",
            "DownloadFailedFromFormat": "Error de descarga desde {0}: {1}",
            "AllUpdateMirrorsFailed": "Todos los espejos de actualización fallaron.",
            "RteEditorTitle": "Editor RTE",
            "OpenInfoRte": "Abrir info.rte",
            "SaveInfoRte": "Guardar info.rte",
            "RteFileFilter": "Editor de texto enriquecido (*.rte)",
            "UnsavedChanges": "Cambios sin guardar",
            "UnsavedChangesDiscardPrompt": "Tiene cambios sin guardar. ¿Desea descartarlos?",
            "FailedToLoadRtfContent": "No se pudo cargar el contenido RTF. Consulte la consola para más detalles.",
            "Untitled": "Sin título",
            "MenuFile": "_Archivo",
            "MenuNew": "_Nuevo",
            "MenuOpen": "_Abrir...",
            "MenuSave": "_Guardar",
            "MenuSaveAs": "Guardar _como...",
            "MenuClose": "_Cerrar",
            "Bold": "Negrita",
            "Italic": "Cursiva",
            "Underline": "Subrayado",
            "Strike": "Tachado",
            "AlignLeft": "Alinear a la izquierda",
            "AlignCenter": "Centrar",
            "AlignRight": "Alinear a la derecha",
            "ColorBlack": "Negro",
            "ColorRed": "Rojo",
            "ColorGreen": "Verde",
            "ColorBlue": "Azul",
            "ColorGray": "Gris",
            "ColorTransparent": "Transparente",
            "ColorYellow": "Amarillo",
            "ColorLightBlue": "Azul claro",
            "ColorLightGreen": "Verde claro",
            "InstallationCompleteWithErrorsAndWarningsFormat": "La instalación finalizó con {0} errores y {1} advertencias.{2}Tiempo total: {3}{2}Parches totales: {4}",
            "UnexpectedErrorDuringInstallationFormat": "Ocurrió un error inesperado durante la instalación y esta se interrumpió.{0}{0}{1}",
            "ConfigReaderTestComplete": "Prueba del lector de configuración completada.",
            "UninstallProcessFinished": "Proceso de desinstalación finalizado.",
            "PermissionsFixerTaskCompleted": "Tarea de corrección de permisos de archivos/carpetas completada.",
            "AtLeastOneOptionRequired": "Se requiere al menos una opción.",
            "DefaultInstallation": "Instalación predeterminada",
            "LoadedNamespacesCountFormat": "Se cargaron {0} espacio(s) de nombres.",
            "DetectedKotorInstallationsFormat": "Se detectaron {0} instalación(es) de KOTOR.",
            "AutoOpeningModFromFormat": "Abriendo mod automáticamente desde: {0}",
            "InstallationCancelled": "Instalación cancelada.",
            "NoBackupDirectoryFoundFormat": "No se encontró directorio de copia de seguridad en {0}",
            "UninstallFailedFormat": "Error al desinstalar: {0}",
            "UnableToLocateWindowForUpdater": "No se pudo localizar la ventana para la actualización.",
            "UnableToOpenRteEditorWindow": "No se pudo abrir el editor RTE: ventana no disponible.",
            "FailedToLoadRteContentFormat": "Error al cargar contenido RTE: {0}",
            "FailedToLoadModFormat": "Error al cargar mod: {0}",
            "FailedToLoadNamespaceConfigFormat": "Error al cargar configuración del espacio de nombres: {0}",
            "PleaseSelectModAndGameDirectory": "Seleccione un mod y el directorio del juego.",
            "InstallationFailedFormat": "Error en la instalación: {0}",
            "ValidationFailedFormat": "Error de validación: {0}",
            "FailedToFixPermissionsFormat": "Error al corregir permisos: {0}",
            "FailedToFixCaseSensitivityFormat": "Error al corregir sensibilidad de mayúsculas: {0}",
            "FailedToOpenUrlFormat": "Error al abrir URL: {0}",
            "NoBackupsFoundTitle": "¡No se encontraron copias de seguridad!",
            "NoBackupsFoundMessageFormat": "No se encontraron copias de seguridad en '{0}'!{1}KPatcher no puede desinstalar instalaciones de KPatcher.exe.",
            "BackupOutOfDateOrMismatched": "Copia de seguridad desactualizada o no coincide",
            "BackupMismatchMessageFormat": "Esta copia no coincide con su instalación actual de KOTOR. Faltan o han cambiado archivos.{0}Es importante desinstalar todos los mods en el orden de instalación al usar esta función.{0}Asegúrese de haber seleccionado el mod correcto y la carpeta KOTOR correcta.{0}¿Continuar de todos modos?",
            "Confirmation": "Confirmación",
            "ReallyUninstallConfirmFormat": "¿Desinstalar realmente {0} archivos y restaurar la copia de seguridad más reciente (con {1} archivos y {2} carpetas)?{3}Nota: Se usa la copia de seguridad más reciente del mod; la opción de espacio de nombres no afecta esta herramienta.",
            "FailedToRestoreBackupFormat": "Error al restaurar la copia de seguridad.{0}{0}{1}",
            "UninstallCompletedTitle": "¡Desinstalación completada!",
            "UninstallCompletedDeleteBackupFormat": "Se eliminaron {0} archivos y se restauró la copia de seguridad del {1}{2}{2}¿Desea eliminar la copia de seguridad del {1} ya restaurada?",
            "PermissionErrorTitle": "Error de permisos",
            "UnableToDeleteBackupPermissionFormat": "No se puede eliminar la copia restaurada por permisos. ¿Obtener permisos e intentar de nuevo?",
            "GainingPermissionPleaseWait": "Obteniendo permisos, espere...",
            "TimeUnitDay": "día",
            "TimeUnitDays": "días",
            "TimeUnitHour": "hora",
            "TimeUnitHours": "horas",
            "TimeUnitMinute": "minuto",
            "TimeUnitMinutes": "minutos",
            "TimeUnitSecond": "segundo",
            "TimeUnitSeconds": "segundos",
            "DownloadEndedPrematurely": "La descarga terminó prematuramente.",
            "UnsupportedArchiveFormat": "Formato de archivo no compatible: {0}",
            "UnableToLocateCurrentProcessPath": "No se pudo localizar la ruta del proceso actual.",
            "UnableToDetermineApplicationDirectory": "No se pudo determinar el directorio de la aplicación.",
            "SelectedNamespaceNotFound": "No se encontró el espacio de nombres seleccionado.",
            "UnsupportedOsForAutomaticUpdates": "Sistema operativo no compatible con actualizaciones automáticas.",
            "RemoteUpdatePayloadEmpty": "La carga de actualización remota estaba vacía.",
            "FailedToParseRemoteUpdatePayload": "Error al analizar la carga de actualización remota.",
            "InstallLocationUserSelected": "Ubicación de instalación: Seleccionada por el usuario.",
            "MakeBackupsBeforeModifying": "Hacer copias de seguridad: Antes de modificar/sobrescribir archivos existentes.",
            "LogLevelNothing": "Nada: Sin comentarios.",
            "LogLevelGeneral": "General: Solo progreso.",
            "LogLevelErrors": "Errores: Progreso y errores.",
            "LogLevelWarnings": "Estándar: Progreso, errores y advertencias.",
            "LogLevelFull": "Completo: Progreso detallado (depuración).",
            "NoNamespacesOrChangesFoundInFormat": "No se encontraron namespaces.ini, namespaces.yaml, changes.ini ni changes.yaml (ni variantes localizadas) en {0}",
            "NamespaceNotFoundInListFormat": "Espacio de nombres '{0}' no encontrado en la lista.",
            "InvalidKotorDirectoryFormat": "Directorio de KOTOR no válido: {0}",
            "BackupFolderNotFoundFormat": "Carpeta de copia de seguridad no encontrada: {0}",
            "ChangesIniFileNotFoundFormat": "Archivo INI de cambios no encontrado: {0}",
            "NoContentInGitHubApiResponse": "No se encontró contenido en la respuesta de la API de GitHub",
            "JsonDataNotFoundOrMarkersIncorrect": "Datos JSON no encontrados o marcadores incorrectos",
            "FailedToDeserializeRemoteInfo": "Error al deserializar la información remota",
            "TarGzRequiresNet8OrGreater": "La extracción tar.gz requiere .NET 8 o superior",
            "NoDirectDownloadLinksForFormat": "No se proporcionaron enlaces de descarga directos para {0}/{1}.",
            "FlowDocumentNotInitialized": "FlowDocument no está inicializado",
            "ConfigSummaryTitle": "TSLPatcher - RESUMEN DE CONFIGURACIÓN",
            "ConfigSummarySettings": "Ajustes:",
            "ConfigFileLabel": "Archivo de configuración: ",
            "InformationFileLabel": "Archivo de información: ",
            "LogLevelLabel": "Nivel de registro: ",
            "DialogTlkAppending": "adjuntar dialog tlk:",
            "NewEntriesLabel": "Nuevas entradas: ",
            "ConfigSummaryTwoDAFileChanges": "Cambios en archivos 2DA:",
            "ConfigSummaryGffFileChanges": "Cambios en archivos GFF:",
            "ConfigSummaryNcsIntegerHacks": "Hacks de enteros en archivos NCS:",
            "ConfigSummaryModifiedRecompiledScripts": "Scripts modificados y recompilados:",
            "ConfigSummaryNewModifiedSoundsetFiles": "Archivos de conjunto de sonidos nuevos/modificados:",
            "ConfigSummaryUnpatchedFilesToInstall": "Archivos sin parchear a instalar:",
            "ConfigSummaryNone": "  (ninguno)",
            "ConfigSummaryNewRows": " - filas nuevas: ",
            "ConfigSummaryModifiedRows": ", filas modificadas: ",
            "ConfigSummaryNewColumns": ", columnas nuevas: ",
            "ConfigSummaryModifyExistingLocation": " - modificar existente, ubicación: ",
            "ConfigSummaryLocation": " * Ubicación: ",
            "ConfigSummaryOverwrite": "sobrescribir",
            "ConfigSummarySkipExisting": "omitir existente",
            "ConfigurationSummaryToolTip": "Resumen de configuración",
        }
    )
    return t


def _de():
    t = _en().copy()
    t.update(
        {
            "MenuTools": "Extras",
            "MenuHelp": "Hilfe",
            "HelpWindowTitle": "Hilfe",
            "OK": "OK",
            "MenuAbout": "Über",
            "MenuLanguage": "Sprache",
            "ValidateIni": "INI prüfen",
            "UninstallModRestoreBackup": "Mod deinstallieren / Backup wiederherstellen",
            "FixPermissionsToFileFolder": "Berechtigungen für Datei/Ordner reparieren...",
            "FixIOSCaseSensitivity": "iOS-Groß-/Kleinschreibung reparieren",
            "CreateInfoRte": "info.rte erstellen...",
            "DeadlyStream": "DeadlyStream",
            "Discord": "Discord",
            "Website": "Webseite",
            "PCGamingWiki": "PCGamingWiki",
            "KOTOR1": "KOTOR 1",
            "KOTOR2TSL": "KOTOR 2: TSL",
            "KOTORCommunityPortal": "KOTOR-Community-Portal",
            "CheckForUpdates": "Nach Updates suchen",
            "KPatcherHome": "KPatcher-Startseite",
            "GitHubSource": "GitHub-Quellcode",
            "Exit": "Beenden",
            "Browse": "Durchsuchen",
            "PlaceholderSelectMod": "Mod zur Installation auswählen",
            "PlaceholderSelectKotor": "KOTOR-Installationsordner auswählen",
            "AlphaBannerText": "⚠️ ALPHA-VERSION – NICHT FÜR DEN PRODUKTIVEINSATZ ⚠️",
            "AlphaWarningTitle": "HINWEIS ZUR ALPHA-VERSION",
            "AlphaWarningMessageFormat": "⚠️ HINWEIS: Dies ist eine ALPHA-Version ({0}) von KPatcher\n\nDiese Version dient nur zu Test- und Demonstrationszwecken.\nSie ist NICHT für den produktiven Einsatz vorgesehen.\n\nFunktionen können unvollständig, instabil oder fehlerhaft sein.\nNutzung auf eigenes Risiko.\n\nFür den produktiven Einsatz bitte die stabile Version verwenden.",
            "WindowTitleFormat": "KOTORPatcher {0}",
            "WindowTitleAlphaSuffix": " [ALPHA – NICHT FÜR DEN PRODUKTIVEINSATZ]",
            "KOTORPatcherUpdate": "KOTORPatcher-Update",
            "Cancel": "Abbrechen",
            "WelcomeToKPatcher": "Willkommen bei KPatcher!",
            "SelectModAndKotorToBegin": "Wählen Sie einen Mod und Ihren KOTOR-Ordner, um zu beginnen.",
            "StartingInstallation": "Installation wird gestartet...",
            "PatcherFinishedTitle": "Patcher beendet",
            "SelectModDirectory": "Mod-Ordner auswählen",
            "SelectKotorDirectory": "KOTOR-Ordner auswählen",
            "ThisModRequiresConfirmation": "Dieser Mod erfordert eine Bestätigung",
            "StartPatchingButtonLabel": "&Patching starten",
            "Error": "Fehler",
            "WarningTitle": "Warnung!",
            "WarningNotAToy": "Das ist kein Spielzeug. Wirklich fortfahren?",
            "SelectDirectoryFixPermissions": "Ordner zur Berechtigungsreparatur auswählen",
            "PleaseWaitMayTakeAWhile": "Bitte warten, das kann einen Moment dauern...",
            "SuccessfullyAcquiredPermission": "Berechtigung erfolgreich erteilt",
            "OperationSuccessfulFormat": "Die Aktion war erfolgreich. {0}",
            "FilesAndFoldersProcessedFormat": "{0} Dateien und {1} Ordner verarbeitet.",
            "CouldNotAcquirePermission": "Berechtigung konnte nicht erteilt werden!",
            "PermissionsDeniedCheckLogsFormat": "Berechtigung verweigert! Weitere Details in den Protokollen.{0}{1}",
            "SelectDirectoryFixCaseSensitivity": "Ordner zur Groß-/Kleinschreibungsreparatur auswählen",
            "NothingToChangeCase": "Nichts zu ändern – alle Dateien/Ordner haben bereits die richtige Schreibweise.",
            "IOSCaseRenameTaskCompleted": "iOS-Groß-/Kleinschreibungs-Umbenennung abgeschlossen.",
            "UpdateError": "Update-Fehler",
            "UnableToFetchUpdateInfo": "Update-Informationen konnten nicht abgerufen werden. Bitte später erneut versuchen.",
            "UpdateAvailable": "Update verfügbar",
            "UpdateAvailableMessageFormat": "Eine neuere Version von KPatcher ({0}) ist verfügbar.{1}{1}{2}",
            "UpdateButton": "Aktualisieren",
            "ManualDownloadButton": "Manueller Download",
            "NoUpdatesFound": "Keine Updates gefunden",
            "NoUpdatesFoundMessageFormat": "Sie verwenden bereits die neueste Version von KPatcher ({0}).",
            "ReinstallButton": "Neu installieren",
            "NoNamespaceSelected": "Kein Namensraum ausgewählt",
            "PleaseSelectNamespaceFirst": "Bitte wählen Sie zuerst einen Namensraum.",
            "NoDescriptionAvailable": "Keine Beschreibung verfügbar.",
            "CouldNotFindModAtFolderFormat": "Im angegebenen Ordner wurde kein Mod gefunden.{0}{1}",
            "TaskAlreadyRunning": "Eine Aufgabe läuft bereits",
            "WaitForPreviousTask": "Warten Sie, bis die vorherige Aufgabe beendet ist.",
            "NoModChosen": "Kein Mod ausgewählt",
            "SelectModDirectoryFirst": "Wählen Sie zuerst Ihren Mod-Ordner.",
            "NoGameFolder": "Kein Spielordner",
            "InvalidGameFolder": "Ungültiger Spielordner",
            "PreparingUpdate": "Update wird vorbereitet...",
            "EstimatedTimeRemainingFormat": "Geschätzte verbleibende Zeit: {0}",
            "Downloaded": "heruntergeladen",
            "ByteB": "B",
            "ByteKB": "KB",
            "ByteMB": "MB",
            "ByteGB": "GB",
            "DownloadingKPatcherFormat": "KPatcher {0} wird heruntergeladen...",
            "DownloadComplete": "Download abgeschlossen.",
            "ExtractingUpdatePackage": "Update-Paket wird entpackt...",
            "ArchiveExtracted": "Archiv entpackt.",
            "FinalizingUpdate": "Update wird abgeschlossen...",
            "RestartingToCompleteUpdate": "Neustart zum Abschluss des Updates...",
            "DownloadFailedFromFormat": "Download von {0} fehlgeschlagen: {1}",
            "AllUpdateMirrorsFailed": "Alle Update-Server sind fehlgeschlagen.",
            "RteEditorTitle": "RTE-Editor",
            "OpenInfoRte": "info.rte öffnen",
            "SaveInfoRte": "info.rte speichern",
            "RteFileFilter": "Rich-Text-Editor (*.rte)",
            "UnsavedChanges": "Ungespeicherte Änderungen",
            "UnsavedChangesDiscardPrompt": "Sie haben ungespeicherte Änderungen. Möchten Sie sie verwerfen?",
            "FailedToLoadRtfContent": "RTF-Inhalt konnte nicht geladen werden. Details finden Sie in der Konsole.",
            "Untitled": "Unbenannt",
            "MenuFile": "_Datei",
            "MenuNew": "_Neu",
            "MenuOpen": "_Öffnen...",
            "MenuSave": "_Speichern",
            "MenuSaveAs": "Speichern _unter...",
            "MenuClose": "_Schließen",
            "Bold": "Fett",
            "Italic": "Kursiv",
            "Underline": "Unterstrichen",
            "Strike": "Durchgestrichen",
            "AlignLeft": "Linksbündig",
            "AlignCenter": "Zentriert",
            "AlignRight": "Rechtsbündig",
            "ColorBlack": "Schwarz",
            "ColorRed": "Rot",
            "ColorGreen": "Grün",
            "ColorBlue": "Blau",
            "ColorGray": "Grau",
            "ColorTransparent": "Transparent",
            "ColorYellow": "Gelb",
            "ColorLightBlue": "Hellblau",
            "ColorLightGreen": "Hellgrün",
            "InstallationCompleteWithErrorsAndWarningsFormat": "Die Installation wurde mit {0} Fehlern und {1} Warnungen abgeschlossen.{2}Gesamtzeit: {3}{2}Patches gesamt: {4}",
            "UnexpectedErrorDuringInstallationFormat": "Ein unerwarteter Fehler ist aufgetreten; die Installation wurde abgebrochen.{0}{0}{1}",
            "ConfigReaderTestComplete": "Konfigurationstest abgeschlossen.",
            "UninstallProcessFinished": "Deinstallationsvorgang abgeschlossen.",
            "PermissionsFixerTaskCompleted": "Berechtigungsreparatur für Dateien/Ordner abgeschlossen.",
            "AtLeastOneOptionRequired": "Mindestens eine Option ist erforderlich.",
            "DefaultInstallation": "Standardinstallation",
            "LoadedNamespacesCountFormat": "{0} Namensraum/Namensräume geladen.",
            "DetectedKotorInstallationsFormat": "{0} KOTOR-Installation(en) erkannt.",
            "AutoOpeningModFromFormat": "Mod wird automatisch geöffnet von: {0}",
            "InstallationCancelled": "Installation wurde abgebrochen.",
            "NoBackupDirectoryFoundFormat": "Kein Sicherungsordner unter {0} gefunden.",
            "UninstallFailedFormat": "Deinstallation fehlgeschlagen: {0}",
            "UnableToLocateWindowForUpdater": "Fenster für Update-UI konnte nicht gefunden werden.",
            "UnableToOpenRteEditorWindow": "RTE-Editor konnte nicht geöffnet werden: Fenster nicht verfügbar.",
            "FailedToLoadRteContentFormat": "RTF-Inhalt konnte nicht geladen werden: {0}",
            "FailedToLoadModFormat": "Mod konnte nicht geladen werden: {0}",
            "FailedToLoadNamespaceConfigFormat": "Namensraum-Konfiguration konnte nicht geladen werden: {0}",
            "PleaseSelectModAndGameDirectory": "Bitte wählen Sie einen Mod und den Spielordner.",
            "InstallationFailedFormat": "Installation fehlgeschlagen: {0}",
            "ValidationFailedFormat": "Validierung fehlgeschlagen: {0}",
            "FailedToFixPermissionsFormat": "Berechtigungsreparatur fehlgeschlagen: {0}",
            "FailedToFixCaseSensitivityFormat": "Groß-/Kleinschreibungsreparatur fehlgeschlagen: {0}",
            "FailedToOpenUrlFormat": "URL konnte nicht geöffnet werden: {0}",
            "NoBackupsFoundTitle": "Keine Backups gefunden!",
            "NoBackupsFoundMessageFormat": "Keine Backups unter '{0}' gefunden!{1}KPatcher kann KPatcher.exe-Installationen nicht deinstallieren.",
            "BackupOutOfDateOrMismatched": "Backup veraltet oder stimmt nicht überein",
            "BackupMismatchMessageFormat": "Dieses Backup passt nicht zu Ihrer KOTOR-Installation. Dateien fehlen oder wurden geändert.{0}Deinstallieren Sie alle Mods in der Installationsreihenfolge.{0}Stellen Sie sicher, dass Sie den richtigen Mod und den richtigen KOTOR-Ordner gewählt haben.{0}Trotzdem fortfahren?",
            "Confirmation": "Bestätigung",
            "ReallyUninstallConfirmFormat": "Wirklich {0} Dateien deinstallieren und das neueste Backup ({1} Dateien, {2} Ordner) wiederherstellen?{3}Hinweis: Es wird das neueste mod-spezifische Backup verwendet.",
            "FailedToRestoreBackupFormat": "Backup konnte wegen einer Ausnahme nicht wiederhergestellt werden.{0}{0}{1}",
            "UninstallCompletedTitle": "Deinstallation abgeschlossen!",
            "UninstallCompletedDeleteBackupFormat": "{0} Dateien gelöscht und Backup vom {1} wiederhergestellt.{2}{2}Backup vom {1} jetzt löschen?",
            "PermissionErrorTitle": "Berechtigungsfehler",
            "UnableToDeleteBackupPermissionFormat": "Das wiederhergestellte Backup konnte wegen Berechtigungen nicht gelöscht werden. Berechtigung anfordern und erneut versuchen?",
            "GainingPermissionPleaseWait": "Berechtigung wird angefordert, bitte warten...",
            "TimeUnitDay": "Tag",
            "TimeUnitDays": "Tage",
            "TimeUnitHour": "Stunde",
            "TimeUnitHours": "Stunden",
            "TimeUnitMinute": "Minute",
            "TimeUnitMinutes": "Minuten",
            "TimeUnitSecond": "Sekunde",
            "TimeUnitSeconds": "Sekunden",
            "DownloadEndedPrematurely": "Der Download wurde vorzeitig beendet.",
            "UnsupportedArchiveFormat": "Nicht unterstütztes Archivformat: {0}",
            "UnableToLocateCurrentProcessPath": "Aktueller Prozesspfad konnte nicht ermittelt werden.",
            "UnableToDetermineApplicationDirectory": "Anwendungsverzeichnis konnte nicht ermittelt werden.",
            "SelectedNamespaceNotFound": "Gewählter Namensraum wurde nicht gefunden.",
            "UnsupportedOsForAutomaticUpdates": "Betriebssystem wird für automatische Updates nicht unterstützt.",
            "RemoteUpdatePayloadEmpty": "Remote-Update-Payload war leer.",
            "FailedToParseRemoteUpdatePayload": "Remote-Update-Payload konnte nicht geparst werden.",
            "InstallLocationUserSelected": "Installationsort: Vom Benutzer gewählt.",
            "MakeBackupsBeforeModifying": "Sicherungen: Vor dem Ändern/Überschreiben vorhandener Dateien.",
            "LogLevelNothing": "Nichts: Keine Rückmeldung.",
            "LogLevelGeneral": "Allgemein: Nur Fortschritt.",
            "LogLevelErrors": "Fehler: Fortschritt und Fehler.",
            "LogLevelWarnings": "Standard: Fortschritt, Fehler und Warnungen.",
            "LogLevelFull": "Voll: Ausführlicher Fortschritt (Debug).",
            "NoNamespacesOrChangesFoundInFormat": "Keine namespaces.ini, namespaces.yaml, changes.ini oder changes.yaml (oder lokalisierte Varianten) in {0} gefunden.",
            "NamespaceNotFoundInListFormat": "Namensraum '{0}' nicht in der Namensraumliste gefunden.",
            "InvalidKotorDirectoryFormat": "Ungültiges KOTOR-Verzeichnis: {0}",
            "BackupFolderNotFoundFormat": "Sicherungsordner nicht gefunden: {0}",
            "ChangesIniFileNotFoundFormat": "Changes-INI-Datei nicht gefunden: {0}",
            "NoContentInGitHubApiResponse": "Kein Inhalt in der GitHub-API-Antwort gefunden",
            "JsonDataNotFoundOrMarkersIncorrect": "JSON-Daten nicht gefunden oder Markierungen fehlerhaft",
            "FailedToDeserializeRemoteInfo": "Deserialisierung der Remote-Informationen fehlgeschlagen",
            "TarGzRequiresNet8OrGreater": "tar.gz-Extraktion erfordert .NET 8 oder höher",
            "NoDirectDownloadLinksForFormat": "Keine direkten Download-Links für {0}/{1} angegeben.",
            "FlowDocumentNotInitialized": "FlowDocument ist nicht initialisiert",
            "ConfigSummaryTitle": "TSLPatcher - KONFIGURATIONSÜBERSICHT",
            "ConfigSummarySettings": "Einstellungen:",
            "ConfigFileLabel": "Konfigurationsdatei: ",
            "InformationFileLabel": "Informationsdatei: ",
            "LogLevelLabel": "Protokollstufe: ",
            "DialogTlkAppending": "Dialog-TLK-Anhänge:",
            "NewEntriesLabel": "Neue Einträge: ",
            "ConfigSummaryTwoDAFileChanges": "2DA-Dateiänderungen:",
            "ConfigSummaryGffFileChanges": "GFF-Dateiänderungen:",
            "ConfigSummaryNcsIntegerHacks": "NCS-Ganzzahl-Hacks:",
            "ConfigSummaryModifiedRecompiledScripts": "Geänderte & neu kompilierte Skripte:",
            "ConfigSummaryNewModifiedSoundsetFiles": "Neue/geänderte Soundset-Dateien:",
            "ConfigSummaryUnpatchedFilesToInstall": "Ungepatchte zu installierende Dateien:",
            "ConfigSummaryNone": "  (keine)",
            "ConfigSummaryNewRows": " - neue Zeilen: ",
            "ConfigSummaryModifiedRows": ", geänderte Zeilen: ",
            "ConfigSummaryNewColumns": ", neue Spalten: ",
            "ConfigSummaryModifyExistingLocation": " - Vorhandenes ändern, Speicherort: ",
            "ConfigSummaryLocation": " * Speicherort: ",
            "ConfigSummaryOverwrite": "überschreiben",
            "ConfigSummarySkipExisting": "Vorhandene überspringen",
            "ConfigurationSummaryToolTip": "Konfigurationsübersicht",
        }
    )
    return t


def _fr():
    t = _en().copy()
    t.update(
        {
            "MenuTools": "Outils",
            "MenuHelp": "Aide",
            "HelpWindowTitle": "Aide",
            "OK": "OK",
            "MenuAbout": "À propos",
            "MenuLanguage": "Langue",
            "ValidateIni": "Valider INI",
            "UninstallModRestoreBackup": "Désinstaller le mod / Restaurer la sauvegarde",
            "FixPermissionsToFileFolder": "Corriger les permissions fichier/dossier...",
            "FixIOSCaseSensitivity": "Corriger la casse iOS",
            "CreateInfoRte": "Créer info.rte...",
            "DeadlyStream": "DeadlyStream",
            "Discord": "Discord",
            "Website": "Site web",
            "PCGamingWiki": "PCGamingWiki",
            "KOTOR1": "KOTOR 1",
            "KOTOR2TSL": "KOTOR 2: TSL",
            "KOTORCommunityPortal": "Portail communautaire KOTOR",
            "CheckForUpdates": "Rechercher les mises à jour",
            "KPatcherHome": "Accueil KPatcher",
            "GitHubSource": "Code source GitHub",
            "Exit": "Quitter",
            "Browse": "Parcourir",
            "PlaceholderSelectMod": "Sélectionnez le mod à installer",
            "PlaceholderSelectKotor": "Sélectionnez le dossier d'installation de KOTOR",
            "AlphaBannerText": "⚠️ VERSION ALPHA - NE PAS UTILISER EN PRODUCTION ⚠️",
            "AlphaWarningTitle": "AVERTISSEMENT VERSION ALPHA",
            "AlphaWarningMessageFormat": "⚠️ ATTENTION : Ceci est une version ALPHA ({0}) de KPatcher\n\nCette version est destinée aux tests et démonstrations uniquement.\nElle ne doit PAS être utilisée en production.\n\nLes fonctionnalités peuvent être incomplètes, instables ou contenir des bugs.\nUtilisez à vos risques et périls.\n\nPour un usage en production, utilisez la version stable.",
            "WindowTitleFormat": "KOTORPatcher {0}",
            "WindowTitleAlphaSuffix": " [ALPHA - NE PAS UTILISER EN PRODUCTION]",
            "KOTORPatcherUpdate": "Mise à jour KOTORPatcher",
            "Cancel": "Annuler",
            "WelcomeToKPatcher": "Bienvenue dans KPatcher !",
            "SelectModAndKotorToBegin": "Sélectionnez un mod et votre dossier KOTOR pour commencer.",
            "StartingInstallation": "Démarrage de l'installation...",
            "PatcherFinishedTitle": "Patcheur terminé",
            "SelectModDirectory": "Sélectionner le dossier du mod",
            "SelectKotorDirectory": "Sélectionner le dossier KOTOR",
            "ThisModRequiresConfirmation": "Ce mod nécessite une confirmation",
            "StartPatchingButtonLabel": "&Démarrer le patch",
            "Error": "Erreur",
            "WarningTitle": "Attention !",
            "WarningNotAToy": "Ce n'est pas un jouet. Continuer quand même ?",
            "SelectDirectoryFixPermissions": "Sélectionner le dossier pour corriger les permissions",
            "PleaseWaitMayTakeAWhile": "Veuillez patienter, cela peut prendre un moment...",
            "SuccessfullyAcquiredPermission": "Permission obtenue avec succès",
            "OperationSuccessfulFormat": "L'opération a réussi. {0}",
            "FilesAndFoldersProcessedFormat": "{0} fichiers et {1} dossiers traités.",
            "CouldNotAcquirePermission": "Impossible d'obtenir la permission !",
            "PermissionsDeniedCheckLogsFormat": "Permission refusée ! Consultez les journaux pour plus de détails.{0}{1}",
            "SelectDirectoryFixCaseSensitivity": "Sélectionner le dossier pour corriger la casse",
            "NothingToChangeCase": "Rien à modifier – tous les fichiers/dossiers ont déjà la bonne casse.",
            "IOSCaseRenameTaskCompleted": "Renommage de casse iOS terminé.",
            "UpdateError": "Erreur de mise à jour",
            "UnableToFetchUpdateInfo": "Impossible de récupérer les informations de mise à jour. Réessayez plus tard.",
            "UpdateAvailable": "Mise à jour disponible",
            "UpdateAvailableMessageFormat": "Une version plus récente de KPatcher ({0}) est disponible.{1}{1}{2}",
            "UpdateButton": "Mettre à jour",
            "ManualDownloadButton": "Téléchargement manuel",
            "NoUpdatesFound": "Aucune mise à jour",
            "NoUpdatesFoundMessageFormat": "Vous utilisez déjà la dernière version de KPatcher ({0}).",
            "ReinstallButton": "Réinstaller",
            "NoNamespaceSelected": "Aucun espace de noms sélectionné",
            "PleaseSelectNamespaceFirst": "Veuillez d'abord sélectionner un espace de noms.",
            "NoDescriptionAvailable": "Aucune description disponible.",
            "CouldNotFindModAtFolderFormat": "Aucun mod trouvé dans le dossier indiqué.{0}{1}",
            "TaskAlreadyRunning": "Une tâche est déjà en cours",
            "WaitForPreviousTask": "Attendez la fin de la tâche précédente.",
            "NoModChosen": "Aucun mod choisi",
            "SelectModDirectoryFirst": "Sélectionnez d'abord le dossier du mod.",
            "NoGameFolder": "Aucun dossier de jeu",
            "InvalidGameFolder": "Dossier de jeu invalide",
            "PreparingUpdate": "Préparation de la mise à jour...",
            "EstimatedTimeRemainingFormat": "Temps restant estimé : {0}",
            "Downloaded": "téléchargé",
            "ByteB": "B",
            "ByteKB": "Ko",
            "ByteMB": "Mo",
            "ByteGB": "Go",
            "DownloadingKPatcherFormat": "Téléchargement de KPatcher {0}...",
            "DownloadComplete": "Téléchargement terminé.",
            "ExtractingUpdatePackage": "Extraction du paquet de mise à jour...",
            "ArchiveExtracted": "Archive extraite.",
            "FinalizingUpdate": "Finalisation de la mise à jour...",
            "RestartingToCompleteUpdate": "Redémarrage pour terminer la mise à jour...",
            "DownloadFailedFromFormat": "Échec du téléchargement depuis {0} : {1}",
            "AllUpdateMirrorsFailed": "Tous les miroirs de mise à jour ont échoué.",
            "RteEditorTitle": "Éditeur RTE",
            "OpenInfoRte": "Ouvrir info.rte",
            "SaveInfoRte": "Enregistrer info.rte",
            "RteFileFilter": "Éditeur de texte enrichi (*.rte)",
            "UnsavedChanges": "Modifications non enregistrées",
            "UnsavedChangesDiscardPrompt": "Vous avez des modifications non enregistrées. Voulez-vous les abandonner ?",
            "FailedToLoadRtfContent": "Impossible de charger le contenu RTF. Consultez la console pour plus de détails.",
            "Untitled": "Sans titre",
            "MenuFile": "_Fichier",
            "MenuNew": "_Nouveau",
            "MenuOpen": "_Ouvrir...",
            "MenuSave": "_Enregistrer",
            "MenuSaveAs": "Enregistrer _sous...",
            "MenuClose": "_Fermer",
            "Bold": "Gras",
            "Italic": "Italique",
            "Underline": "Souligné",
            "Strike": "Barré",
            "AlignLeft": "Aligner à gauche",
            "AlignCenter": "Centrer",
            "AlignRight": "Aligner à droite",
            "ColorBlack": "Noir",
            "ColorRed": "Rouge",
            "ColorGreen": "Vert",
            "ColorBlue": "Bleu",
            "ColorGray": "Gris",
            "ColorTransparent": "Transparent",
            "ColorYellow": "Jaune",
            "ColorLightBlue": "Bleu clair",
            "ColorLightGreen": "Vert clair",
            "InstallationCompleteWithErrorsAndWarningsFormat": "L'installation s'est terminée avec {0} erreurs et {1} avertissements.{2}Durée totale : {3}{2}Patches au total : {4}",
            "UnexpectedErrorDuringInstallationFormat": "Une erreur inattendue s'est produite et l'installation a été interrompue.{0}{0}{1}",
            "ConfigReaderTestComplete": "Test du lecteur de configuration terminé.",
            "UninstallProcessFinished": "Désinstallation terminée.",
            "PermissionsFixerTaskCompleted": "Réparation des permissions fichier/dossier terminée.",
            "AtLeastOneOptionRequired": "Au moins une option est requise.",
            "DefaultInstallation": "Installation par défaut",
            "LoadedNamespacesCountFormat": "{0} espace(s) de noms chargé(s).",
            "DetectedKotorInstallationsFormat": "{0} installation(s) KOTOR détectée(s).",
            "AutoOpeningModFromFormat": "Ouverture automatique du mod depuis : {0}",
            "InstallationCancelled": "Installation annulée.",
            "NoBackupDirectoryFoundFormat": "Aucun dossier de sauvegarde trouvé dans {0}.",
            "UninstallFailedFormat": "Désinstallation échouée : {0}",
            "UnableToLocateWindowForUpdater": "Impossible de localiser la fenêtre pour la mise à jour.",
            "UnableToOpenRteEditorWindow": "Impossible d'ouvrir l'éditeur RTE : fenêtre non disponible.",
            "FailedToLoadRteContentFormat": "Échec du chargement du contenu RTF : {0}",
            "FailedToLoadModFormat": "Échec du chargement du mod : {0}",
            "FailedToLoadNamespaceConfigFormat": "Échec du chargement de la configuration de l'espace de noms : {0}",
            "PleaseSelectModAndGameDirectory": "Veuillez sélectionner un mod et le dossier du jeu.",
            "InstallationFailedFormat": "Échec de l'installation : {0}",
            "ValidationFailedFormat": "Échec de la validation : {0}",
            "FailedToFixPermissionsFormat": "Échec de la correction des permissions : {0}",
            "FailedToFixCaseSensitivityFormat": "Échec de la correction de la casse : {0}",
            "FailedToOpenUrlFormat": "Échec de l'ouverture de l'URL : {0}",
            "NoBackupsFoundTitle": "Aucune sauvegarde trouvée !",
            "NoBackupsFoundMessageFormat": "Aucune sauvegarde trouvée dans '{0}' !{1}KPatcher ne peut pas désinstaller les installations KPatcher.exe.",
            "BackupOutOfDateOrMismatched": "Sauvegarde obsolète ou non correspondante",
            "BackupMismatchMessageFormat": "Cette sauvegarde ne correspond pas à votre installation KOTOR. Fichiers manquants ou modifiés.{0}Désinstallez tous les mods dans l'ordre d'installation.{0}Vérifiez que vous avez sélectionné le bon mod et le bon dossier KOTOR.{0}Continuer quand même ?",
            "Confirmation": "Confirmation",
            "ReallyUninstallConfirmFormat": "Vraiment désinstaller {0} fichiers et restaurer la sauvegarde la plus récente ({1} fichiers, {2} dossiers) ?{3}Ceci utilise la sauvegarde la plus récente du mod.",
            "FailedToRestoreBackupFormat": "Échec de la restauration de la sauvegarde (exception).{0}{0}{1}",
            "UninstallCompletedTitle": "Désinstallation terminée !",
            "UninstallCompletedDeleteBackupFormat": "{0} fichiers supprimés, sauvegarde du {1} restaurée.{2}{2}Supprimer la sauvegarde du {1} ?",
            "PermissionErrorTitle": "Erreur de permission",
            "UnableToDeleteBackupPermissionFormat": "Impossible de supprimer la sauvegarde restaurée (permissions). Voulez-vous demander les permissions et réessayer ?",
            "GainingPermissionPleaseWait": "Obtention des permissions, veuillez patienter...",
            "TimeUnitDay": "jour",
            "TimeUnitDays": "jours",
            "TimeUnitHour": "heure",
            "TimeUnitHours": "heures",
            "TimeUnitMinute": "minute",
            "TimeUnitMinutes": "minutes",
            "TimeUnitSecond": "seconde",
            "TimeUnitSeconds": "secondes",
            "DownloadEndedPrematurely": "Le téléchargement s'est terminé prématurément.",
            "UnsupportedArchiveFormat": "Format d'archive non pris en charge : {0}",
            "UnableToLocateCurrentProcessPath": "Impossible de localiser le chemin du processus actuel.",
            "UnableToDetermineApplicationDirectory": "Impossible de déterminer le répertoire de l'application.",
            "SelectedNamespaceNotFound": "Espace de noms sélectionné introuvable.",
            "UnsupportedOsForAutomaticUpdates": "Système d'exploitation non pris en charge pour les mises à jour automatiques.",
            "RemoteUpdatePayloadEmpty": "La charge utile de mise à jour distante était vide.",
            "FailedToParseRemoteUpdatePayload": "Échec de l'analyse de la charge utile de mise à jour distante.",
            "InstallLocationUserSelected": "Emplacement d'installation : sélectionné par l'utilisateur.",
            "MakeBackupsBeforeModifying": "Sauvegardes : avant modification/écrasement des fichiers existants.",
            "LogLevelNothing": "Rien : aucune remarque.",
            "LogLevelGeneral": "Général : progression uniquement.",
            "LogLevelErrors": "Erreurs : progression et erreurs.",
            "LogLevelWarnings": "Standard : progression, erreurs et avertissements.",
            "LogLevelFull": "Complet : progression détaillée (débogage).",
            "NoNamespacesOrChangesFoundInFormat": "Aucun namespaces.ini, namespaces.yaml, changes.ini ou changes.yaml (ou variantes localisées) trouvé dans {0}",
            "NamespaceNotFoundInListFormat": "Espace de noms '{0}' introuvable dans la liste.",
            "InvalidKotorDirectoryFormat": "Répertoire KOTOR invalide : {0}",
            "BackupFolderNotFoundFormat": "Dossier de sauvegarde introuvable : {0}",
            "ChangesIniFileNotFoundFormat": "Fichier INI des changements introuvable : {0}",
            "NoContentInGitHubApiResponse": "Aucun contenu trouvé dans la réponse de l'API GitHub",
            "JsonDataNotFoundOrMarkersIncorrect": "Données JSON introuvables ou marqueurs incorrects",
            "FailedToDeserializeRemoteInfo": "Échec de la désérialisation des informations distantes",
            "TarGzRequiresNet8OrGreater": "L'extraction tar.gz nécessite .NET 8 ou supérieur",
            "NoDirectDownloadLinksForFormat": "Aucun lien de téléchargement direct fourni pour {0}/{1}.",
            "FlowDocumentNotInitialized": "FlowDocument n'est pas initialisé",
            "ConfigSummaryTitle": "TSLPatcher - RÉSUMÉ DE CONFIGURATION",
            "ConfigSummarySettings": "Paramètres :",
            "ConfigFileLabel": "Fichier de configuration : ",
            "InformationFileLabel": "Fichier d'information : ",
            "LogLevelLabel": "Niveau de journal : ",
            "DialogTlkAppending": "ajout dialog tlk :",
            "NewEntriesLabel": "Nouvelles entrées : ",
            "ConfigSummaryTwoDAFileChanges": "Modifications de fichiers 2DA :",
            "ConfigSummaryGffFileChanges": "Modifications de fichiers GFF :",
            "ConfigSummaryNcsIntegerHacks": "Hacks d'entiers NCS :",
            "ConfigSummaryModifiedRecompiledScripts": "Scripts modifiés et recompilés :",
            "ConfigSummaryNewModifiedSoundsetFiles": "Fichiers de jeu de sons nouveaux/modifiés :",
            "ConfigSummaryUnpatchedFilesToInstall": "Fichiers non patchés à installer :",
            "ConfigSummaryNone": "  (aucun)",
            "ConfigSummaryNewRows": " - nouvelles lignes : ",
            "ConfigSummaryModifiedRows": ", lignes modifiées : ",
            "ConfigSummaryNewColumns": ", nouvelles colonnes : ",
            "ConfigSummaryModifyExistingLocation": " - modifier l'existant, emplacement : ",
            "ConfigSummaryLocation": " * Emplacement : ",
            "ConfigSummaryOverwrite": "écraser",
            "ConfigSummarySkipExisting": "ignorer l'existant",
            "ConfigurationSummaryToolTip": "Résumé de configuration",
        }
    )
    return t


def _ru():
    t = _en().copy()
    t.update(
        {
            "MenuTools": "Инструменты",
            "MenuHelp": "Справка",
            "HelpWindowTitle": "Справка",
            "OK": "OK",
            "MenuAbout": "О программе",
            "MenuLanguage": "Язык",
            "ValidateIni": "Проверить INI",
            "UninstallModRestoreBackup": "Удалить мод / Восстановить резервную копию",
            "FixPermissionsToFileFolder": "Исправить права доступа к файлу/папке...",
            "FixIOSCaseSensitivity": "Исправить регистр для iOS",
            "CreateInfoRte": "Создать info.rte...",
            "DeadlyStream": "DeadlyStream",
            "Discord": "Discord",
            "Website": "Веб-сайт",
            "PCGamingWiki": "PCGamingWiki",
            "KOTOR1": "KOTOR 1",
            "KOTOR2TSL": "KOTOR 2: TSL",
            "KOTORCommunityPortal": "Портал сообщества KOTOR",
            "CheckForUpdates": "Проверить обновления",
            "KPatcherHome": "Домашняя страница KPatcher",
            "GitHubSource": "Исходный код на GitHub",
            "Exit": "Выход",
            "Browse": "Обзор",
            "PlaceholderSelectMod": "Выберите мод для установки",
            "PlaceholderSelectKotor": "Выберите папку с KOTOR",
            "AlphaBannerText": "⚠️ АЛЬФА-ВЕРСИЯ — НЕ ДЛЯ ПРОДАКШЕНА ⚠️",
            "AlphaWarningTitle": "ПРЕДУПРЕЖДЕНИЕ ОБ АЛЬФА-ВЕРСИИ",
            "AlphaWarningMessageFormat": "⚠️ ВНИМАНИЕ: Это альфа-версия ({0}) KPatcher\n\nЭта версия только для тестирования и демонстрации.\nНЕ для использования в продакшене.\n\nФункции могут быть неполными, нестабильными или содержать ошибки.\nИспользуйте на свой страх и риск.\n\nДля продакшена используйте стабильный выпуск.",
            "WindowTitleFormat": "KOTORPatcher {0}",
            "WindowTitleAlphaSuffix": " [АЛЬФА — НЕ ДЛЯ ПРОДАКШЕНА]",
            "KOTORPatcherUpdate": "Обновление KOTORPatcher",
            "Cancel": "Отмена",
            "WelcomeToKPatcher": "Добро пожаловать в KPatcher!",
            "SelectModAndKotorToBegin": "Выберите мод и папку KOTOR для начала.",
            "StartingInstallation": "Запуск установки...",
            "PatcherFinishedTitle": "Патчер завершён",
            "SelectModDirectory": "Выберите папку мода",
            "SelectKotorDirectory": "Выберите папку KOTOR",
            "ThisModRequiresConfirmation": "Для этого мода требуется подтверждение",
            "StartPatchingButtonLabel": "&Начать патчинг",
            "Error": "Ошибка",
            "WarningTitle": "Предупреждение!",
            "WarningNotAToy": "Это не игрушка. Всё равно продолжить?",
            "SelectDirectoryFixPermissions": "Выберите папку для исправления прав доступа",
            "PleaseWaitMayTakeAWhile": "Подождите, это может занять некоторое время...",
            "SuccessfullyAcquiredPermission": "Права доступа успешно получены",
            "OperationSuccessfulFormat": "Операция выполнена успешно. {0}",
            "FilesAndFoldersProcessedFormat": "Обработано файлов: {0}, папок: {1}.",
            "CouldNotAcquirePermission": "Не удалось получить права доступа!",
            "PermissionsDeniedCheckLogsFormat": "Доступ запрещён! Подробности в журнале.{0}{1}",
            "SelectDirectoryFixCaseSensitivity": "Выберите папку для исправления регистра",
            "NothingToChangeCase": "Менять нечего — у всех файлов и папок уже правильный регистр.",
            "IOSCaseRenameTaskCompleted": "Переименование регистра для iOS завершено.",
            "UpdateError": "Ошибка обновления",
            "UnableToFetchUpdateInfo": "Не удалось получить данные об обновлении. Попробуйте позже.",
            "UpdateAvailable": "Доступно обновление",
            "UpdateAvailableMessageFormat": "Доступна более новая версия KPatcher ({0}).{1}{1}{2}",
            "UpdateButton": "Обновить",
            "ManualDownloadButton": "Скачать вручную",
            "NoUpdatesFound": "Обновления не найдены",
            "NoUpdatesFoundMessageFormat": "У вас уже установлена последняя версия KPatcher ({0}).",
            "ReinstallButton": "Переустановить",
            "NoNamespaceSelected": "Пространство имён не выбрано",
            "PleaseSelectNamespaceFirst": "Сначала выберите пространство имён.",
            "NoDescriptionAvailable": "Описание недоступно.",
            "CouldNotFindModAtFolderFormat": "В указанной папке мод не найден.{0}{1}",
            "TaskAlreadyRunning": "Задача уже выполняется",
            "WaitForPreviousTask": "Дождитесь завершения предыдущей задачи.",
            "NoModChosen": "Мод не выбран",
            "SelectModDirectoryFirst": "Сначала выберите папку мода.",
            "NoGameFolder": "Папка игры не указана",
            "InvalidGameFolder": "Недопустимая папка игры",
            "PreparingUpdate": "Подготовка обновления...",
            "EstimatedTimeRemainingFormat": "Оставшееся время: {0}",
            "Downloaded": "загружено",
            "ByteB": "Б",
            "ByteKB": "КБ",
            "ByteMB": "МБ",
            "ByteGB": "ГБ",
            "DownloadingKPatcherFormat": "Загрузка KPatcher {0}...",
            "DownloadComplete": "Загрузка завершена.",
            "ExtractingUpdatePackage": "Распаковка пакета обновления...",
            "ArchiveExtracted": "Архив распакован.",
            "FinalizingUpdate": "Завершение обновления...",
            "RestartingToCompleteUpdate": "Перезапуск для завершения обновления...",
            "DownloadFailedFromFormat": "Ошибка загрузки с {0}: {1}",
            "AllUpdateMirrorsFailed": "Все зеркала обновления недоступны.",
            "RteEditorTitle": "Редактор RTE",
            "OpenInfoRte": "Открыть info.rte",
            "SaveInfoRte": "Сохранить info.rte",
            "RteFileFilter": "Редактор RTF (*.rte)",
            "UnsavedChanges": "Несохранённые изменения",
            "UnsavedChangesDiscardPrompt": "У вас есть несохранённые изменения. Отменить их?",
            "FailedToLoadRtfContent": "Не удалось загрузить содержимое RTF. Подробности см. в консоли.",
            "Untitled": "Без названия",
            "MenuFile": "_Файл",
            "MenuNew": "_Создать",
            "MenuOpen": "_Открыть...",
            "MenuSave": "_Сохранить",
            "MenuSaveAs": "Сохранить _как...",
            "MenuClose": "_Закрыть",
            "Bold": "Жирный",
            "Italic": "Курсив",
            "Underline": "Подчёркнутый",
            "Strike": "Зачёркнутый",
            "AlignLeft": "По левому краю",
            "AlignCenter": "По центру",
            "AlignRight": "По правому краю",
            "ColorBlack": "Чёрный",
            "ColorRed": "Красный",
            "ColorGreen": "Зелёный",
            "ColorBlue": "Синий",
            "ColorGray": "Серый",
            "ColorTransparent": "Прозрачный",
            "ColorYellow": "Жёлтый",
            "ColorLightBlue": "Голубой",
            "ColorLightGreen": "Светло-зелёный",
            "InstallationCompleteWithErrorsAndWarningsFormat": "Установка завершена с {0} ошибками и {1} предупреждениями.{2}Общее время: {3}{2}Всего патчей: {4}",
            "UnexpectedErrorDuringInstallationFormat": "Во время установки произошла ошибка, установка прервана.{0}{0}{1}",
            "ConfigReaderTestComplete": "Проверка конфигурации завершена.",
            "UninstallProcessFinished": "Удаление завершено.",
            "PermissionsFixerTaskCompleted": "Исправление прав доступа к файлам и папкам завершено.",
            "AtLeastOneOptionRequired": "Требуется хотя бы одна опция.",
            "DefaultInstallation": "Установка по умолчанию",
            "LoadedNamespacesCountFormat": "Загружено пространств имён: {0}.",
            "DetectedKotorInstallationsFormat": "Обнаружено установок KOTOR: {0}.",
            "AutoOpeningModFromFormat": "Автооткрытие мода из: {0}",
            "InstallationCancelled": "Установка отменена.",
            "NoBackupDirectoryFoundFormat": "Папка резервной копии не найдена: {0}",
            "UninstallFailedFormat": "Ошибка удаления: {0}",
            "UnableToLocateWindowForUpdater": "Не удалось найти окно для обновления.",
            "UnableToOpenRteEditorWindow": "Не удалось открыть редактор RTE: окно недоступно.",
            "FailedToLoadRteContentFormat": "Не удалось загрузить содержимое RTF: {0}",
            "FailedToLoadModFormat": "Не удалось загрузить мод: {0}",
            "FailedToLoadNamespaceConfigFormat": "Не удалось загрузить конфигурацию пространства имён: {0}",
            "PleaseSelectModAndGameDirectory": "Выберите мод и папку игры.",
            "InstallationFailedFormat": "Ошибка установки: {0}",
            "ValidationFailedFormat": "Ошибка проверки: {0}",
            "FailedToFixPermissionsFormat": "Не удалось исправить права доступа: {0}",
            "FailedToFixCaseSensitivityFormat": "Не удалось исправить регистр: {0}",
            "FailedToOpenUrlFormat": "Не удалось открыть URL: {0}",
            "NoBackupsFoundTitle": "Резервные копии не найдены!",
            "NoBackupsFoundMessageFormat": "Резервные копии в '{0}' не найдены!{1}KPatcher не может удалять установки KPatcher.exe.",
            "BackupOutOfDateOrMismatched": "Резервная копия устарела или не совпадает",
            "BackupMismatchMessageFormat": "Эта копия не совпадает с вашей установкой KOTOR. Файлы отсутствуют или изменены.{0}Удаляйте все моды в порядке их установки.{0}Убедитесь, что выбран правильный мод и папка KOTOR.{0}Всё равно продолжить?",
            "Confirmation": "Подтверждение",
            "ReallyUninstallConfirmFormat": "Действительно удалить {0} файлов и восстановить последнюю резервную копию ({1} файлов, {2} папок)?{3}Используется последняя резервная копия этого мода.",
            "FailedToRestoreBackupFormat": "Не удалось восстановить резервную копию (исключение).{0}{0}{1}",
            "UninstallCompletedTitle": "Удаление завершено!",
            "UninstallCompletedDeleteBackupFormat": "Удалено файлов: {0}, восстановлена резервная копия от {1}{2}{2}Удалить резервную копию от {1}?",
            "PermissionErrorTitle": "Ошибка доступа",
            "UnableToDeleteBackupPermissionFormat": "Не удалось удалить восстановленную копию (права доступа). Запросить права и повторить?",
            "GainingPermissionPleaseWait": "Запрос прав доступа, подождите...",
            "TimeUnitDay": "день",
            "TimeUnitDays": "дня",
            "TimeUnitHour": "час",
            "TimeUnitHours": "часа",
            "TimeUnitMinute": "минута",
            "TimeUnitMinutes": "минуты",
            "TimeUnitSecond": "секунда",
            "TimeUnitSeconds": "секунды",
            "DownloadEndedPrematurely": "Загрузка завершилась преждевременно.",
            "UnsupportedArchiveFormat": "Неподдерживаемый формат архива: {0}",
            "UnableToLocateCurrentProcessPath": "Не удалось определить путь текущего процесса.",
            "UnableToDetermineApplicationDirectory": "Не удалось определить каталог приложения.",
            "SelectedNamespaceNotFound": "Выбранное пространство имён не найдено.",
            "UnsupportedOsForAutomaticUpdates": "Операционная система не поддерживает автоматические обновления.",
            "RemoteUpdatePayloadEmpty": "Удалённый пакет обновления пуст.",
            "FailedToParseRemoteUpdatePayload": "Не удалось разобрать удалённый пакет обновления.",
            "InstallLocationUserSelected": "Папка установки: выбрана пользователем.",
            "MakeBackupsBeforeModifying": "Резервные копии: перед изменением/перезаписью существующих файлов.",
            "LogLevelNothing": "Ничего: без отклика.",
            "LogLevelGeneral": "Общий: только прогресс.",
            "LogLevelErrors": "Ошибки: прогресс и ошибки.",
            "LogLevelWarnings": "Стандарт: прогресс, ошибки и предупреждения.",
            "LogLevelFull": "Полный: подробный прогресс (отладка).",
            "NoNamespacesOrChangesFoundInFormat": "В {0} не найдено namespaces.ini, namespaces.yaml, changes.ini или changes.yaml (или локализованных вариантов).",
            "NamespaceNotFoundInListFormat": "Пространство имён '{0}' не найдено в списке.",
            "InvalidKotorDirectoryFormat": "Недопустимый каталог KOTOR: {0}",
            "BackupFolderNotFoundFormat": "Папка резервных копий не найдена: {0}",
            "ChangesIniFileNotFoundFormat": "Файл INI изменений не найден: {0}",
            "NoContentInGitHubApiResponse": "В ответе GitHub API контент не найден",
            "JsonDataNotFoundOrMarkersIncorrect": "Данные JSON не найдены или маркеры неверны",
            "FailedToDeserializeRemoteInfo": "Не удалось десериализовать удалённую информацию",
            "TarGzRequiresNet8OrGreater": "Для распаковки tar.gz требуется .NET 8 или выше",
            "NoDirectDownloadLinksForFormat": "Прямые ссылки для загрузки для {0}/{1} не указаны.",
            "FlowDocumentNotInitialized": "FlowDocument не инициализирован",
            "ConfigSummaryTitle": "TSLPatcher - СВОДКА КОНФИГУРАЦИИ",
            "ConfigSummarySettings": "Настройки:",
            "ConfigFileLabel": "Файл конфигурации: ",
            "InformationFileLabel": "Информационный файл: ",
            "LogLevelLabel": "Уровень журнала: ",
            "DialogTlkAppending": "добавление dialog tlk:",
            "NewEntriesLabel": "Новые записи: ",
            "ConfigSummaryTwoDAFileChanges": "Изменения в файлах 2DA:",
            "ConfigSummaryGffFileChanges": "Изменения в файлах GFF:",
            "ConfigSummaryNcsIntegerHacks": "Целочисленные правки NCS:",
            "ConfigSummaryModifiedRecompiledScripts": "Изменённые и перекомпилированные скрипты:",
            "ConfigSummaryNewModifiedSoundsetFiles": "Новые/изменённые файлы набора звуков:",
            "ConfigSummaryUnpatchedFilesToInstall": "Непатченные файлы для установки:",
            "ConfigSummaryNone": "  (нет)",
            "ConfigSummaryNewRows": " - новых строк: ",
            "ConfigSummaryModifiedRows": ", изменённых строк: ",
            "ConfigSummaryNewColumns": ", новых столбцов: ",
            "ConfigSummaryModifyExistingLocation": " - изменить существующий, расположение: ",
            "ConfigSummaryLocation": " * Расположение: ",
            "ConfigSummaryOverwrite": "перезаписать",
            "ConfigSummarySkipExisting": "пропустить существующий",
            "ConfigurationSummaryToolTip": "Сводка конфигурации",
        }
    )
    return t


def _pl():
    t = _en().copy()
    t.update(
        {
            "MenuTools": "Narzędzia",
            "MenuHelp": "Pomoc",
            "HelpWindowTitle": "Pomoc",
            "OK": "OK",
            "MenuAbout": "O programie",
            "MenuLanguage": "Język",
            "ValidateIni": "Zwaliduj INI",
            "UninstallModRestoreBackup": "Odinstaluj mod / Przywróć kopię zapasową",
            "FixPermissionsToFileFolder": "Napraw uprawnienia pliku/folderu...",
            "FixIOSCaseSensitivity": "Napraw wielkość liter iOS",
            "CreateInfoRte": "Utwórz info.rte...",
            "DeadlyStream": "DeadlyStream",
            "Discord": "Discord",
            "Website": "Strona internetowa",
            "PCGamingWiki": "PCGamingWiki",
            "KOTOR1": "KOTOR 1",
            "KOTOR2TSL": "KOTOR 2: TSL",
            "KOTORCommunityPortal": "Portal społeczności KOTOR",
            "CheckForUpdates": "Sprawdź aktualizacje",
            "KPatcherHome": "Strona główna KPatcher",
            "GitHubSource": "Kod źródłowy GitHub",
            "Exit": "Zakończ",
            "Browse": "Przeglądaj",
            "PlaceholderSelectMod": "Wybierz mod do zainstalowania",
            "PlaceholderSelectKotor": "Wybierz ścieżkę folderu KOTOR",
            "AlphaBannerText": "⚠️ WERSJA ALFA — NIE DO UŻYTKU PRODUKCYJNEGO ⚠️",
            "AlphaWarningTitle": "OSTRZEŻENIE O WERSJI ALFA",
            "AlphaWarningMessageFormat": "⚠️ OSTRZEŻENIE: To jest wersja ALFA ({0}) KPatcher\n\nTa wersja jest wyłącznie do testów i demonstracji.\nNIE jest przeznaczona do użytku produkcyjnego.\n\nFunkcje mogą być niekompletne, niestabilne lub zawierać błędy.\nUżywasz na własną odpowiedzialność.\n\nDo użytku produkcyjnego użyj wersji stabilnej.",
            "WindowTitleFormat": "KOTORPatcher {0}",
            "WindowTitleAlphaSuffix": " [ALFA — NIE DO UŻYTKU PRODUKCYJNEGO]",
            "KOTORPatcherUpdate": "Aktualizacja KOTORPatcher",
            "Cancel": "Anuluj",
            "WelcomeToKPatcher": "Witamy w KPatcher!",
            "SelectModAndKotorToBegin": "Wybierz mod i folder KOTOR, aby rozpocząć.",
            "StartingInstallation": "Uruchamianie instalacji...",
            "PatcherFinishedTitle": "Patcher zakończony",
            "SelectModDirectory": "Wybierz folder moda",
            "SelectKotorDirectory": "Wybierz folder KOTOR",
            "ThisModRequiresConfirmation": "Ten mod wymaga potwierdzenia",
            "StartPatchingButtonLabel": "&Rozpocznij patchowanie",
            "Error": "Błąd",
            "WarningTitle": "Ostrzeżenie!",
            "WarningNotAToy": "To nie jest zabawka. Naprawdę kontynuować?",
            "SelectDirectoryFixPermissions": "Wybierz folder do naprawy uprawnień",
            "PleaseWaitMayTakeAWhile": "Proszę czekać, to może chwilę potrwać...",
            "SuccessfullyAcquiredPermission": "Uprawnienia uzyskane pomyślnie",
            "OperationSuccessfulFormat": "Operacja zakończona pomyślnie. {0}",
            "FilesAndFoldersProcessedFormat": "Przetworzono {0} plików i {1} folderów.",
            "CouldNotAcquirePermission": "Nie udało się uzyskać uprawnień!",
            "PermissionsDeniedCheckLogsFormat": "Odmowa uprawnień! Sprawdź dzienniki, aby uzyskać szczegóły.{0}{1}",
            "SelectDirectoryFixCaseSensitivity": "Wybierz folder do naprawy wielkości liter",
            "NothingToChangeCase": "Nic do zmiany — wszystkie pliki/foldery mają już poprawną wielkość liter.",
            "IOSCaseRenameTaskCompleted": "Zadanie zmiany wielkości liter iOS zakończone.",
            "UpdateError": "Błąd aktualizacji",
            "UnableToFetchUpdateInfo": "Nie można pobrać informacji o aktualizacji. Spróbuj ponownie później.",
            "UpdateAvailable": "Dostępna aktualizacja",
            "UpdateAvailableMessageFormat": "Dostępna jest nowsza wersja KPatcher ({0}).{1}{1}{2}",
            "UpdateButton": "Aktualizuj",
            "ManualDownloadButton": "Pobierz ręcznie",
            "NoUpdatesFound": "Brak aktualizacji",
            "NoUpdatesFoundMessageFormat": "Używasz już najnowszej wersji KPatcher ({0}).",
            "ReinstallButton": "Zainstaluj ponownie",
            "NoNamespaceSelected": "Nie wybrano przestrzeni nazw",
            "PleaseSelectNamespaceFirst": "Najpierw wybierz przestrzeń nazw.",
            "NoDescriptionAvailable": "Brak opisu.",
            "CouldNotFindModAtFolderFormat": "Nie znaleziono moda w podanym folderze.{0}{1}",
            "TaskAlreadyRunning": "Zadanie jest już wykonywane",
            "WaitForPreviousTask": "Poczekaj na zakończenie poprzedniego zadania.",
            "NoModChosen": "Nie wybrano moda",
            "SelectModDirectoryFirst": "Najpierw wybierz folder moda.",
            "NoGameFolder": "Brak folderu gry",
            "InvalidGameFolder": "Nieprawidłowy folder gry",
            "PreparingUpdate": "Przygotowywanie aktualizacji...",
            "EstimatedTimeRemainingFormat": "Szacowany pozostały czas: {0}",
            "Downloaded": "pobrano",
            "ByteB": "B",
            "ByteKB": "KB",
            "ByteMB": "MB",
            "ByteGB": "GB",
            "DownloadingKPatcherFormat": "Pobieranie KPatcher {0}...",
            "DownloadComplete": "Pobieranie zakończone.",
            "ExtractingUpdatePackage": "Wypakowywanie pakietu aktualizacji...",
            "ArchiveExtracted": "Archiwum wypakowane.",
            "FinalizingUpdate": "Finalizowanie aktualizacji...",
            "RestartingToCompleteUpdate": "Ponowne uruchamianie w celu dokończenia aktualizacji...",
            "DownloadFailedFromFormat": "Pobieranie z {0} nie powiodło się: {1}",
            "AllUpdateMirrorsFailed": "Wszystkie serwery aktualizacji są niedostępne.",
            "RteEditorTitle": "Edytor RTE",
            "OpenInfoRte": "Otwórz info.rte",
            "SaveInfoRte": "Zapisz info.rte",
            "RteFileFilter": "Edytor tekstu sformatowanego (*.rte)",
            "UnsavedChanges": "Niezapisane zmiany",
            "UnsavedChangesDiscardPrompt": "Masz niezapisane zmiany. Czy chcesz je odrzucić?",
            "FailedToLoadRtfContent": "Nie można załadować zawartości RTF. Sprawdź konsolę, aby uzyskać szczegóły.",
            "Untitled": "Bez tytułu",
            "MenuFile": "_Plik",
            "MenuNew": "_Nowy",
            "MenuOpen": "_Otwórz...",
            "MenuSave": "_Zapisz",
            "MenuSaveAs": "Zapisz _jako...",
            "MenuClose": "_Zamknij",
            "Bold": "Pogrubienie",
            "Italic": "Kursywa",
            "Underline": "Podkreślenie",
            "Strike": "Przekreślenie",
            "AlignLeft": "Wyrównaj do lewej",
            "AlignCenter": "Wyśrodkuj",
            "AlignRight": "Wyrównaj do prawej",
            "ColorBlack": "Czarny",
            "ColorRed": "Czerwony",
            "ColorGreen": "Zielony",
            "ColorBlue": "Niebieski",
            "ColorGray": "Szary",
            "ColorTransparent": "Przezroczysty",
            "ColorYellow": "Żółty",
            "ColorLightBlue": "Jasnoniebieski",
            "ColorLightGreen": "Jasnozielony",
            "InstallationCompleteWithErrorsAndWarningsFormat": "Instalacja zakończona z {0} błędami i {1} ostrzeżeniami.{2}Czas instalacji: {3}{2}Łącznie łatek: {4}",
            "UnexpectedErrorDuringInstallationFormat": "Wystąpił nieoczekiwany błąd; instalacja została przerwana.{0}{0}{1}",
            "ConfigReaderTestComplete": "Test czytnika konfiguracji zakończony.",
            "UninstallProcessFinished": "Odinstalowywanie zakończone.",
            "PermissionsFixerTaskCompleted": "Zadanie naprawy uprawnień plików/folderów zakończone.",
            "AtLeastOneOptionRequired": "Wymagana jest co najmniej jedna opcja.",
            "DefaultInstallation": "Instalacja domyślna",
            "LoadedNamespacesCountFormat": "Załadowano {0} przestrzeni nazw.",
            "DetectedKotorInstallationsFormat": "Wykryto {0} instalacji KOTOR.",
            "AutoOpeningModFromFormat": "Automatyczne otwieranie moda z: {0}",
            "InstallationCancelled": "Instalacja została anulowana.",
            "NoBackupDirectoryFoundFormat": "Nie znaleziono folderu kopii zapasowej w {0}",
            "UninstallFailedFormat": "Odinstalowanie nie powiodło się: {0}",
            "UnableToLocateWindowForUpdater": "Nie można zlokalizować okna aktualizatora.",
            "UnableToOpenRteEditorWindow": "Nie można otworzyć edytora RTE: okno niedostępne.",
            "FailedToLoadRteContentFormat": "Nie można załadować zawartości RTF: {0}",
            "FailedToLoadModFormat": "Nie można załadować moda: {0}",
            "FailedToLoadNamespaceConfigFormat": "Nie można załadować konfiguracji przestrzeni nazw: {0}",
            "PleaseSelectModAndGameDirectory": "Wybierz mod i folder gry.",
            "InstallationFailedFormat": "Instalacja nie powiodła się: {0}",
            "ValidationFailedFormat": "Walidacja nie powiodła się: {0}",
            "FailedToFixPermissionsFormat": "Naprawa uprawnień nie powiodła się: {0}",
            "FailedToFixCaseSensitivityFormat": "Naprawa wielkości liter nie powiodła się: {0}",
            "FailedToOpenUrlFormat": "Nie udało się otworzyć adresu URL: {0}",
            "NoBackupsFoundTitle": "Nie znaleziono kopii zapasowych!",
            "NoBackupsFoundMessageFormat": "Nie znaleziono kopii zapasowych w '{0}'!{1}KPatcher nie może odinstalować instalacji KPatcher.exe.",
            "BackupOutOfDateOrMismatched": "Kopia zapasowa nieaktualna lub niezgodna",
            "BackupMismatchMessageFormat": "Ta kopia nie pasuje do Twojej instalacji KOTOR. Brakuje lub zmieniono pliki.{0}Odinstaluj wszystkie mody w kolejności instalacji.{0}Upewnij się, że wybrałeś właściwy mod i folder KOTOR.{0}Kontynuować?",
            "Confirmation": "Potwierdzenie",
            "ReallyUninstallConfirmFormat": "Czy na pewno odinstalować {0} plików i przywrócić najnowszą kopię zapasową ({1} plików, {2} folderów)?{3}Uwaga: używana jest najnowsza kopia zapasowa tego moda.",
            "FailedToRestoreBackupFormat": "Nie udało się przywrócić kopii zapasowej (wyjątek).{0}{0}{1}",
            "UninstallCompletedTitle": "Odinstalowanie zakończone!",
            "UninstallCompletedDeleteBackupFormat": "Usunięto {0} plików i przywrócono kopię zapasową z {1}{2}{2}Czy usunąć kopię zapasową z {1}?",
            "PermissionErrorTitle": "Błąd uprawnień",
            "UnableToDeleteBackupPermissionFormat": "Nie można usunąć przywróconej kopii (uprawnienia). Uzyskać uprawnienia i spróbować ponownie?",
            "GainingPermissionPleaseWait": "Uzyskiwanie uprawnień, proszę czekać...",
            "TimeUnitDay": "dzień",
            "TimeUnitDays": "dni",
            "TimeUnitHour": "godzina",
            "TimeUnitHours": "godziny",
            "TimeUnitMinute": "minuta",
            "TimeUnitMinutes": "minuty",
            "TimeUnitSecond": "sekunda",
            "TimeUnitSeconds": "sekundy",
            "DownloadEndedPrematurely": "Pobieranie zakończyło się przedwcześnie.",
            "UnsupportedArchiveFormat": "Nieobsługiwany format archiwum: {0}",
            "UnableToLocateCurrentProcessPath": "Nie można ustalić ścieżki bieżącego procesu.",
            "UnableToDetermineApplicationDirectory": "Nie można ustalić katalogu aplikacji.",
            "SelectedNamespaceNotFound": "Nie znaleziono wybranej przestrzeni nazw.",
            "UnsupportedOsForAutomaticUpdates": "System operacyjny nieobsługiwany przy automatycznych aktualizacjach.",
            "RemoteUpdatePayloadEmpty": "Zdalny pakiet aktualizacji był pusty.",
            "FailedToParseRemoteUpdatePayload": "Nie udało się przeanalizować zdalnego pakietu aktualizacji.",
            "InstallLocationUserSelected": "Lokalizacja instalacji: wybrana przez użytkownika.",
            "MakeBackupsBeforeModifying": "Kopie zapasowe: przed modyfikacją/nadpisywaniem istniejących plików.",
            "LogLevelNothing": "Nic: brak informacji.",
            "LogLevelGeneral": "Ogólny: tylko postęp.",
            "LogLevelErrors": "Błędy: postęp i błędy.",
            "LogLevelWarnings": "Standard: postęp, błędy i ostrzeżenia.",
            "LogLevelFull": "Pełny: szczegółowy postęp (debugowanie).",
            "NoNamespacesOrChangesFoundInFormat": "Nie znaleziono namespaces.ini, namespaces.yaml, changes.ini ani changes.yaml (ani wariantów zlokalizowanych) w {0}",
            "NamespaceNotFoundInListFormat": "Przestrzeń nazw „{0}” nie została znaleziona na liście.",
            "InvalidKotorDirectoryFormat": "Nieprawidłowy katalog KOTOR: {0}",
            "BackupFolderNotFoundFormat": "Nie znaleziono folderu kopii zapasowych: {0}",
            "ChangesIniFileNotFoundFormat": "Nie znaleziono pliku INI zmian: {0}",
            "NoContentInGitHubApiResponse": "Nie znaleziono treści w odpowiedzi API GitHub",
            "JsonDataNotFoundOrMarkersIncorrect": "Nie znaleziono danych JSON lub znaczniki są nieprawidłowe",
            "FailedToDeserializeRemoteInfo": "Nie udało się zdeserializować zdalnych informacji",
            "TarGzRequiresNet8OrGreater": "Rozpakowanie tar.gz wymaga .NET 8 lub nowszego",
            "NoDirectDownloadLinksForFormat": "Nie podano bezpośrednich linków do pobrania dla {0}/{1}.",
            "FlowDocumentNotInitialized": "FlowDocument nie jest zainicjowany",
            "ConfigSummaryTitle": "TSLPatcher - PODSUMOWANIE KONFIGURACJI",
            "ConfigSummarySettings": "Ustawienia:",
            "ConfigFileLabel": "Plik konfiguracyjny: ",
            "InformationFileLabel": "Plik informacyjny: ",
            "LogLevelLabel": "Poziom dziennika: ",
            "DialogTlkAppending": "dołączanie dialog tlk:",
            "NewEntriesLabel": "Nowe wpisy: ",
            "ConfigSummaryTwoDAFileChanges": "Zmiany w plikach 2DA:",
            "ConfigSummaryGffFileChanges": "Zmiany w plikach GFF:",
            "ConfigSummaryNcsIntegerHacks": "Zmiany całkowitoliczbowe NCS:",
            "ConfigSummaryModifiedRecompiledScripts": "Zmodyfikowane i skompilowane skrypty:",
            "ConfigSummaryNewModifiedSoundsetFiles": "Nowe/zmodyfikowane pliki zestawu dźwięków:",
            "ConfigSummaryUnpatchedFilesToInstall": "Niezałatane pliki do instalacji:",
            "ConfigSummaryNone": "  (brak)",
            "ConfigSummaryNewRows": " - nowe wiersze: ",
            "ConfigSummaryModifiedRows": ", zmodyfikowane wiersze: ",
            "ConfigSummaryNewColumns": ", nowe kolumny: ",
            "ConfigSummaryModifyExistingLocation": " - zmodyfikuj istniejący, lokalizacja: ",
            "ConfigSummaryLocation": " * Lokalizacja: ",
            "ConfigSummaryOverwrite": "nadpisz",
            "ConfigSummarySkipExisting": "pomiń istniejący",
            "ConfigurationSummaryToolTip": "Podsumowanie konfiguracji",
        }
    )
    return t


def escape_xml(s: str) -> str:
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace('"', "&quot;")


def get_all_keys():
    base = _en()
    return sorted(base.keys())


def write_resx(path: Path, data: dict):
    lines = [HEADER.rstrip()]
    for key in get_all_keys():
        value = data.get(key, _en().get(key, ""))
        v = escape_xml(value)
        lines.append(f'  <data name="{key}" xml:space="preserve"><value>{v}</value></data>')
    lines.append("</root>")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main():
    root = Path(__file__).resolve().parents[1] / "src" / "KPatcher.UI" / "Resources"
    lang_data = {"es": _es(), "de": _de(), "fr": _fr(), "ru": _ru(), "pl": _pl()}
    for lang in ("es", "de", "fr", "ru", "pl"):
        write_resx(root / f"UIResources.{lang}.resx", lang_data[lang])
    print("Wrote UI satellite resx files.")


if __name__ == "__main__":
    main()
