# -*- coding: utf-8 -*-
"""Generate PatcherResources.{es,de,fr,ru,pl}.resx from PatcherResources.resx + translation overrides."""

import re

from pathlib import Path

HEADER = """<?xml version="1.0" encoding="utf-8"?>
<root>
  <resheader name="resmimetype"><value>text/microsoft-resx</value></resheader>
  <resheader name="version"><value>2.0</value></resheader>
  <resheader name="reader"><value>System.Resources.ResXResourceReader, System.Resources.Extensions, Version=9.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51</value></resheader>
  <resheader name="writer"><value>System.Resources.ResXResourceWriter, System.Resources.Extensions, Version=9.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51</value></resheader>
"""


def _read_english_from_resx(root: Path) -> dict:
    """Read (name, value) from PatcherResources.resx. Un-escapes XML entities in value."""
    resx_path = root / "PatcherResources.resx"
    text = resx_path.read_text(encoding="utf-8")
    # Match <data name="Key" ...><value>...</value></data>; value may span lines and contain \n
    pattern = re.compile(r'<data name="([^"]+)"[^>]*>\s*<value>([\s\S]*?)</value>\s*</data>')
    result = {}
    for m in pattern.finditer(text):
        key, raw_val = m.group(1), m.group(2)
        # Unescape for use in Python; we re-escape when writing
        val = (
            raw_val.replace("&lt;", "<")
            .replace("&gt;", ">")
            .replace("&quot;", '"')
            .replace("&amp;", "&")
        )
        result[key] = val
    return result


# English keys match PatcherResources.resx (values are translations)
TRANSLATIONS = {
    "es": {
        "StartPatchingButton": "&Iniciar parcheo",
        "StartPatchingConfirmation": "Esto iniciará el parcheo de los archivos del juego necesarios. ¿Desea continuar?",
        "InvalidGameFolderDialogTlkNotFound": "Carpeta del juego no válida, ¡no se encontró dialog.tlk! Asegúrese de haber seleccionado el directorio correcto del juego.",
        "NoValidGameFolderSelected": "¡Error! No se seleccionó una carpeta de juego válida. Instalación cancelada.",
        "SkippingFileNoOverwriteDialogTlk": "Omitiendo el archivo {0}, este instalador no sobrescribirá dialog.tlk directamente.",
        "NwnnsscompNotFoundInTslPatchData": "¡No se encontró nwnnsscomp.exe en la carpeta TSLPatchData! No se puede compilar el script.",
        "Invalid2DAMemoryToken": "¡Token 2DAMEMORY no válido! Los índices de token empiezan en 1 y suben.",
        "PatcherFinished": "El parcheador ha terminado. Revise el registro de progreso para ver qué se instaló.",
        "PatcherFinishedWithWarnings": "El parcheador ha terminado, pero se encontraron {0} advertencias. El mod puede funcionar o no correctamente.",
        "PatcherFinishedWithErrors": "El parcheador ha terminado, pero se encontraron {0} errores. Es probable que el mod no se haya instalado correctamente.",
        "PatcherFinishedWithErrorsAndWarnings": "El parcheador ha terminado, pero se encontraron {0} errores y {1} advertencias. Es probable que el mod no se haya instalado correctamente.",
        "StrRefTokenNotInTLK": 'Token StrRef "{0}" en la lista de modificadores que no estaba en el TLK.',
        "NoNewEntriesAppendedToTlk": "Advertencia: No se añadieron entradas nuevas a {0}. Posibles entradas faltantes en append.tlk.",
        "NoTLKFileLoaded": "No hay archivo TLK cargado. No se puede continuar.",
        "UnableToLocateTLKFileToPatch": '¡Error! No se pudo localizar el archivo TLK a parchear, ¡no se encontró el archivo "{0}"!',
        "UnableToFind2DAFileToModify": 'No se encuentra el archivo 2DA "{0}" para modificar. Omitiendo archivo...',
        "ErrorLookingUpRowLabelForRowIndex": "Error al buscar la etiqueta de fila para el índice de fila {0}.",
        "ErrorLookingUpColumnLabelForColumnIndex": "Error al buscar la etiqueta de columna para el índice de columna {0}.",
        "UsedAsIndexBut2DAHasNoLabel": '{0} usado como índice al cambiar la línea en el modificador "{1}" pero el archivo 2DA no tiene etiqueta para ese índice.',
        "FailedToCopyLine2DA": "¡Error! No se pudo copiar la línea en 2DA. Omitiendo...",
        "UnableToLoad2DAFileSkipping": "No se pudo cargar el archivo 2DA {0}. Omitiéndolo...",
        "NoValueAssignedColumn2DA": 'No se ha asignado valor a la columna {0} para la nueva línea 2DA en el modificador "{1}"...',
        "ErrorAddingNewLine2DA": '¡Ocurrió un error al intentar añadir una nueva línea 2DA en el modificador "{0}"!',
        "InternalErrorInvalidTLKFileType": "Error interno, tipo de archivo TLK no válido especificado.",
        "CriticalErrorUnableToLocateFileToPatch": 'Error crítico: No se pudo localizar el archivo a parchear, ¡no se encontró el archivo "{0}"!',
        "NoFileToInstallSpecified": "¡Error! No se especificó ningún archivo para instalar.",
        "NoInstallPathSet": "¡Error! No se ha establecido la ruta de instalación.",
        "FileSetToPatchDoesNotExist": '¡Error! El archivo "{0}" marcado para parchear no existe.',
        "UnableToLoadInstructionsTslpatchdata": 'No se pudieron cargar las instrucciones. Asegúrese de que la carpeta "tslpatchdata" contiene el archivo "info.rtf".',
        "SectionNotFoundError": "No se encontró la sección [{0}] en el ini",
        "ReferencesTracebackMsg": ", referenciado por '{0}={1}' en [{2}]",
        "ErrorParsingIniFile": "Error al analizar el archivo INI: {0}",
        "IniFileNotFound": "Archivo INI no encontrado: {0}",
        "IniTextCannotBeNullOrEmpty": "El texto INI no puede ser nulo o vacío",
        "LanguageIntegerNotKnown": "Entero de idioma desconocido: {0}",
        "NoEncodingDefinedForLanguage": "No hay codificación definida para el idioma: {0}",
        "FilePatcherDescription": "Parcheador de archivos 2DA/TLK/GFF/NSS/SSF/ERF/RIM para KotOR/TSL.",
        "NoLineSetToBeModifiedFormat": "No hay línea definida para modificar en [{0}].",
        "OrphanedIniSectionsFormat": "Se encontraron secciones ini huérfanas en los cambios:\n{0}",
        # Install log
        "InstallationLogHeader": "Registro de Instalación de KPatcher",
        "InstallationLogHeaderSeparator": "===========================",
        "InstallationDate": "Fecha de Instalación: {0}",
        "ModPath": "Ruta del Mod: {0}",
        "GamePath": "Ruta del Juego: {0}",
        "GameDetected": "Juego Detectado: {0}",
        "FileOperationFormat": "{0}: {1} -> {2}",
        "FileOperationErrorFormat": "Error al {0} {1} a {2}",
        "FileOperationErrorWithMessageFormat": "Error al {0} {1} a {2}: {3}",
        "PatchOperationFormat": "Parcheando {0}: {1} - {2}",
        # ModInstaller
        "CouldNotFindChangesIniFile": "No se pudo encontrar el archivo changes.ini en el disco.",
        "CouldNotCreateInstallLogFile": "No se pudo crear el archivo de registro de instalación: {0}",
        "ChangesConfigFileNotFound": "Archivo de configuración changes no encontrado: {0}",
        "CouldNotDetermineEncoding": "No se pudo determinar la codificación de '{0}'. Intentando cargar forzadamente...",
        "CouldNotWriteEquivalentYaml": "No se pudo escribir el YAML equivalente: {0}",
        "CouldNotInitializeUninstallDirectory": "No se pudo inicializar el directorio de desinstalación: {0}",
        "CouldNotCreateBackupFolder": "No se pudo crear la carpeta de respaldo: {0}",
        "UsingBackupDirectory": "Usando directorio de respaldo: '{0}'",
        "InvalidKotorDirectory": "El directorio de KOTOR elegido no es una instalación válida - no se puede inicializar ModInstaller.",
        "StartingInstallation": "Iniciando instalación...",
        "LoadingConfigurationFrom": "Cargando configuración desde {0}",
        "FoundPatchesToApply": "Se encontraron {0} parches para aplicar",
        "InstallationTerminationRequest": "ModInstaller.Install() recibió solicitud de terminación, cancelando...",
        "ProcessingInstallListEntries": "Procesando entradas de InstallList...",
        "ProcessingTlkPatches": "Procesando parches TLK...",
        "Processing2DAPatches": "Procesando parches 2DA...",
        "ProcessingGffPatches": "Procesando parches GFF...",
        "ProcessingNssScriptPatches": "Procesando parches de scripts NSS...",
        "ProcessingNcsScriptPatches": "Procesando parches de scripts NCS...",
        "ProcessingSsfSoundPatches": "Procesando parches de sonido SSF...",
        "FileHasNoContent": "'{0}' no tiene contenido/datos y está completamente vacío.",
        "SkippingFilePatchResource": "Omitiendo '{0}' - patch_resource determinó que este archivo puede ser omitido.",
        "CleaningTemporaryScriptFolder": "Limpiando carpeta temporal de scripts en '{0}' (pista: use 'SaveProcessedScripts=1' en [Settings] para conservar estos scripts)",
        "SuccessfullyCompletedFormat": "Completado exitosamente {0} {1}.",
        "InstallationCompletedSuccessfully": "Instalación completada exitosamente",
        "InstallationFailedFormat": "Instalación fallida: {0}",
        "PatchingRimFileWarning": "¡Este mod está parcheando el archivo RIM Modules/{0}!\nParchear RIMs es altamente incompatible, no recomendado y ampliamente considerado una mala práctica. Por favor, solicite al desarrollador del mod que lo corrija.",
        "ModuleDidNotExistBuilding": "¡IMPORTANTE! El módulo en la ruta '{0}' no existía, construyendo uno en la carpeta 'Modules' inmediatamente desde los siguientes archivos:",
        "FailedToBuildModule": "Error al construir el módulo '{0}': {1}",
        "CapsuleNotFoundOrPermission": "La cápsula '{0}' no existía, o ocurrieron problemas de permisos, al intentar {1} '{2}'. Omitiendo archivo...",
        "BackingUpFile": "Haciendo respaldo de '{0}'...",
        "FailedToCreateBackup": "Error al crear respaldo de '{0}': {1}",
        "CouldNotLoadSourceFileMissing": "No se pudo cargar el archivo fuente para {0}: SourceFile está faltando o vacío (corrija o elimine esta fila de InstallList / patch en changes.ini).",
        "CouldNotLoadFileSaveAsMissing": "No se pudo cargar el archivo para {0}: SaveAs está faltando o vacío.",
        "CouldNotLoadResourceFromCapsule": "No se pudo cargar el recurso de la cápsula para {0}: SaveAs está faltando o vacío.",
        "CouldNotLoadSourceFileFormat": "No se pudo cargar el archivo fuente para {0}:{1}{2}",
        "CapsuleNotFoundWhenAttempting": "La cápsula '{0}' no existía al intentar {1} '{2}'. Omitiendo archivo...",
        "RenamedExistingOverrideFile": "Renombrado archivo Override existente '{0}' a '{1}' para prevenir sombreado.",
        "CouldNotRenameInOverrideFolder": "No se pudo renombrar '{0}' a '{1}' en la carpeta Override: {2}",
        "ResourceShadowingModChanges": "¡Un recurso ubicado en '{0}' está sombreando los cambios de este mod en {1}!",
        "ModOvershadowedByExisting": "¡Este mod intenta instalar '{0}' en '{1}', pero está ensombrecido por el '{2}' existente!",
        # ConfigReader
        "ConfigReaderFinishedLoadingIni": "El ConfigReader terminó de cargar el INI",
        "SettingsSectionMissing": "Sección [Settings] faltante en el ini.",
        "LoadingSettingsSection": "Cargando sección [Settings] del ini...",
        "InstallListSectionMissing": "Sección [InstallList] faltante en el ini.",
        "LoadingInstallListPatches": "Cargando parches [InstallList] del ini...",
        "SkippingEmptyInstallListEntry": "Omitiendo entrada vacía de InstallList (línea en blanco o clave vacía en la sección [InstallList] de changes.ini).",
        "TlkListSectionMissing": "Sección [TLKList] faltante en el ini.",
        "LoadingTlkListPatches": "Cargando parches [TLKList] del ini...",
        "TwoDAListSectionMissing": "Sección [2DAList] faltante en el ini.",
        "LoadingTwoDAListPatches": "Cargando parches [2DAList] del ini...",
        "SsfListSectionMissing": "Sección [SSFList] faltante en el ini.",
        "LoadingSsfListPatches": "Cargando parches [SSFList] del ini...",
        "GffListSectionMissing": "Sección [GFFList] faltante en el ini.",
        "LoadingGffListPatches": "Cargando parches [GFFList] del ini...",
        "CompileListSectionMissing": "Sección [CompileList] faltante en el ini.",
        "LoadingCompileListPatches": "Cargando parches [CompileList] del ini...",
        "HackListSectionMissing": "Sección [HACKList] faltante en el ini.",
        "LoadingHackListPatches": "Cargando parches [HACKList] del ini...",
        # CLI
        "CliErrorNoModPath": "[Error] No se especificó la ruta del mod. Use --tslpatchdata <ruta>",
        "CliErrorFailedToLoadMod": "[Error] Error al cargar el mod: {0}",
        "CliErrorNamespaceIndexOutOfRange": "[Error] Índice de namespace {0} fuera de rango (máx: {1})",
        "CliErrorNoGameDirectory": "[Error] No se especificó el directorio del juego. Use --game-dir <ruta>",
        "CliErrorInvalidGameDirectory": "[Error] Directorio de juego inválido: {0}: {1}",
        "CliErrorInvalidModOrGamePaths": "[Error] Rutas de mod o juego inválidas",
        "CliErrorCannotRunMultipleOperations": "[Error] No se puede ejecutar más de una de [--install, --uninstall, --validate]",
        "CliErrorMustSpecifyOperation": "[Error] Debe especificar una de [--install, --uninstall, --validate] para el modo CLI",
        "CliInfoInstallingMod": "[Info] Instalando mod desde {0} a {1}",
        "CliInfoInstallCompleted": "[Info] Instalación completada: {0} errores, {1} advertencias, {2} parches",
        "CliInfoInstallTime": "[Info] Tiempo de instalación: {0}",
        "CliInfoUninstallingMod": "[Info] Desinstalando mod desde {0}",
        "CliInfoUseHelpForOptions": "[Info] Use --help para ver opciones de CLI",
        "CliWarningDisplayDriverNotAvailable": "[Advertencia] Controlador de pantalla no disponible, no se puede ejecutar en modo GUI: {0}",
        "CliInfoUninstallCompletedSuccessfully": "[Info] Desinstalación completada exitosamente",
        "CliWarningUninstallCompletedWithWarnings": "[Advertencia] Desinstalación completada con advertencias",
        "CliInfoValidatingMod": "[Info] Validando configuración del mod",
        "CliInfoValidationCompletedSuccessfully": "[Info] Validación completada exitosamente",
        "CliErrorFormat": "[Error] {0}: {1}",
        "CliInnerException": "Excepción Interna: {0}",
        # ErrorHandling
        "UnknownException": "Excepción desconocida",
        "CouldNotFindFile": "No se pudo encontrar el archivo: '{0}'",
        "CouldNotFindDirectory": "No se pudo encontrar el directorio: '{0}'",
        "PermissionDenied": "Permiso Denegado: {0}",
        "OperationTimedOut": "Operación agotó el tiempo de espera: {0}",
        "OperationWasCancelled": "Operación fue cancelada: {0}",
        "IOError": "Error de E/S: {0}",
        "ExceptionInformationHeader": "  Información:",
        # ModUninstaller
        "RemovedFormat": "Eliminado {0}...",
        "RestoringBackupOf": "Restaurando respaldo de '{0}' a '{1}'...",
        "UsingBackupFolder": "Usando carpeta de respaldo '{0}'",
        "WouldRestoreFile": "Se restauraría el archivo '{0}'",
        "DeletedRestoredBackup": "Respaldo restaurado '{0}' eliminado",
        # GFF/Interpreter/CodeRoot (technical)
        "ExpectedGffStructButGot": "Se esperaba GFFStruct pero se obtuvo {0}",
        "DoesNotExist": "No existe",
        "PathPointsToExpectedGffList": "La ruta apunta a un '{0}', se esperaba un GFFList.",
        "UnableToAddStructToList": "No se pudo agregar struct a la lista '{0}': {1}",
        "IniSectionThrewException": "La sección INI [{0}] lanzó una excepción: {1}",
        "FailedToAddNewStructToList": "Error al agregar un nuevo struct a la lista '{0}' en [{1}]. Razón: Se esperaba GFFStruct pero se obtuvo '{2}' ({3}) de tipo {4} Omitiendo...",
        "Set2DAMemory": "Establecer 2DAMEMORY{0}={1}",
        "UnexpectedModifierType": "Tipo de modificador inesperado: {0}: {1}",
        "ResolvedGffListPath": "Ruta GFFList resuelta de [{0}] desde '{1}' --> '{2}'",
        "ApplyPatchFromIniSection": "Aplicar parche desde la sección INI [{0}] FieldType: {1} Ruta GFF: '{2}'",
        "UnableToAddNewGffField": "¡No se pudo agregar el nuevo campo GFF '{0}' en la ruta GFF '{1}'! Esto {2}",
        "InstructionJumpsToNotInList": "La instrucción #{0} ({1}) salta a una instrucción que no está en la lista. Hash del objetivo de salto: {2}",
        "InstructionLimitExceeded": "Límite de instrucciones excedido: {0} instrucciones ejecutadas",
        "InfiniteLoopDetectedExecuted": "Bucle infinito detectado: la instrucción en el índice {0} ({1}) ha sido ejecutada {2} veces",
        "JumpInstructionNoTarget": "La instrucción de salto {0} en el índice {1} no tiene objetivo de salto",
        "JumpTargetNotFound": "Objetivo de salto para la instrucción {0} no encontrado en la tabla de instrucciones",
        "InfiniteLoopJumpsToItself": "Bucle infinito detectado: {0} en el índice {1} salta a sí mismo",
        "CannotAdvanceSameInstruction": "No se puede avanzar: la siguiente instrucción en el índice {0} es la misma que la actual en el índice {1}",
        "InstructionNotPresentInTable": "Instrucción no presente en la tabla de instrucciones actual",
        "InstructionNotImplemented": "Instrucción {0} no implementada",
        "StoreStateCannotAccessInstruction": "STORE_STATE en el índice {0}: no se puede acceder a la instrucción en el índice {1}",
        "StoreStateReachedEndWithoutRetn": "STORE_STATE en el índice {0}: se alcanzó el final de las instrucciones sin encontrar RETN",
        "ActionInstructionRequiresTwoArgs": "La instrucción ACTION requiere al menos 2 argumentos",
        "ActionIdOutOfRange": "El ID de acción {0} está fuera de rango (0-{1})",
        "StackUnderflowPoppingVector": "Desbordamiento de pila al extraer vector para '{0}'",
        "StackUnderflowPoppingArgument": "Desbordamiento de pila al extraer argumento para '{0}'",
        "FileHasNoEntryPoint": "Este archivo no tiene punto de entrada y no puede ser compilado (Probablemente un archivo include).",
        "InvalidNssSourceProvided": "Fuente nss no válida proporcionada a ModificationsNSS.PatchResource()",
        "BuiltInCompilationFailedFormat": "La compilación integrada falló para '{0}': {1}",
        "CouldNotCompileReturningUncompiledFormat": "No se pudo compilar '{0}'. Devolviendo fuente NSS sin compilar.",
        "ExpectedMutableStringButGotFormat": "Se esperaba MutableString para ModificationsNSS, pero se obtuvo {0}",
        "PatchingFromUnixCompilingFormat": "Parcheando desde un sistema operativo unix, compilando '{0}' usando los compiladores integrados...",
        "ExpectedByteArrayButGotFormat": "Se esperaba byte[] para ModificationsNCS, pero se obtuvo {0}",
        "GffPathNotFoundDefaultingToRootFormat": "Ruta GFF '{0}' no encontrada, usando la estructura raíz gff por defecto.",
        "UnableToModifyGffFieldFormat": "No se pudo modificar el campo GFF '{0}'. Ruta '{1}' {2}",
        "PathDoesNotExist": "¡no existe!",
        "PathIsNotGffStructInstance": "no es una instancia de un GFFStruct.",
        "ExpectedGffObjectButGotFormat": "Se esperaba un objeto GFF para ModificationsGFF, pero se obtuvo {0}",
        "ErrorOccurredWhileCompilingTryingExternalFormat": "Ocurrió un error al compilar '{0}' con el compilador integrado, intentando compilador externo...",
        "ExpectedSsfObjectButGotFormat": "Se esperaba un objeto SSF para ModificationsSSF, pero se obtuvo {0}",
        "UnableToUseFieldPathFrom2DAMemoryFormat": "No se puede usar !FieldPath desde 2DAMEMORY. Campo padre en '{0}' {1}",
        "ExpectedLocalizedStringButGotFormat": "Se esperaba LocalizedString pero se obtuvo {0}",
        "ExpectedLocalizedStringDeltaButGotFormat": "Se esperaba LocalizedStringDelta para el campo existente pero se obtuvo {0}",
        "ExpectedTlkObjectButGotFormat": "Se esperaba un objeto TLK para ModificationsTLK, pero se obtuvo {0}",
        "ManagedCompilationFailedFormat": "La compilación administrada falló para '{0}': {1}",
        "CompiledUsingExternalNwnnsscompFormat": "Compilado '{0}' usando nwnnsscomp.exe externo (compilación administrada falló).",
        "ExternalNwnnsscompAlsoFailedFormat": "El nwnnsscomp externo también falló para '{0}': {1}",
        "NwnnsscompNotExpectedVersionFormat": "El nwnnsscomp.exe no es la versión esperada de KPatcher (detectada: {0}).",
        "ExpectedTwoDAObjectButGotFormat": "Se esperaba un objeto TwoDA para Modifications2DA, pero se obtuvo {0}",
    },
    "de": {
        "StartPatchingButton": "&Patching starten",
        "StartPatchingConfirmation": "Damit werden die erforderlichen Spieldateien gepatcht. Möchten Sie fortfahren?",
        "InvalidGameFolderDialogTlkNotFound": "Ungültiger Spielordner, dialog.tlk nicht gefunden! Wählen Sie das richtige Spielverzeichnis.",
        "NoValidGameFolderSelected": "Fehler! Kein gültiger Spielordner ausgewählt! Installation abgebrochen.",
        "SkippingFileNoOverwriteDialogTlk": "Datei {0} wird übersprungen; dieser Installer überschreibt dialog.tlk nicht direkt.",
        "NwnnsscompNotFoundInTslPatchData": "nwnnsscomp.exe wurde im TSLPatchData-Ordner nicht gefunden! Skript kann nicht kompiliert werden.",
        "Invalid2DAMemoryToken": "Ungültiges 2DAMEMORY-Token! Token-Indizes beginnen bei 1.",
        "PatcherFinished": "Der Patcher ist fertig. Prüfen Sie das Fortschrittsprotokoll für Details.",
        "PatcherFinishedWithWarnings": "Der Patcher ist fertig, aber {0} Warnungen sind aufgetreten! Der Mod funktioniert möglicherweise nicht korrekt.",
        "PatcherFinishedWithErrors": "Der Patcher ist fertig, aber {0} Fehler sind aufgetreten! Der Mod wurde wahrscheinlich nicht korrekt installiert.",
        "PatcherFinishedWithErrorsAndWarnings": "Der Patcher ist fertig, aber {0} Fehler und {1} Warnungen sind aufgetreten! Der Mod wurde wahrscheinlich nicht korrekt installiert.",
        "StrRefTokenNotInTLK": 'StrRef-Token "{0}" in der Modifierliste war im TLK nicht vorhanden.',
        "NoNewEntriesAppendedToTlk": "Warnung: Keine neuen Einträge zu {0} angehängt. Möglicherweise fehlen Einträge in append.tlk.",
        "NoTLKFileLoaded": "Keine TLK-Datei geladen. Fortsetzung nicht möglich.",
        "UnableToLocateTLKFileToPatch": 'Fehler! TLK-Datei zum Patchen nicht gefunden, Datei "{0}" nicht gefunden!',
        "UnableToFind2DAFileToModify": '2DA-Datei "{0}" zum Ändern nicht gefunden! Datei wird übersprungen...',
        "ErrorLookingUpRowLabelForRowIndex": "Fehler beim Nachschlagen der Zeilenbezeichnung für Zeilenindex {0}.",
        "ErrorLookingUpColumnLabelForColumnIndex": "Fehler beim Nachschlagen der Spaltenbezeichnung für Spaltenindex {0}.",
        "UsedAsIndexBut2DAHasNoLabel": '{0} als Index beim Zeilenwechsel in Modifier "{1}" verwendet, aber 2DA hat keine Bezeichnung für diesen Index.',
        "FailedToCopyLine2DA": "Fehler! Zeile in 2DA konnte nicht kopiert werden! Überspringe...",
        "UnableToLoad2DAFileSkipping": "2DA-Datei {0} konnte nicht geladen werden! Überspringe...",
        "NoValueAssignedColumn2DA": 'Kein Wert für Spalte {0} bei neuer 2DA-Zeile in Modifier "{1}" zugewiesen...',
        "ErrorAddingNewLine2DA": 'Fehler beim Hinzufügen einer neuen Zeile zur 2DA in Modifier "{0}"!',
        "InternalErrorInvalidTLKFileType": "Interner Fehler, ungültiger TLK-Dateityp angegeben.",
        "CriticalErrorUnableToLocateFileToPatch": 'Kritischer Fehler: Datei zum Patchen nicht gefunden, Datei "{0}" nicht gefunden!',
        "NoFileToInstallSpecified": "Fehler! Keine zu installierende Datei angegeben!",
        "NoInstallPathSet": "Fehler! Kein Installationspfad festgelegt!",
        "FileSetToPatchDoesNotExist": 'Fehler! Datei "{0}" zum Patchen existiert nicht!',
        "UnableToLoadInstructionsTslpatchdata": 'Anweisungstext konnte nicht geladen werden! Der Ordner "tslpatchdata" muss die Datei "info.rtf" enthalten.',
        "SectionNotFoundError": "Abschnitt [{0}] wurde in der INI nicht gefunden",
        "ReferencesTracebackMsg": ", referenziert von '{0}={1}' in [{2}]",
        "ErrorParsingIniFile": "Fehler beim Analysieren der INI-Datei: {0}",
        "IniFileNotFound": "INI-Datei nicht gefunden: {0}",
        "IniTextCannotBeNullOrEmpty": "INI-Text darf nicht null oder leer sein",
        "LanguageIntegerNotKnown": "Unbekannte Sprach-ID: {0}",
        "NoEncodingDefinedForLanguage": "Keine Kodierung für Sprache definiert: {0}",
        "FilePatcherDescription": "2DA/TLK/GFF/NSS/SSF/ERF/RIM-Datei-Patcher für KotOR/TSL.",
        "NoLineSetToBeModifiedFormat": "Keine Zeile zum Ändern in [{0}] festgelegt.",
        "OrphanedIniSectionsFormat": "Es wurden verwaiste INI-Abschnitte in den Änderungen gefunden:\n{0}",
        # Install log
        "InstallationLogHeader": "KPatcher Installationsprotokoll",
        "InstallationLogHeaderSeparator": "===========================",
        "InstallationDate": "Installationsdatum: {0}",
        "ModPath": "Mod-Pfad: {0}",
        "GamePath": "Spielpfad: {0}",
        "GameDetected": "Spiel erkannt: {0}",
        "FileOperationFormat": "{0}: {1} -> {2}",
        "FileOperationErrorFormat": "Fehler beim {0} von {1} nach {2}",
        "FileOperationErrorWithMessageFormat": "Fehler beim {0} von {1} nach {2}: {3}",
        "PatchOperationFormat": "Patchen von {0}: {1} - {2}",
        # ModInstaller
        "CouldNotFindChangesIniFile": "Die changes.ini-Datei konnte auf der Festplatte nicht gefunden werden.",
        "CouldNotCreateInstallLogFile": "Installationsprotokolldatei konnte nicht erstellt werden: {0}",
        "ChangesConfigFileNotFound": "Changes-Konfigurationsdatei nicht gefunden: {0}",
        "CouldNotDetermineEncoding": "Kodierung von '{0}' konnte nicht bestimmt werden. Versuche erzwungenes Laden...",
        "CouldNotWriteEquivalentYaml": "Äquivalentes YAML konnte nicht geschrieben werden: {0}",
        "CouldNotInitializeUninstallDirectory": "Deinstallationsverzeichnis konnte nicht initialisiert werden: {0}",
        "CouldNotCreateBackupFolder": "Backup-Ordner konnte nicht erstellt werden: {0}",
        "UsingBackupDirectory": "Verwende Backup-Verzeichnis: '{0}'",
        "InvalidKotorDirectory": "Gewähltes KOTOR-Verzeichnis ist keine gültige Installation - ModInstaller kann nicht initialisiert werden.",
        "StartingInstallation": "Installation wird gestartet...",
        "LoadingConfigurationFrom": "Lade Konfiguration von {0}",
        "FoundPatchesToApply": "{0} Patches zum Anwenden gefunden",
        "InstallationTerminationRequest": "ModInstaller.Install() hat Abbruchanforderung erhalten, wird abgebrochen...",
        "ProcessingInstallListEntries": "Verarbeite InstallList-Einträge...",
        "ProcessingTlkPatches": "Verarbeite TLK-Patches...",
        "Processing2DAPatches": "Verarbeite 2DA-Patches...",
        "ProcessingGffPatches": "Verarbeite GFF-Patches...",
        "ProcessingNssScriptPatches": "Verarbeite NSS-Skript-Patches...",
        "ProcessingNcsScriptPatches": "Verarbeite NCS-Skript-Patches...",
        "ProcessingSsfSoundPatches": "Verarbeite SSF-Sound-Patches...",
        "FileHasNoContent": "'{0}' hat keinen Inhalt/Daten und ist vollständig leer.",
        "SkippingFilePatchResource": "Überspringe '{0}' - patch_resource hat bestimmt, dass diese Datei übersprungen werden kann.",
        "CleaningTemporaryScriptFolder": "Bereinige temporären Skript-Ordner bei '{0}' (Hinweis: Verwenden Sie 'SaveProcessedScripts=1' in [Settings], um diese Skripte zu behalten)",
        "SuccessfullyCompletedFormat": "Erfolgreich abgeschlossen {0} {1}.",
        "InstallationCompletedSuccessfully": "Installation erfolgreich abgeschlossen",
        "InstallationFailedFormat": "Installation fehlgeschlagen: {0}",
        "PatchingRimFileWarning": "Dieser Mod patcht die RIM-Datei Modules/{0}!\nDas Patchen von RIMs ist sehr inkompatibel, nicht empfohlen und allgemein als schlechte Praxis angesehen. Bitte fordern Sie den Mod-Entwickler auf, dies zu beheben.",
        "ModuleDidNotExistBuilding": "WICHTIG! Das Modul im Pfad '{0}' existierte nicht, erstelle eines im 'Modules'-Ordner sofort aus den folgenden Dateien:",
        "FailedToBuildModule": "Fehler beim Erstellen des Moduls '{0}': {1}",
        "CapsuleNotFoundOrPermission": "Die Kapsel '{0}' existierte nicht oder es traten Berechtigungsprobleme auf beim Versuch, '{2}' zu {1}. Überspringe Datei...",
        "BackingUpFile": "Erstelle Backup von '{0}'...",
        "FailedToCreateBackup": "Fehler beim Erstellen des Backups von '{0}': {1}",
        "CouldNotLoadSourceFileMissing": "Quelldatei konnte nicht geladen werden für {0}: SourceFile fehlt oder ist leer (korrigieren oder entfernen Sie diese InstallList / Patch-Zeile in changes.ini).",
        "CouldNotLoadFileSaveAsMissing": "Datei konnte nicht geladen werden für {0}: SaveAs fehlt oder ist leer.",
        "CouldNotLoadResourceFromCapsule": "Ressource konnte nicht aus der Kapsel geladen werden für {0}: SaveAs fehlt oder ist leer.",
        "CouldNotLoadSourceFileFormat": "Quelldatei konnte nicht geladen werden für {0}:{1}{2}",
        "CapsuleNotFoundWhenAttempting": "Die Kapsel '{0}' existierte nicht beim Versuch, '{2}' zu {1}. Überspringe Datei...",
        "RenamedExistingOverrideFile": "Vorhandene Override-Datei '{0}' wurde zu '{1}' umbenannt, um Schattenbildung zu verhindern.",
        "CouldNotRenameInOverrideFolder": "Datei '{0}' konnte nicht zu '{1}' im Override-Ordner umbenannt werden: {2}",
        "ResourceShadowingModChanges": "Eine Ressource an '{0}' überschattet die Änderungen dieses Mods in {1}!",
        "ModOvershadowedByExisting": "Dieser Mod möchte '{0}' in '{1}' installieren, wird aber von der vorhandenen '{2}' überschattet!",
        # ConfigReader
        "ConfigReaderFinishedLoadingIni": "Der ConfigReader hat das Laden der INI abgeschlossen",
        "SettingsSectionMissing": "Abschnitt [Settings] fehlt in der ini.",
        "LoadingSettingsSection": "Lade Abschnitt [Settings] aus der ini...",
        "InstallListSectionMissing": "Abschnitt [InstallList] fehlt in der ini.",
        "LoadingInstallListPatches": "Lade [InstallList]-Patches aus der ini...",
        "SkippingEmptyInstallListEntry": "Überspringe leeren InstallList-Eintrag (leere Zeile oder leerer Schlüssel im Abschnitt [InstallList] von changes.ini).",
        "TlkListSectionMissing": "Abschnitt [TLKList] fehlt in der ini.",
        "LoadingTlkListPatches": "Lade [TLKList]-Patches aus der ini...",
        "TwoDAListSectionMissing": "Abschnitt [2DAList] fehlt in der ini.",
        "LoadingTwoDAListPatches": "Lade [2DAList]-Patches aus der ini...",
        "SsfListSectionMissing": "Abschnitt [SSFList] fehlt in der ini.",
        "LoadingSsfListPatches": "Lade [SSFList]-Patches aus der ini...",
        "GffListSectionMissing": "Abschnitt [GFFList] fehlt in der ini.",
        "LoadingGffListPatches": "Lade [GFFList]-Patches aus der ini...",
        "CompileListSectionMissing": "Abschnitt [CompileList] fehlt in der ini.",
        "LoadingCompileListPatches": "Lade [CompileList]-Patches aus der ini...",
        "HackListSectionMissing": "Abschnitt [HACKList] fehlt in der ini.",
        "LoadingHackListPatches": "Lade [HACKList]-Patches aus der ini...",
        # CLI
        "CliErrorNoModPath": "[Fehler] Kein Mod-Pfad angegeben. Verwenden Sie --tslpatchdata <Pfad>",
        "CliErrorFailedToLoadMod": "[Fehler] Fehler beim Laden des Mods: {0}",
        "CliErrorNamespaceIndexOutOfRange": "[Fehler] Namespace-Index {0} außerhalb des Bereichs (max: {1})",
        "CliErrorNoGameDirectory": "[Fehler] Kein Spielverzeichnis angegeben. Verwenden Sie --game-dir <Pfad>",
        "CliErrorInvalidGameDirectory": "[Fehler] Ungültiges Spielverzeichnis: {0}: {1}",
        "CliErrorInvalidModOrGamePaths": "[Fehler] Ungültige Mod- oder Spielpfade",
        "CliErrorCannotRunMultipleOperations": "[Fehler] Es kann nicht mehr als eine von [--install, --uninstall, --validate] ausgeführt werden",
        "CliErrorMustSpecifyOperation": "[Fehler] Eine von [--install, --uninstall, --validate] muss für den CLI-Modus angegeben werden",
        "CliInfoInstallingMod": "[Info] Installiere Mod von {0} nach {1}",
        "CliInfoInstallCompleted": "[Info] Installation abgeschlossen: {0} Fehler, {1} Warnungen, {2} Patches",
        "CliInfoInstallTime": "[Info] Installationszeit: {0}",
        "CliInfoUninstallingMod": "[Info] Deinstalliere Mod von {0}",
        "CliInfoUseHelpForOptions": "[Info] Verwenden Sie --help, um CLI-Optionen anzuzeigen",
        "CliWarningDisplayDriverNotAvailable": "[Warnung] Anzeigetreiber nicht verfügbar, GUI-Modus nicht möglich: {0}",
        "CliInfoUninstallCompletedSuccessfully": "[Info] Deinstallation erfolgreich abgeschlossen",
        "CliWarningUninstallCompletedWithWarnings": "[Warnung] Deinstallation mit Warnungen abgeschlossen",
        "CliInfoValidatingMod": "[Info] Validiere Mod-Konfiguration",
        "CliInfoValidationCompletedSuccessfully": "[Info] Validierung erfolgreich abgeschlossen",
        "CliErrorFormat": "[Fehler] {0}: {1}",
        "CliInnerException": "Interne Ausnahme: {0}",
        # ErrorHandling
        "UnknownException": "Unbekannte Ausnahme",
        "CouldNotFindFile": "Datei konnte nicht gefunden werden: '{0}'",
        "CouldNotFindDirectory": "Verzeichnis konnte nicht gefunden werden: '{0}'",
        "PermissionDenied": "Zugriff verweigert: {0}",
        "OperationTimedOut": "Vorgang hat Zeitüberschreitung: {0}",
        "OperationWasCancelled": "Vorgang wurde abgebrochen: {0}",
        "IOError": "E/A-Fehler: {0}",
        "ExceptionInformationHeader": "  Informationen:",
        # ModUninstaller
        "RemovedFormat": "Entfernt {0}...",
        "RestoringBackupOf": "Stelle Backup von '{0}' nach '{1}' wieder her...",
        "UsingBackupFolder": "Verwende Backup-Ordner '{0}'",
        "WouldRestoreFile": "Würde Datei '{0}' wiederherstellen",
        "DeletedRestoredBackup": "Wiederhergestelltes Backup '{0}' gelöscht",
        # GFF/Interpreter/CodeRoot (technical)
        "ExpectedGffStructButGot": "GFFStruct erwartet, aber {0} erhalten",
        "DoesNotExist": "Existiert nicht",
        "PathPointsToExpectedGffList": "Pfad zeigt auf ein '{0}', GFFList erwartet.",
        "UnableToAddStructToList": "Struct konnte nicht zur Liste '{0}' hinzugefügt werden: {1}",
        "IniSectionThrewException": "INI-Abschnitt [{0}] hat eine Ausnahme ausgelöst: {1}",
        "FailedToAddNewStructToList": "Fehler beim Hinzufügen eines neuen Structs zur Liste '{0}' in [{1}]. Grund: GFFStruct erwartet, aber '{2}' ({3}) vom Typ {4} erhalten. Überspringe...",
        "Set2DAMemory": "Setze 2DAMEMORY{0}={1}",
        "UnexpectedModifierType": "Unerwarteter Modifikatortyp: {0}: {1}",
        "ResolvedGffListPath": "GFFList-Pfad von [{0}] von '{1}' --> '{2}' aufgelöst",
        "ApplyPatchFromIniSection": "Wende Patch aus INI-Abschnitt [{0}] an FieldType: {1} GFF-Pfad: '{2}'",
        "UnableToAddNewGffField": "Neues GFF-Feld '{0}' konnte am GFF-Pfad '{1}' nicht hinzugefügt werden! Dies {2}",
        "InstructionJumpsToNotInList": "Anweisung #{0} ({1}) springt zu einer Anweisung, die nicht in der Liste ist. Sprungziel-Hash: {2}",
        "InstructionLimitExceeded": "Anweisungslimit überschritten: {0} Anweisungen ausgeführt",
        "InfiniteLoopDetectedExecuted": "Endlosschleife erkannt: Anweisung am Index {0} ({1}) wurde {2} Mal ausgeführt",
        "JumpInstructionNoTarget": "Sprunganweisung {0} am Index {1} hat kein Sprungziel",
        "JumpTargetNotFound": "Sprungziel für Anweisung {0} nicht in der Anweisungstabelle gefunden",
        "InfiniteLoopJumpsToItself": "Endlosschleife erkannt: {0} am Index {1} springt zu sich selbst",
        "CannotAdvanceSameInstruction": "Kann nicht vorrücken: nächste Anweisung am Index {0} ist dieselbe wie die aktuelle am Index {1}",
        "InstructionNotPresentInTable": "Anweisung nicht in der aktuellen Anweisungstabelle vorhanden",
        "InstructionNotImplemented": "Anweisung {0} nicht implementiert",
        "StoreStateCannotAccessInstruction": "STORE_STATE am Index {0}: kann nicht auf Anweisung am Index {1} zugreifen",
        "StoreStateReachedEndWithoutRetn": "STORE_STATE am Index {0}: Ende der Anweisungen erreicht ohne RETN zu finden",
        "ActionInstructionRequiresTwoArgs": "ACTION-Anweisung erfordert mindestens 2 Argumente",
        "ActionIdOutOfRange": "Aktions-ID {0} ist außerhalb des Bereichs (0-{1})",
        "StackUnderflowPoppingVector": "Stack-Unterlauf beim Entfernen des Vektors für '{0}'",
        "StackUnderflowPoppingArgument": "Stack-Unterlauf beim Entfernen des Arguments für '{0}'",
        "FileHasNoEntryPoint": "Diese Datei hat keinen Einstiegspunkt und kann nicht kompiliert werden (Wahrscheinlich eine Include-Datei).",
        "InvalidNssSourceProvided": "Ungültige nss-Quelle an ModificationsNSS.PatchResource() übergeben",
        "BuiltInCompilationFailedFormat": "Integrierte Kompilierung für '{0}' fehlgeschlagen: {1}",
        "CouldNotCompileReturningUncompiledFormat": "Konnte '{0}' nicht kompilieren. Gebe unkompilierte NSS-Quelle zurück.",
        "ExpectedMutableStringButGotFormat": "Erwartete MutableString für ModificationsNSS, aber {0} erhalten",
        "PatchingFromUnixCompilingFormat": "Patchen von einem Unix-Betriebssystem, kompiliere '{0}' mit den integrierten Compilern...",
        "ExpectedByteArrayButGotFormat": "Erwartete byte[] für ModificationsNCS, aber {0} erhalten",
        "GffPathNotFoundDefaultingToRootFormat": "GFF-Pfad '{0}' nicht gefunden, verwende standardmäßig die GFF-Root-Struktur.",
        "UnableToModifyGffFieldFormat": "GFF-Feld '{0}' konnte nicht geändert werden. Pfad '{1}' {2}",
        "PathDoesNotExist": "existiert nicht!",
        "PathIsNotGffStructInstance": "ist keine Instanz eines GFFStruct.",
        "ExpectedGffObjectButGotFormat": "Erwartete GFF-Objekt für ModificationsGFF, aber {0} erhalten",
        "ErrorOccurredWhileCompilingTryingExternalFormat": "Fehler beim Kompilieren von '{0}' mit dem integrierten Compiler, versuche externen Compiler...",
        "ExpectedSsfObjectButGotFormat": "Erwartete SSF-Objekt für ModificationsSSF, aber {0} erhalten",
        "UnableToUseFieldPathFrom2DAMemoryFormat": "Kann !FieldPath von 2DAMEMORY nicht verwenden. Übergeordnetes Feld bei '{0}' {1}",
        "ExpectedLocalizedStringButGotFormat": "Erwartete LocalizedString, aber {0} erhalten",
        "ExpectedLocalizedStringDeltaButGotFormat": "Erwartete LocalizedStringDelta für vorhandenes Feld, aber {0} erhalten",
        "ExpectedTlkObjectButGotFormat": "Erwartete TLK-Objekt für ModificationsTLK, aber {0} erhalten",
        "ManagedCompilationFailedFormat": "Verwaltete Kompilierung für '{0}' fehlgeschlagen: {1}",
        "CompiledUsingExternalNwnnsscompFormat": "Kompiliert '{0}' mit externem nwnnsscomp.exe (verwaltete Kompilierung fehlgeschlagen).",
        "ExternalNwnnsscompAlsoFailedFormat": "Externer nwnnsscomp schlug auch für '{0}' fehl: {1}",
        "NwnnsscompNotExpectedVersionFormat": "Die nwnnsscomp.exe ist nicht die erwartete KPatcher-Version (erkannt: {0}).",
        "ExpectedTwoDAObjectButGotFormat": "Erwartete TwoDA-Objekt für Modifications2DA, aber {0} erhalten",
    },
    "fr": {
        "StartPatchingButton": "&Démarrer le patch",
        "StartPatchingConfirmation": "Cela lancera le patch des fichiers du jeu nécessaires. Voulez-vous continuer ?",
        "InvalidGameFolderDialogTlkNotFound": "Dossier de jeu invalide, fichier dialog.tlk introuvable ! Sélectionnez le bon répertoire du jeu.",
        "NoValidGameFolderSelected": "Erreur ! Aucun dossier de jeu valide sélectionné ! Installation annulée.",
        "SkippingFileNoOverwriteDialogTlk": "Fichier {0} ignoré : ce programme n’écrase pas dialog.tlk directement.",
        "NwnnsscompNotFoundInTslPatchData": "Impossible de trouver nwnnsscomp.exe dans le dossier TSLPatchData ! Impossible de compiler le script.",
        "Invalid2DAMemoryToken": "Jeton 2DAMEMORY invalide ! Les index commencent à 1.",
        "PatcherFinished": "Le patcher a terminé. Consultez le journal de progression pour les détails.",
        "PatcherFinishedWithWarnings": "Le patcher a terminé, mais {0} avertissements ! Le mod peut ne pas fonctionner correctement.",
        "PatcherFinishedWithErrors": "Le patcher a terminé, mais {0} erreurs ! Le mod n’a probablement pas été installé correctement.",
        "PatcherFinishedWithErrorsAndWarnings": "Le patcher a terminé, mais {0} erreurs et {1} avertissements ! Le mod n’a probablement pas été installé correctement.",
        "StrRefTokenNotInTLK": "Jeton StrRef « {0} » dans la liste des modificateurs absent du TLK.",
        "NoNewEntriesAppendedToTlk": "Avertissement : aucune nouvelle entrée ajoutée à {0}. Entrées manquantes possibles dans append.tlk.",
        "NoTLKFileLoaded": "Aucun fichier TLK chargé. Impossible de continuer.",
        "UnableToLocateTLKFileToPatch": "Erreur ! Impossible de localiser le fichier TLK à patcher, fichier « {0} » introuvable !",
        "UnableToFind2DAFileToModify": "Fichier 2DA « {0} » introuvable pour modification ! Fichier ignoré...",
        "ErrorLookingUpRowLabelForRowIndex": "Erreur lors de la recherche de l’étiquette de ligne pour l’index {0}.",
        "ErrorLookingUpColumnLabelForColumnIndex": "Erreur lors de la recherche de l’étiquette de colonne pour l’index {0}.",
        "UsedAsIndexBut2DAHasNoLabel": "{0} utilisé comme index lors du changement de ligne dans le modificateur « {1} », mais le fichier 2DA n’a pas d’étiquette pour cet index.",
        "FailedToCopyLine2DA": "Erreur ! Échec de la copie de ligne dans la 2DA ! Ignoré...",
        "UnableToLoad2DAFileSkipping": "Impossible de charger le fichier 2DA {0} ! Ignoré...",
        "NoValueAssignedColumn2DA": "Aucune valeur assignée à la colonne {0} pour la nouvelle ligne 2DA dans le modificateur « {1} »...",
        "ErrorAddingNewLine2DA": "Erreur lors de l’ajout d’une nouvelle ligne 2DA dans le modificateur « {0} » !",
        "InternalErrorInvalidTLKFileType": "Erreur interne, type de fichier TLK invalide.",
        "CriticalErrorUnableToLocateFileToPatch": "Erreur critique : impossible de localiser le fichier à patcher, « {0} » introuvable !",
        "NoFileToInstallSpecified": "Erreur ! Aucun fichier à installer spécifié !",
        "NoInstallPathSet": "Erreur ! Aucun chemin d’installation défini !",
        "FileSetToPatchDoesNotExist": "Erreur ! Le fichier « {0} » à patcher n’existe pas !",
        "UnableToLoadInstructionsTslpatchdata": "Impossible de charger les instructions ! Le dossier « tslpatchdata » doit contenir « info.rtf ».",
        "SectionNotFoundError": "La section [{0}] est introuvable dans l’INI",
        "ReferencesTracebackMsg": ", référencé par « {0}={1} » dans [{2}]",
        "ErrorParsingIniFile": "Erreur d’analyse du fichier INI : {0}",
        "IniFileNotFound": "Fichier INI introuvable : {0}",
        "IniTextCannotBeNullOrEmpty": "Le texte INI ne peut pas être null ou vide",
        "LanguageIntegerNotKnown": "Identifiant de langue inconnu : {0}",
        "NoEncodingDefinedForLanguage": "Aucun encodage défini pour la langue : {0}",
        "FilePatcherDescription": "Correcteur de fichiers 2DA/TLK/GFF/NSS/SSF/ERF/RIM pour KotOR/TSL.",
        "NoLineSetToBeModifiedFormat": "Aucune ligne définie à modifier dans [{0}].",
        "OrphanedIniSectionsFormat": "Des sections INI orphelines ont été trouvées dans les modifications :\n{0}",
        # Install log
        "InstallationLogHeader": "Journal d'installation KPatcher",
        "InstallationLogHeaderSeparator": "===========================",
        "InstallationDate": "Date d'installation : {0}",
        "ModPath": "Chemin du mod : {0}",
        "GamePath": "Chemin du jeu : {0}",
        "GameDetected": "Jeu détecté : {0}",
        "FileOperationFormat": "{0} : {1} -> {2}",
        "FileOperationErrorFormat": "Échec du {0} de {1} vers {2}",
        "FileOperationErrorWithMessageFormat": "Échec du {0} de {1} vers {2} : {3}",
        "PatchOperationFormat": "Application du patch {0} : {1} - {2}",
        # ModInstaller
        "CouldNotFindChangesIniFile": "Impossible de trouver le fichier changes.ini sur le disque.",
        "CouldNotCreateInstallLogFile": "Impossible de créer le fichier de journal d'installation : {0}",
        "ChangesConfigFileNotFound": "Fichier de configuration changes introuvable : {0}",
        "CouldNotDetermineEncoding": "Impossible de déterminer l'encodage de '{0}'. Tentative de chargement forcé...",
        "CouldNotWriteEquivalentYaml": "Impossible d'écrire le YAML équivalent : {0}",
        "CouldNotInitializeUninstallDirectory": "Impossible d'initialiser le répertoire de désinstallation : {0}",
        "CouldNotCreateBackupFolder": "Impossible de créer le dossier de sauvegarde : {0}",
        "UsingBackupDirectory": "Utilisation du répertoire de sauvegarde : '{0}'",
        "InvalidKotorDirectory": "Le répertoire KOTOR choisi n'est pas une installation valide - impossible d'initialiser ModInstaller.",
        "StartingInstallation": "Démarrage de l'installation...",
        "LoadingConfigurationFrom": "Chargement de la configuration depuis {0}",
        "FoundPatchesToApply": "{0} correctifs trouvés à appliquer",
        "InstallationTerminationRequest": "ModInstaller.Install() a reçu une demande d'arrêt, annulation...",
        "ProcessingInstallListEntries": "Traitement des entrées InstallList...",
        "ProcessingTlkPatches": "Traitement des correctifs TLK...",
        "Processing2DAPatches": "Traitement des correctifs 2DA...",
        "ProcessingGffPatches": "Traitement des correctifs GFF...",
        "ProcessingNssScriptPatches": "Traitement des correctifs de scripts NSS...",
        "ProcessingNcsScriptPatches": "Traitement des correctifs de scripts NCS...",
        "ProcessingSsfSoundPatches": "Traitement des correctifs sonores SSF...",
        "FileHasNoContent": "'{0}' n'a pas de contenu/données et est complètement vide.",
        "SkippingFilePatchResource": "Ignorer '{0}' - patch_resource a déterminé que ce fichier peut être ignoré.",
        "CleaningTemporaryScriptFolder": "Nettoyage du dossier de scripts temporaire à '{0}' (astuce : utilisez 'SaveProcessedScripts=1' dans [Settings] pour conserver ces scripts)",
        "SuccessfullyCompletedFormat": "Terminé avec succès {0} {1}.",
        "InstallationCompletedSuccessfully": "Installation terminée avec succès",
        "InstallationFailedFormat": "Échec de l'installation : {0}",
        "PatchingRimFileWarning": "Ce mod applique un correctif au fichier RIM Modules/{0} !\nL'application de correctifs aux RIM est très incompatible, non recommandée et largement considérée comme une mauvaise pratique. Veuillez demander au développeur du mod de corriger cela.",
        "ModuleDidNotExistBuilding": "IMPORTANT ! Le module au chemin '{0}' n'existait pas, création d'un dans le dossier 'Modules' immédiatement à partir des fichiers suivants :",
        "FailedToBuildModule": "Échec de la construction du module '{0}' : {1}",
        "CapsuleNotFoundOrPermission": "La capsule '{0}' n'existait pas, ou des problèmes d'autorisation se sont produits, lors de la tentative de {1} '{2}'. Fichier ignoré...",
        "BackingUpFile": "Sauvegarde de '{0}'...",
        "FailedToCreateBackup": "Échec de la création de la sauvegarde de '{0}' : {1}",
        "CouldNotLoadSourceFileMissing": "Impossible de charger le fichier source pour {0} : SourceFile est manquant ou vide (corrigez ou supprimez cette ligne InstallList / patch dans changes.ini).",
        "CouldNotLoadFileSaveAsMissing": "Impossible de charger le fichier pour {0} : SaveAs est manquant ou vide.",
        "CouldNotLoadResourceFromCapsule": "Impossible de charger la ressource de la capsule pour {0} : SaveAs est manquant ou vide.",
        "CouldNotLoadSourceFileFormat": "Impossible de charger le fichier source pour {0} :{1}{2}",
        "CapsuleNotFoundWhenAttempting": "La capsule '{0}' n'existait pas lors de la tentative de {1} '{2}'. Fichier ignoré...",
        "RenamedExistingOverrideFile": "Fichier Override existant '{0}' renommé en '{1}' pour éviter l'ombrage.",
        "CouldNotRenameInOverrideFolder": "Impossible de renommer '{0}' en '{1}' dans le dossier Override : {2}",
        "ResourceShadowingModChanges": "Une ressource située à '{0}' masque les modifications de ce mod dans {1} !",
        "ModOvershadowedByExisting": "Ce mod a l'intention d'installer '{0}' dans '{1}', mais est masqué par '{2}' existant !",
        # ConfigReader
        "ConfigReaderFinishedLoadingIni": "Le ConfigReader a terminé le chargement de l'INI",
        "SettingsSectionMissing": "Section [Settings] manquante dans l'ini.",
        "LoadingSettingsSection": "Chargement de la section [Settings] depuis l'ini...",
        "InstallListSectionMissing": "Section [InstallList] manquante dans l'ini.",
        "LoadingInstallListPatches": "Chargement des correctifs [InstallList] depuis l'ini...",
        "SkippingEmptyInstallListEntry": "Ignorer l'entrée InstallList vide (ligne vide ou clé vide dans la section [InstallList] de changes.ini).",
        "TlkListSectionMissing": "Section [TLKList] manquante dans l'ini.",
        "LoadingTlkListPatches": "Chargement des correctifs [TLKList] depuis l'ini...",
        "TwoDAListSectionMissing": "Section [2DAList] manquante dans l'ini.",
        "LoadingTwoDAListPatches": "Chargement des correctifs [2DAList] depuis l'ini...",
        "SsfListSectionMissing": "Section [SSFList] manquante dans l'ini.",
        "LoadingSsfListPatches": "Chargement des correctifs [SSFList] depuis l'ini...",
        "GffListSectionMissing": "Section [GFFList] manquante dans l'ini.",
        "LoadingGffListPatches": "Chargement des correctifs [GFFList] depuis l'ini...",
        "CompileListSectionMissing": "Section [CompileList] manquante dans l'ini.",
        "LoadingCompileListPatches": "Chargement des correctifs [CompileList] depuis l'ini...",
        "HackListSectionMissing": "Section [HACKList] manquante dans l'ini.",
        "LoadingHackListPatches": "Chargement des correctifs [HACKList] depuis l'ini...",
        # CLI
        "CliErrorNoModPath": "[Erreur] Aucun chemin de mod spécifié. Utilisez --tslpatchdata <chemin>",
        "CliErrorFailedToLoadMod": "[Erreur] Échec du chargement du mod : {0}",
        "CliErrorNamespaceIndexOutOfRange": "[Erreur] Index de namespace {0} hors limites (max : {1})",
        "CliErrorNoGameDirectory": "[Erreur] Aucun répertoire de jeu spécifié. Utilisez --game-dir <chemin>",
        "CliErrorInvalidGameDirectory": "[Erreur] Répertoire de jeu invalide : {0} : {1}",
        "CliErrorInvalidModOrGamePaths": "[Erreur] Chemins de mod ou de jeu invalides",
        "CliErrorCannotRunMultipleOperations": "[Erreur] Impossible d'exécuter plus d'une opération parmi [--install, --uninstall, --validate]",
        "CliErrorMustSpecifyOperation": "[Erreur] Vous devez spécifier une opération parmi [--install, --uninstall, --validate] pour le mode CLI",
        "CliInfoInstallingMod": "[Info] Installation du mod depuis {0} vers {1}",
        "CliInfoInstallCompleted": "[Info] Installation terminée : {0} erreurs, {1} avertissements, {2} correctifs",
        "CliInfoInstallTime": "[Info] Temps d'installation : {0}",
        "CliInfoUninstallingMod": "[Info] Désinstallation du mod depuis {0}",
        "CliInfoUseHelpForOptions": "[Info] Utilisez --help pour voir les options CLI",
        "CliWarningDisplayDriverNotAvailable": "[Avertissement] Pilote d'affichage non disponible, impossible d'exécuter en mode GUI : {0}",
        "CliInfoUninstallCompletedSuccessfully": "[Info] Désinstallation terminée avec succès",
        "CliWarningUninstallCompletedWithWarnings": "[Avertissement] Désinstallation terminée avec des avertissements",
        "CliInfoValidatingMod": "[Info] Validation de la configuration du mod",
        "CliInfoValidationCompletedSuccessfully": "[Info] Validation terminée avec succès",
        "CliErrorFormat": "[Erreur] {0} : {1}",
        "CliInnerException": "Exception interne : {0}",
        # ErrorHandling
        "UnknownException": "Exception inconnue",
        "CouldNotFindFile": "Impossible de trouver le fichier : '{0}'",
        "CouldNotFindDirectory": "Impossible de trouver le répertoire : '{0}'",
        "PermissionDenied": "Permission refusée : {0}",
        "OperationTimedOut": "Opération expirée : {0}",
        "OperationWasCancelled": "Opération annulée : {0}",
        "IOError": "Erreur E/S : {0}",
        "ExceptionInformationHeader": "  Informations :",
        # ModUninstaller
        "RemovedFormat": "Supprimé {0}...",
        "RestoringBackupOf": "Restauration de la sauvegarde de '{0}' vers '{1}'...",
        "UsingBackupFolder": "Utilisation du dossier de sauvegarde '{0}'",
        "WouldRestoreFile": "Restauration du fichier '{0}'",
        "DeletedRestoredBackup": "Sauvegarde restaurée '{0}' supprimée",
        # GFF/Interpreter/CodeRoot (technical)
        "ExpectedGffStructButGot": "GFFStruct attendu mais {0} obtenu",
        "DoesNotExist": "N'existe pas",
        "PathPointsToExpectedGffList": "Le chemin pointe vers un '{0}', un GFFList est attendu.",
        "UnableToAddStructToList": "Impossible d'ajouter le struct à la liste '{0}' : {1}",
        "IniSectionThrewException": "La section INI [{0}] a levé une exception : {1}",
        "FailedToAddNewStructToList": "Échec de l'ajout d'un nouveau struct à la liste '{0}' dans [{1}]. Raison : GFFStruct attendu mais '{2}' ({3}) de type {4} obtenu. Ignoré...",
        "Set2DAMemory": "Définir 2DAMEMORY{0}={1}",
        "UnexpectedModifierType": "Type de modificateur inattendu : {0} : {1}",
        "ResolvedGffListPath": "Chemin GFFList de [{0}] résolu depuis '{1}' --> '{2}'",
        "ApplyPatchFromIniSection": "Appliquer le correctif depuis la section INI [{0}] FieldType : {1} Chemin GFF : '{2}'",
        "UnableToAddNewGffField": "Impossible d'ajouter le nouveau champ GFF '{0}' au chemin GFF '{1}' ! Ceci {2}",
        "InstructionJumpsToNotInList": "L'instruction #{0} ({1}) saute vers une instruction qui n'est pas dans la liste. Hash de la cible de saut : {2}",
        "InstructionLimitExceeded": "Limite d'instructions dépassée : {0} instructions exécutées",
        "InfiniteLoopDetectedExecuted": "Boucle infinie détectée : l'instruction à l'index {0} ({1}) a été exécutée {2} fois",
        "JumpInstructionNoTarget": "L'instruction de saut {0} à l'index {1} n'a pas de cible de saut",
        "JumpTargetNotFound": "Cible de saut pour l'instruction {0} introuvable dans la table d'instructions",
        "InfiniteLoopJumpsToItself": "Boucle infinie détectée : {0} à l'index {1} saute vers lui-même",
        "CannotAdvanceSameInstruction": "Impossible d'avancer : l'instruction suivante à l'index {0} est la même que l'actuelle à l'index {1}",
        "InstructionNotPresentInTable": "Instruction absente de la table d'instructions actuelle",
        "InstructionNotImplemented": "Instruction {0} non implémentée",
        "StoreStateCannotAccessInstruction": "STORE_STATE à l'index {0} : impossible d'accéder à l'instruction à l'index {1}",
        "StoreStateReachedEndWithoutRetn": "STORE_STATE à l'index {0} : fin des instructions atteinte sans trouver RETN",
        "ActionInstructionRequiresTwoArgs": "L'instruction ACTION nécessite au moins 2 arguments",
        "ActionIdOutOfRange": "L'ID d'action {0} est hors limites (0-{1})",
        "StackUnderflowPoppingVector": "Débordement de pile lors de l'extraction du vecteur pour '{0}'",
        "StackUnderflowPoppingArgument": "Débordement de pile lors de l'extraction de l'argument pour '{0}'",
        "FileHasNoEntryPoint": "Ce fichier n'a pas de point d'entrée et ne peut pas être compilé (Probablement un fichier include).",
        "InvalidNssSourceProvided": "Source nss invalide fournie à ModificationsNSS.PatchResource()",
        "BuiltInCompilationFailedFormat": "La compilation intégrée a échoué pour '{0}': {1}",
        "CouldNotCompileReturningUncompiledFormat": "Impossible de compiler '{0}'. Retour de la source NSS non compilée.",
        "ExpectedMutableStringButGotFormat": "MutableString attendu pour ModificationsNSS, mais {0} obtenu",
        "PatchingFromUnixCompilingFormat": "Application de correctifs depuis un système d'exploitation unix, compilation de '{0}' à l'aide des compilateurs intégrés...",
        "ExpectedByteArrayButGotFormat": "byte[] attendu pour ModificationsNCS, mais {0} obtenu",
        "GffPathNotFoundDefaultingToRootFormat": "Chemin GFF '{0}' introuvable, utilisation par défaut de la structure racine gff.",
        "UnableToModifyGffFieldFormat": "Impossible de modifier le champ GFF '{0}'. Chemin '{1}' {2}",
        "PathDoesNotExist": "n'existe pas !",
        "PathIsNotGffStructInstance": "n'est pas une instance d'un GFFStruct.",
        "ExpectedGffObjectButGotFormat": "Objet GFF attendu pour ModificationsGFF, mais {0} obtenu",
        "ErrorOccurredWhileCompilingTryingExternalFormat": "Une erreur s'est produite lors de la compilation de '{0}' avec le compilateur intégré, tentative du compilateur externe...",
        "ExpectedSsfObjectButGotFormat": "Objet SSF attendu pour ModificationsSSF, mais {0} obtenu",
        "UnableToUseFieldPathFrom2DAMemoryFormat": "Impossible d'utiliser !FieldPath depuis 2DAMEMORY. Champ parent à '{0}' {1}",
        "ExpectedLocalizedStringButGotFormat": "LocalizedString attendu mais {0} obtenu",
        "ExpectedLocalizedStringDeltaButGotFormat": "LocalizedStringDelta attendu pour le champ existant mais {0} obtenu",
        "ExpectedTlkObjectButGotFormat": "Objet TLK attendu pour ModificationsTLK, mais {0} obtenu",
        "ManagedCompilationFailedFormat": "La compilation gérée a échoué pour '{0}': {1}",
        "CompiledUsingExternalNwnnsscompFormat": "Compilé '{0}' en utilisant nwnnsscomp.exe externe (compilation gérée échouée).",
        "ExternalNwnnsscompAlsoFailedFormat": "Le nwnnsscomp externe a également échoué pour '{0}': {1}",
        "NwnnsscompNotExpectedVersionFormat": "Le nwnnsscomp.exe n'est pas la version KPatcher attendue (détectée: {0}).",
        "ExpectedTwoDAObjectButGotFormat": "Objet TwoDA attendu pour Modifications2DA, mais {0} obtenu",
    },
    "ru": {
        "StartPatchingButton": "&Начать патчинг",
        "StartPatchingConfirmation": "Будут пропатчены необходимые файлы игры. Продолжить?",
        "InvalidGameFolderDialogTlkNotFound": "Неверная папка игры, файл dialog.tlk не найден! Укажите правильный каталог игры.",
        "NoValidGameFolderSelected": "Ошибка! Не выбрана допустимая папка игры! Установка прервана.",
        "SkippingFileNoOverwriteDialogTlk": "Пропуск файла {0}: установщик не перезаписывает dialog.tlk напрямую.",
        "NwnnsscompNotFoundInTslPatchData": "Не найден nwnnsscomp.exe в папке TSLPatchData! Невозможно скомпилировать скрипт.",
        "Invalid2DAMemoryToken": "Недопустимый токен 2DAMEMORY! Индексы токенов начинаются с 1.",
        "PatcherFinished": "Патчер завершил работу. См. журнал прогресса для подробностей.",
        "PatcherFinishedWithWarnings": "Патчер завершил работу, но обнаружено предупреждений: {0}. Мод может работать некорректно.",
        "PatcherFinishedWithErrors": "Патчер завершил работу, но ошибок: {0}. Мод, вероятно, установлен некорректно.",
        "PatcherFinishedWithErrorsAndWarnings": "Патчер завершил работу, но ошибок: {0} и предупреждений: {1}. Мод, вероятно, установлен некорректно.",
        "StrRefTokenNotInTLK": "Токен StrRef «{0}» в списке модификаторов отсутствует в TLK.",
        "NoNewEntriesAppendedToTlk": "Предупреждение: к {0} не добавлено новых записей. Возможно, отсутствуют записи в append.tlk.",
        "NoTLKFileLoaded": "Файл TLK не загружен. Продолжение невозможно.",
        "UnableToLocateTLKFileToPatch": "Ошибка! Не удалось найти TLK для патча, файл «{0}» не найден!",
        "UnableToFind2DAFileToModify": "Не найден файл 2DA «{0}» для изменения! Пропуск файла...",
        "ErrorLookingUpRowLabelForRowIndex": "Ошибка поиска метки строки для индекса строки {0}.",
        "ErrorLookingUpColumnLabelForColumnIndex": "Ошибка поиска метки столбца для индекса столбца {0}.",
        "UsedAsIndexBut2DAHasNoLabel": "{0} использован как индекс при смене строки в модификаторе «{1}», но в 2DA нет метки для этого индекса.",
        "FailedToCopyLine2DA": "Ошибка! Не удалось скопировать строку в 2DA! Пропуск...",
        "UnableToLoad2DAFileSkipping": "Не удалось загрузить файл 2DA {0}! Пропуск...",
        "NoValueAssignedColumn2DA": "Не задано значение столбца {0} для новой строки 2DA в модификаторе «{1}»...",
        "ErrorAddingNewLine2DA": "Ошибка при добавлении новой строки 2DA в модификаторе «{0}»!",
        "InternalErrorInvalidTLKFileType": "Внутренняя ошибка: указан недопустимый тип файла TLK.",
        "CriticalErrorUnableToLocateFileToPatch": "Критическая ошибка: не удалось найти файл для патча, «{0}» не найден!",
        "NoFileToInstallSpecified": "Ошибка! Не указан файл для установки!",
        "NoInstallPathSet": "Ошибка! Не задан путь установки!",
        "FileSetToPatchDoesNotExist": "Ошибка! Файл «{0}» для патча не существует!",
        "UnableToLoadInstructionsTslpatchdata": "Не удалось загрузить текст инструкций! В папке «tslpatchdata» должен быть файл «info.rtf».",
        "SectionNotFoundError": "Секция [{0}] не найдена в ini",
        "ReferencesTracebackMsg": ", ссылка «{0}={1}» в [{2}]",
        "ErrorParsingIniFile": "Ошибка разбора INI: {0}",
        "IniFileNotFound": "Файл INI не найден: {0}",
        "IniTextCannotBeNullOrEmpty": "Текст INI не может быть пустым",
        "LanguageIntegerNotKnown": "Неизвестный код языка: {0}",
        "NoEncodingDefinedForLanguage": "Для языка не задана кодировка: {0}",
        "FilePatcherDescription": "Патчер файлов 2DA/TLK/GFF/NSS/SSF/ERF/RIM для KotOR/TSL.",
        "NoLineSetToBeModifiedFormat": "Не задана строка для изменения в [{0}].",
        "OrphanedIniSectionsFormat": "В изменениях обнаружены «осиротевшие» секции INI:\n{0}",
        # Install log
        "InstallationLogHeader": "Журнал установки KPatcher",
        "InstallationLogHeaderSeparator": "===========================",
        "InstallationDate": "Дата установки: {0}",
        "ModPath": "Путь мода: {0}",
        "GamePath": "Путь игры: {0}",
        "GameDetected": "Игра обнаружена: {0}",
        "FileOperationFormat": "{0}: {1} -> {2}",
        "FileOperationErrorFormat": "Ошибка при {0} {1} в {2}",
        "FileOperationErrorWithMessageFormat": "Ошибка при {0} {1} в {2}: {3}",
        "PatchOperationFormat": "Применение патча {0}: {1} - {2}",
        # ModInstaller
        "CouldNotFindChangesIniFile": "Не удалось найти файл changes.ini на диске.",
        "CouldNotCreateInstallLogFile": "Не удалось создать файл журнала установки: {0}",
        "ChangesConfigFileNotFound": "Файл конфигурации changes не найден: {0}",
        "CouldNotDetermineEncoding": "Не удалось определить кодировку '{0}'. Попытка принудительной загрузки...",
        "CouldNotWriteEquivalentYaml": "Не удалось записать эквивалентный YAML: {0}",
        "CouldNotInitializeUninstallDirectory": "Не удалось инициализировать каталог удаления: {0}",
        "CouldNotCreateBackupFolder": "Не удалось создать папку резервной копии: {0}",
        "UsingBackupDirectory": "Использование каталога резервной копии: '{0}'",
        "InvalidKotorDirectory": "Выбранный каталог KOTOR не является допустимой установкой - невозможно инициализировать ModInstaller.",
        "StartingInstallation": "Запуск установки...",
        "LoadingConfigurationFrom": "Загрузка конфигурации из {0}",
        "FoundPatchesToApply": "Найдено {0} патчей для применения",
        "InstallationTerminationRequest": "ModInstaller.Install() получил запрос на завершение, отмена...",
        "ProcessingInstallListEntries": "Обработка записей InstallList...",
        "ProcessingTlkPatches": "Обработка патчей TLK...",
        "Processing2DAPatches": "Обработка патчей 2DA...",
        "ProcessingGffPatches": "Обработка патчей GFF...",
        "ProcessingNssScriptPatches": "Обработка патчей скриптов NSS...",
        "ProcessingNcsScriptPatches": "Обработка патчей скриптов NCS...",
        "ProcessingSsfSoundPatches": "Обработка патчей звука SSF...",
        "FileHasNoContent": "'{0}' не имеет содержимого/данных и полностью пуст.",
        "SkippingFilePatchResource": "Пропуск '{0}' - patch_resource определил, что этот файл можно пропустить.",
        "CleaningTemporaryScriptFolder": "Очистка временной папки скриптов в '{0}' (подсказка: используйте 'SaveProcessedScripts=1' в [Settings] для сохранения этих скриптов)",
        "SuccessfullyCompletedFormat": "Успешно завершено {0} {1}.",
        "InstallationCompletedSuccessfully": "Установка успешно завершена",
        "InstallationFailedFormat": "Ошибка установки: {0}",
        "PatchingRimFileWarning": "Этот мод применяет патч к файлу RIM Modules/{0}!\nПрименение патчей к RIM крайне несовместимо, не рекомендуется и широко считается плохой практикой. Пожалуйста, попросите разработчика мода исправить это.",
        "ModuleDidNotExistBuilding": "ВАЖНО! Модуль по пути '{0}' не существовал, создание одного в папке 'Modules' немедленно из следующих файлов:",
        "FailedToBuildModule": "Ошибка при создании модуля '{0}': {1}",
        "CapsuleNotFoundOrPermission": "Капсула '{0}' не существовала, или возникли проблемы с разрешениями при попытке {1} '{2}'. Пропуск файла...",
        "BackingUpFile": "Создание резервной копии '{0}'...",
        "FailedToCreateBackup": "Ошибка при создании резервной копии '{0}': {1}",
        "CouldNotLoadSourceFileMissing": "Не удалось загрузить исходный файл для {0}: SourceFile отсутствует или пуст (исправьте или удалите эту строку InstallList / patch в changes.ini).",
        "CouldNotLoadFileSaveAsMissing": "Не удалось загрузить файл для {0}: SaveAs отсутствует или пуст.",
        "CouldNotLoadResourceFromCapsule": "Не удалось загрузить ресурс из капсулы для {0}: SaveAs отсутствует или пуст.",
        "CouldNotLoadSourceFileFormat": "Не удалось загрузить исходный файл для {0}:{1}{2}",
        "CapsuleNotFoundWhenAttempting": "Капсула '{0}' не существовала при попытке {1} '{2}'. Пропуск файла...",
        "RenamedExistingOverrideFile": "Существующий файл Override '{0}' переименован в '{1}' для предотвращения затенения.",
        "CouldNotRenameInOverrideFolder": "Не удалось переименовать '{0}' в '{1}' в папке Override: {2}",
        "ResourceShadowingModChanges": "Ресурс, расположенный в '{0}', затеняет изменения этого мода в {1}!",
        "ModOvershadowedByExisting": "Этот мод намеревается установить '{0}' в '{1}', но затенен существующим '{2}'!",
        # ConfigReader
        "ConfigReaderFinishedLoadingIni": "ConfigReader завершил загрузку INI",
        "SettingsSectionMissing": "Секция [Settings] отсутствует в ini.",
        "LoadingSettingsSection": "Загрузка секции [Settings] из ini...",
        "InstallListSectionMissing": "Секция [InstallList] отсутствует в ini.",
        "LoadingInstallListPatches": "Загрузка патчей [InstallList] из ini...",
        "SkippingEmptyInstallListEntry": "Пропуск пустой записи InstallList (пустая строка или пустой ключ в секции [InstallList] changes.ini).",
        "TlkListSectionMissing": "Секция [TLKList] отсутствует в ini.",
        "LoadingTlkListPatches": "Загрузка патчей [TLKList] из ini...",
        "TwoDAListSectionMissing": "Секция [2DAList] отсутствует в ini.",
        "LoadingTwoDAListPatches": "Загрузка патчей [2DAList] из ini...",
        "SsfListSectionMissing": "Секция [SSFList] отсутствует в ini.",
        "LoadingSsfListPatches": "Загрузка патчей [SSFList] из ini...",
        "GffListSectionMissing": "Секция [GFFList] отсутствует в ini.",
        "LoadingGffListPatches": "Загрузка патчей [GFFList] из ini...",
        "CompileListSectionMissing": "Секция [CompileList] отсутствует в ini.",
        "LoadingCompileListPatches": "Загрузка патчей [CompileList] из ini...",
        "HackListSectionMissing": "Секция [HACKList] отсутствует в ini.",
        "LoadingHackListPatches": "Загрузка патчей [HACKList] из ini...",
        # CLI
        "CliErrorNoModPath": "[Ошибка] Путь мода не указан. Используйте --tslpatchdata <путь>",
        "CliErrorFailedToLoadMod": "[Ошибка] Ошибка загрузки мода: {0}",
        "CliErrorNamespaceIndexOutOfRange": "[Ошибка] Индекс пространства имен {0} вне диапазона (макс: {1})",
        "CliErrorNoGameDirectory": "[Ошибка] Каталог игры не указан. Используйте --game-dir <путь>",
        "CliErrorInvalidGameDirectory": "[Ошибка] Неверный каталог игры: {0}: {1}",
        "CliErrorInvalidModOrGamePaths": "[Ошибка] Неверные пути мода или игры",
        "CliErrorCannotRunMultipleOperations": "[Ошибка] Невозможно выполнить более одной из [--install, --uninstall, --validate]",
        "CliErrorMustSpecifyOperation": "[Ошибка] Необходимо указать одну из [--install, --uninstall, --validate] для режима CLI",
        "CliInfoInstallingMod": "[Инфо] Установка мода из {0} в {1}",
        "CliInfoInstallCompleted": "[Инфо] Установка завершена: {0} ошибок, {1} предупреждений, {2} патчей",
        "CliInfoInstallTime": "[Инфо] Время установки: {0}",
        "CliInfoUninstallingMod": "[Инфо] Удаление мода из {0}",
        "CliInfoUseHelpForOptions": "[Инфо] Используйте --help для просмотра опций CLI",
        "CliWarningDisplayDriverNotAvailable": "[Предупреждение] Драйвер дисплея недоступен, невозможно запустить в режиме GUI: {0}",
        "CliInfoUninstallCompletedSuccessfully": "[Инфо] Удаление успешно завершено",
        "CliWarningUninstallCompletedWithWarnings": "[Предупреждение] Удаление завершено с предупреждениями",
        "CliInfoValidatingMod": "[Инфо] Проверка конфигурации мода",
        "CliInfoValidationCompletedSuccessfully": "[Инфо] Проверка успешно завершена",
        "CliErrorFormat": "[Ошибка] {0}: {1}",
        "CliInnerException": "Внутреннее исключение: {0}",
        # ErrorHandling
        "UnknownException": "Неизвестное исключение",
        "CouldNotFindFile": "Не удалось найти файл: '{0}'",
        "CouldNotFindDirectory": "Не удалось найти каталог: '{0}'",
        "PermissionDenied": "Доступ запрещен: {0}",
        "OperationTimedOut": "Операция превысила время ожидания: {0}",
        "OperationWasCancelled": "Операция была отменена: {0}",
        "IOError": "Ошибка ввода-вывода: {0}",
        "ExceptionInformationHeader": "  Информация:",
        # ModUninstaller
        "RemovedFormat": "Удалено {0}...",
        "RestoringBackupOf": "Восстановление резервной копии '{0}' в '{1}'...",
        "UsingBackupFolder": "Использование папки резервной копии '{0}'",
        "WouldRestoreFile": "Будет восстановлен файл '{0}'",
        "DeletedRestoredBackup": "Восстановленная резервная копия '{0}' удалена",
        # GFF/Interpreter/CodeRoot (technical)
        "ExpectedGffStructButGot": "Ожидался GFFStruct, но получен {0}",
        "DoesNotExist": "Не существует",
        "PathPointsToExpectedGffList": "Путь указывает на '{0}', ожидается GFFList.",
        "UnableToAddStructToList": "Не удалось добавить struct в список '{0}': {1}",
        "IniSectionThrewException": "Секция INI [{0}] вызвала исключение: {1}",
        "FailedToAddNewStructToList": "Ошибка при добавлении нового struct в список '{0}' в [{1}]. Причина: Ожидался GFFStruct, но получен '{2}' ({3}) типа {4} Пропуск...",
        "Set2DAMemory": "Установить 2DAMEMORY{0}={1}",
        "UnexpectedModifierType": "Неожиданный тип модификатора: {0}: {1}",
        "ResolvedGffListPath": "Путь GFFList из [{0}] разрешен из '{1}' --> '{2}'",
        "ApplyPatchFromIniSection": "Применить патч из секции INI [{0}] FieldType: {1} Путь GFF: '{2}'",
        "UnableToAddNewGffField": "Не удалось добавить новое поле GFF '{0}' по пути GFF '{1}'! Это {2}",
        "InstructionJumpsToNotInList": "Инструкция #{0} ({1}) переходит к инструкции, которой нет в списке. Хеш цели перехода: {2}",
        "InstructionLimitExceeded": "Превышен лимит инструкций: {0} инструкций выполнено",
        "InfiniteLoopDetectedExecuted": "Обнаружен бесконечный цикл: инструкция по индексу {0} ({1}) была выполнена {2} раз",
        "JumpInstructionNoTarget": "Инструкция перехода {0} по индексу {1} не имеет цели перехода",
        "JumpTargetNotFound": "Цель перехода для инструкции {0} не найдена в таблице инструкций",
        "InfiniteLoopJumpsToItself": "Обнаружен бесконечный цикл: {0} по индексу {1} переходит к самому себе",
        "CannotAdvanceSameInstruction": "Невозможно продвинуться: следующая инструкция по индексу {0} совпадает с текущей по индексу {1}",
        "InstructionNotPresentInTable": "Инструкция отсутствует в текущей таблице инструкций",
        "InstructionNotImplemented": "Инструкция {0} не реализована",
        "StoreStateCannotAccessInstruction": "STORE_STATE по индексу {0}: невозможно получить доступ к инструкции по индексу {1}",
        "StoreStateReachedEndWithoutRetn": "STORE_STATE по индексу {0}: достигнут конец инструкций без RETN",
        "ActionInstructionRequiresTwoArgs": "Инструкция ACTION требует не менее 2 аргументов",
        "ActionIdOutOfRange": "ID действия {0} вне диапазона (0-{1})",
        "StackUnderflowPoppingVector": "Переполнение стека при извлечении вектора для '{0}'",
        "StackUnderflowPoppingArgument": "Переполнение стека при извлечении аргумента для '{0}'",
        "FileHasNoEntryPoint": "Этот файл не имеет точки входа и не может быть скомпилирован (Скорее всего файл include).",
        "InvalidNssSourceProvided": "Недопустимый источник nss передан в ModificationsNSS.PatchResource()",
        "BuiltInCompilationFailedFormat": "Встроенная компиляция не удалась для '{0}': {1}",
        "CouldNotCompileReturningUncompiledFormat": "Не удалось скомпилировать '{0}'. Возврат нескомпилированного исходного кода NSS.",
        "ExpectedMutableStringButGotFormat": "Ожидался MutableString для ModificationsNSS, но получен {0}",
        "PatchingFromUnixCompilingFormat": "Применение патча из операционной системы unix, компиляция '{0}' с использованием встроенных компиляторов...",
        "ExpectedByteArrayButGotFormat": "Ожидался byte[] для ModificationsNCS, но получен {0}",
        "GffPathNotFoundDefaultingToRootFormat": "Путь GFF '{0}' не найден, по умолчанию используется корневая структура gff.",
        "UnableToModifyGffFieldFormat": "Не удалось изменить поле GFF '{0}'. Путь '{1}' {2}",
        "PathDoesNotExist": "не существует!",
        "PathIsNotGffStructInstance": "не является экземпляром GFFStruct.",
        "ExpectedGffObjectButGotFormat": "Ожидался объект GFF для ModificationsGFF, но получен {0}",
        "ErrorOccurredWhileCompilingTryingExternalFormat": "Произошла ошибка при компиляции '{0}' со встроенным компилятором, попытка внешнего компилятора...",
        "ExpectedSsfObjectButGotFormat": "Ожидался объект SSF для ModificationsSSF, но получен {0}",
        "UnableToUseFieldPathFrom2DAMemoryFormat": "Невозможно использовать !FieldPath из 2DAMEMORY. Родительское поле в '{0}' {1}",
        "ExpectedLocalizedStringButGotFormat": "Ожидался LocalizedString, но получен {0}",
        "ExpectedLocalizedStringDeltaButGotFormat": "Ожидался LocalizedStringDelta для существующего поля, но получен {0}",
        "ExpectedTlkObjectButGotFormat": "Ожидался объект TLK для ModificationsTLK, но получен {0}",
        "ManagedCompilationFailedFormat": "Управляемая компиляция не удалась для '{0}': {1}",
        "CompiledUsingExternalNwnnsscompFormat": "Скомпилировано '{0}' с использованием внешнего nwnnsscomp.exe (управляемая компиляция не удалась).",
        "ExternalNwnnsscompAlsoFailedFormat": "Внешний nwnnsscomp также не удался для '{0}': {1}",
        "NwnnsscompNotExpectedVersionFormat": "nwnnsscomp.exe не является ожидаемой версией KPatcher (обнаружена: {0}).",
        "ExpectedTwoDAObjectButGotFormat": "Ожидался объект TwoDA для Modifications2DA, но получен {0}",
    },
    "pl": {
        "StartPatchingButton": "&Rozpocznij patchowanie",
        "StartPatchingConfirmation": "Spowoduje to rozpoczęcie patchowania wymaganych plików gry. Czy chcesz kontynuować?",
        "InvalidGameFolderDialogTlkNotFound": "Nieprawidłowy folder gry, nie znaleziono pliku dialog.tlk! Wybierz właściwy katalog gry.",
        "NoValidGameFolderSelected": "Błąd! Nie wybrano prawidłowego folderu gry! Instalacja przerwana.",
        "SkippingFileNoOverwriteDialogTlk": "Pomijanie pliku {0} — instalator nie nadpisuje bezpośrednio dialog.tlk.",
        "NwnnsscompNotFoundInTslPatchData": "Nie znaleziono nwnnsscomp.exe w folderze TSLPatchData! Nie można skompilować skryptu.",
        "Invalid2DAMemoryToken": "Nieprawidłowy token 2DAMEMORY! Indeksy tokenów zaczynają się od 1.",
        "PatcherFinished": "Patcher zakończył pracę. Sprawdź dziennik postępu, aby zobaczyć szczegóły.",
        "PatcherFinishedWithWarnings": "Patcher zakończył pracę, ale napotkano {0} ostrzeżeń! Mod może działać nieprawidłowo.",
        "PatcherFinishedWithErrors": "Patcher zakończył pracę, ale napotkano {0} błędów! Mod prawdopodobnie nie został poprawnie zainstalowany.",
        "PatcherFinishedWithErrorsAndWarnings": "Patcher zakończył pracę, ale napotkano {0} błędów i {1} ostrzeżeń! Mod prawdopodobnie nie został poprawnie zainstalowany.",
        "StrRefTokenNotInTLK": "Token StrRef „{0}” na liście modyfikatorów nie występuje w TLK.",
        "NoNewEntriesAppendedToTlk": "Ostrzeżenie: Brak nowych wpisów dodanych do {0}. Możliwe brakujące wpisy w append.tlk.",
        "NoTLKFileLoaded": "Nie załadowano pliku TLK. Nie można kontynuować.",
        "UnableToLocateTLKFileToPatch": "Błąd! Nie można zlokalizować pliku TLK do patchowania, plik „{0}” nie został znaleziony!",
        "UnableToFind2DAFileToModify": "Nie znaleziono pliku 2DA „{0}” do modyfikacji! Pomijanie pliku...",
        "ErrorLookingUpRowLabelForRowIndex": "Błąd wyszukiwania etykiety wiersza dla indeksu wiersza {0}.",
        "ErrorLookingUpColumnLabelForColumnIndex": "Błąd wyszukiwania etykiety kolumny dla indeksu kolumny {0}.",
        "UsedAsIndexBut2DAHasNoLabel": "{0} użyto jako indeks przy zmianie linii w modyfikatorze „{1}”, ale plik 2DA nie ma etykiety dla tego indeksu.",
        "FailedToCopyLine2DA": "Błąd! Nie udało się skopiować linii w 2DA! Pomijanie...",
        "UnableToLoad2DAFileSkipping": "Nie można załadować pliku 2DA {0}! Pomijanie...",
        "NoValueAssignedColumn2DA": "Nie przypisano wartości do kolumny {0} dla nowej linii 2DA w modyfikatorze „{1}”...",
        "ErrorAddingNewLine2DA": "Wystąpił błąd podczas dodawania nowej linii 2DA w modyfikatorze „{0}”!",
        "InternalErrorInvalidTLKFileType": "Błąd wewnętrzny, określono nieprawidłowy typ pliku TLK.",
        "CriticalErrorUnableToLocateFileToPatch": "Błąd krytyczny: Nie można zlokalizować pliku do patchowania, „{0}” nie znaleziono!",
        "NoFileToInstallSpecified": "Błąd! Nie określono pliku do zainstalowania!",
        "NoInstallPathSet": "Błąd! Nie ustawiono ścieżki instalacji!",
        "FileSetToPatchDoesNotExist": "Błąd! Plik „{0}” do patchowania nie istnieje!",
        "UnableToLoadInstructionsTslpatchdata": "Nie można załadować tekstu instrukcji! Folder „tslpatchdata” musi zawierać plik „info.rtf”.",
        "SectionNotFoundError": "Nie znaleziono sekcji [{0}] w pliku ini",
        "ReferencesTracebackMsg": ", odwołanie „{0}={1}” w [{2}]",
        "ErrorParsingIniFile": "Błąd parsowania pliku INI: {0}",
        "IniFileNotFound": "Nie znaleziono pliku INI: {0}",
        "IniTextCannotBeNullOrEmpty": "Tekst INI nie może być pusty ani null",
        "LanguageIntegerNotKnown": "Nieznany identyfikator języka: {0}",
        "NoEncodingDefinedForLanguage": "Brak kodowania dla języka: {0}",
        "FilePatcherDescription": "Program do patchowania plików 2DA/TLK/GFF/NSS/SSF/ERF/RIM dla KotOR/TSL.",
        "NoLineSetToBeModifiedFormat": "Nie ustawiono linii do modyfikacji w [{0}].",
        "OrphanedIniSectionsFormat": "Wykryto osierocone sekcje ini w zmianach:\n{0}",
        # Install log
        "InstallationLogHeader": "Dziennik instalacji KPatcher",
        "InstallationLogHeaderSeparator": "===========================",
        "InstallationDate": "Data instalacji: {0}",
        "ModPath": "Ścieżka moda: {0}",
        "GamePath": "Ścieżka gry: {0}",
        "GameDetected": "Wykryta gra: {0}",
        "FileOperationFormat": "{0}: {1} -> {2}",
        "FileOperationErrorFormat": "Niepowodzenie {0} {1} do {2}",
        "FileOperationErrorWithMessageFormat": "Niepowodzenie {0} {1} do {2}: {3}",
        "PatchOperationFormat": "Stosowanie poprawki {0}: {1} - {2}",
        # ModInstaller
        "CouldNotFindChangesIniFile": "Nie można znaleźć pliku changes.ini na dysku.",
        "CouldNotCreateInstallLogFile": "Nie można utworzyć pliku dziennika instalacji: {0}",
        "ChangesConfigFileNotFound": "Plik konfiguracyjny changes nie znaleziony: {0}",
        "CouldNotDetermineEncoding": "Nie można określić kodowania '{0}'. Próba wymuszonego ładowania...",
        "CouldNotWriteEquivalentYaml": "Nie można zapisać równoważnego YAML: {0}",
        "CouldNotInitializeUninstallDirectory": "Nie można zainicjować katalogu odinstalowania: {0}",
        "CouldNotCreateBackupFolder": "Nie można utworzyć folderu kopii zapasowej: {0}",
        "UsingBackupDirectory": "Używanie katalogu kopii zapasowej: '{0}'",
        "InvalidKotorDirectory": "Wybrany katalog KOTOR nie jest prawidłową instalacją - nie można zainicjować ModInstaller.",
        "StartingInstallation": "Rozpoczynanie instalacji...",
        "LoadingConfigurationFrom": "Ładowanie konfiguracji z {0}",
        "FoundPatchesToApply": "Znaleziono {0} poprawek do zastosowania",
        "InstallationTerminationRequest": "ModInstaller.Install() otrzymał żądanie zakończenia, anulowanie...",
        "ProcessingInstallListEntries": "Przetwarzanie wpisów InstallList...",
        "ProcessingTlkPatches": "Przetwarzanie poprawek TLK...",
        "Processing2DAPatches": "Przetwarzanie poprawek 2DA...",
        "ProcessingGffPatches": "Przetwarzanie poprawek GFF...",
        "ProcessingNssScriptPatches": "Przetwarzanie poprawek skryptów NSS...",
        "ProcessingNcsScriptPatches": "Przetwarzanie poprawek skryptów NCS...",
        "ProcessingSsfSoundPatches": "Przetwarzanie poprawek dźwięku SSF...",
        "FileHasNoContent": "'{0}' nie ma zawartości/danych i jest całkowicie pusty.",
        "SkippingFilePatchResource": "Pomijanie '{0}' - patch_resource określił, że ten plik można pominąć.",
        "CleaningTemporaryScriptFolder": "Czyszczenie tymczasowego folderu skryptów w '{0}' (wskazówka: użyj 'SaveProcessedScripts=1' w [Settings], aby zachować te skrypty)",
        "SuccessfullyCompletedFormat": "Pomyślnie ukończono {0} {1}.",
        "InstallationCompletedSuccessfully": "Instalacja zakończona pomyślnie",
        "InstallationFailedFormat": "Instalacja nie powiodła się: {0}",
        "PatchingRimFileWarning": "Ten mod stosuje poprawkę do pliku RIM Modules/{0}!\nStosowanie poprawek do RIM jest wysoce niezgodne, niezalecane i powszechnie uważane za złą praktykę. Proszę poprosić dewelopera moda o naprawę tego.",
        "ModuleDidNotExistBuilding": "WAŻNE! Moduł w ścieżce '{0}' nie istniał, budowanie jednego w folderze 'Modules' natychmiast z następujących plików:",
        "FailedToBuildModule": "Niepowodzenie budowania modułu '{0}': {1}",
        "CapsuleNotFoundOrPermission": "Kapsuła '{0}' nie istniała lub wystąpiły problemy z uprawnieniami podczas próby {1} '{2}'. Pomijanie pliku...",
        "BackingUpFile": "Tworzenie kopii zapasowej '{0}'...",
        "FailedToCreateBackup": "Niepowodzenie utworzenia kopii zapasowej '{0}': {1}",
        "CouldNotLoadSourceFileMissing": "Nie można załadować pliku źródłowego dla {0}: SourceFile jest brakujący lub pusty (napraw lub usuń ten wiersz InstallList / patch w changes.ini).",
        "CouldNotLoadFileSaveAsMissing": "Nie można załadować pliku dla {0}: SaveAs jest brakujący lub pusty.",
        "CouldNotLoadResourceFromCapsule": "Nie można załadować zasobu z kapsuły dla {0}: SaveAs jest brakujący lub pusty.",
        "CouldNotLoadSourceFileFormat": "Nie można załadować pliku źródłowego dla {0}:{1}{2}",
        "CapsuleNotFoundWhenAttempting": "Kapsuła '{0}' nie istniała podczas próby {1} '{2}'. Pomijanie pliku...",
        "RenamedExistingOverrideFile": "Istniejący plik Override '{0}' został przemianowany na '{1}', aby zapobiec cieniowaniu.",
        "CouldNotRenameInOverrideFolder": "Nie można przemianować '{0}' na '{1}' w folderze Override: {2}",
        "ResourceShadowingModChanges": "Zasób znajdujący się w '{0}' zacienia zmiany tego moda w {1}!",
        "ModOvershadowedByExisting": "Ten mod zamierza zainstalować '{0}' w '{1}', ale jest przesłonięty przez istniejący '{2}'!",
        # ConfigReader
        "ConfigReaderFinishedLoadingIni": "ConfigReader zakończył ładowanie INI",
        "SettingsSectionMissing": "Sekcja [Settings] brakuje w ini.",
        "LoadingSettingsSection": "Ładowanie sekcji [Settings] z ini...",
        "InstallListSectionMissing": "Sekcja [InstallList] brakuje w ini.",
        "LoadingInstallListPatches": "Ładowanie poprawek [InstallList] z ini...",
        "SkippingEmptyInstallListEntry": "Pomijanie pustego wpisu InstallList (pusta linia lub pusty klucz w sekcji [InstallList] changes.ini).",
        "TlkListSectionMissing": "Sekcja [TLKList] brakuje w ini.",
        "LoadingTlkListPatches": "Ładowanie poprawek [TLKList] z ini...",
        "TwoDAListSectionMissing": "Sekcja [2DAList] brakuje w ini.",
        "LoadingTwoDAListPatches": "Ładowanie poprawek [2DAList] z ini...",
        "SsfListSectionMissing": "Sekcja [SSFList] brakuje w ini.",
        "LoadingSsfListPatches": "Ładowanie poprawek [SSFList] z ini...",
        "GffListSectionMissing": "Sekcja [GFFList] brakuje w ini.",
        "LoadingGffListPatches": "Ładowanie poprawek [GFFList] z ini...",
        "CompileListSectionMissing": "Sekcja [CompileList] brakuje w ini.",
        "LoadingCompileListPatches": "Ładowanie poprawek [CompileList] z ini...",
        "HackListSectionMissing": "Sekcja [HACKList] brakuje w ini.",
        "LoadingHackListPatches": "Ładowanie poprawek [HACKList] z ini...",
        # CLI
        "CliErrorNoModPath": "[Błąd] Nie określono ścieżki moda. Użyj --tslpatchdata <ścieżka>",
        "CliErrorFailedToLoadMod": "[Błąd] Niepowodzenie załadowania moda: {0}",
        "CliErrorNamespaceIndexOutOfRange": "[Błąd] Indeks przestrzeni nazw {0} poza zakresem (maks: {1})",
        "CliErrorNoGameDirectory": "[Błąd] Nie określono katalogu gry. Użyj --game-dir <ścieżka>",
        "CliErrorInvalidGameDirectory": "[Błąd] Nieprawidłowy katalog gry: {0}: {1}",
        "CliErrorInvalidModOrGamePaths": "[Błąd] Nieprawidłowe ścieżki moda lub gry",
        "CliErrorCannotRunMultipleOperations": "[Błąd] Nie można uruchomić więcej niż jednej z [--install, --uninstall, --validate]",
        "CliErrorMustSpecifyOperation": "[Błąd] Należy określić jedną z [--install, --uninstall, --validate] dla trybu CLI",
        "CliInfoInstallingMod": "[Info] Instalowanie moda z {0} do {1}",
        "CliInfoInstallCompleted": "[Info] Instalacja zakończona: {0} błędów, {1} ostrzeżeń, {2} poprawek",
        "CliInfoInstallTime": "[Info] Czas instalacji: {0}",
        "CliInfoUninstallingMod": "[Info] Odinstalowywanie moda z {0}",
        "CliInfoUseHelpForOptions": "[Info] Użyj --help, aby zobaczyć opcje CLI",
        "CliWarningDisplayDriverNotAvailable": "[Ostrzeżenie] Sterownik wyświetlacza niedostępny, nie można uruchomić w trybie GUI: {0}",
        "CliInfoUninstallCompletedSuccessfully": "[Info] Odinstalowanie zakończone pomyślnie",
        "CliWarningUninstallCompletedWithWarnings": "[Ostrzeżenie] Odinstalowanie zakończone z ostrzeżeniami",
        "CliInfoValidatingMod": "[Info] Walidacja konfiguracji moda",
        "CliInfoValidationCompletedSuccessfully": "[Info] Walidacja zakończona pomyślnie",
        "CliErrorFormat": "[Błąd] {0}: {1}",
        "CliInnerException": "Wewnętrzny wyjątek: {0}",
        # ErrorHandling
        "UnknownException": "Nieznany wyjątek",
        "CouldNotFindFile": "Nie można znaleźć pliku: '{0}'",
        "CouldNotFindDirectory": "Nie można znaleźć katalogu: '{0}'",
        "PermissionDenied": "Odmowa dostępu: {0}",
        "OperationTimedOut": "Operacja przekroczyła limit czasu: {0}",
        "OperationWasCancelled": "Operacja została anulowana: {0}",
        "IOError": "Błąd we/wy: {0}",
        "ExceptionInformationHeader": "  Informacje:",
        # ModUninstaller
        "RemovedFormat": "Usunięto {0}...",
        "RestoringBackupOf": "Przywracanie kopii zapasowej '{0}' do '{1}'...",
        "UsingBackupFolder": "Używanie folderu kopii zapasowej '{0}'",
        "WouldRestoreFile": "Przywrócono by plik '{0}'",
        "DeletedRestoredBackup": "Przywrócona kopia zapasowa '{0}' usunięta",
        # GFF/Interpreter/CodeRoot (technical)
        "ExpectedGffStructButGot": "Oczekiwano GFFStruct, ale otrzymano {0}",
        "DoesNotExist": "Nie istnieje",
        "PathPointsToExpectedGffList": "Ścieżka wskazuje na '{0}', oczekiwano GFFList.",
        "UnableToAddStructToList": "Nie można dodać struct do listy '{0}': {1}",
        "IniSectionThrewException": "Sekcja INI [{0}] rzuciła wyjątek: {1}",
        "FailedToAddNewStructToList": "Niepowodzenie dodania nowego struct do listy '{0}' w [{1}]. Powód: Oczekiwano GFFStruct, ale otrzymano '{2}' ({3}) typu {4} Pomijanie...",
        "Set2DAMemory": "Ustaw 2DAMEMORY{0}={1}",
        "UnexpectedModifierType": "Nieoczekiwany typ modyfikatora: {0}: {1}",
        "ResolvedGffListPath": "Ścieżka GFFList z [{0}] rozwiązana z '{1}' --> '{2}'",
        "ApplyPatchFromIniSection": "Zastosuj poprawkę z sekcji INI [{0}] FieldType: {1} Ścieżka GFF: '{2}'",
        "UnableToAddNewGffField": "Nie można dodać nowego pola GFF '{0}' w ścieżce GFF '{1}'! To {2}",
        "InstructionJumpsToNotInList": "Instrukcja #{0} ({1}) przeskakuje do instrukcji, która nie jest na liście. Hash celu skoku: {2}",
        "InstructionLimitExceeded": "Przekroczono limit instrukcji: {0} instrukcji wykonanych",
        "InfiniteLoopDetectedExecuted": "Wykryto nieskończoną pętlę: instrukcja w indeksie {0} ({1}) została wykonana {2} razy",
        "JumpInstructionNoTarget": "Instrukcja skoku {0} w indeksie {1} nie ma celu skoku",
        "JumpTargetNotFound": "Cel skoku dla instrukcji {0} nie znaleziony w tabeli instrukcji",
        "InfiniteLoopJumpsToItself": "Wykryto nieskończoną pętlę: {0} w indeksie {1} przeskakuje do siebie",
        "CannotAdvanceSameInstruction": "Nie można przejść dalej: następna instrukcja w indeksie {0} jest taka sama jak bieżąca w indeksie {1}",
        "InstructionNotPresentInTable": "Instrukcja nie jest obecna w bieżącej tabeli instrukcji",
        "InstructionNotImplemented": "Instrukcja {0} nie jest zaimplementowana",
        "StoreStateCannotAccessInstruction": "STORE_STATE w indeksie {0}: nie można uzyskać dostępu do instrukcji w indeksie {1}",
        "StoreStateReachedEndWithoutRetn": "STORE_STATE w indeksie {0}: osiągnięto koniec instrukcji bez znalezienia RETN",
        "ActionInstructionRequiresTwoArgs": "Instrukcja ACTION wymaga co najmniej 2 argumentów",
        "ActionIdOutOfRange": "ID akcji {0} jest poza zakresem (0-{1})",
        "StackUnderflowPoppingVector": "Niedomiar stosu podczas usuwania wektora dla '{0}'",
        "StackUnderflowPoppingArgument": "Niedomiar stosu podczas usuwania argumentu dla '{0}'",
        "FileHasNoEntryPoint": "Ten plik nie ma punktu wejścia i nie może być skompilowany (Prawdopodobnie plik include).",
        "InvalidNssSourceProvided": "Nieprawidłowe źródło nss przekazane do ModificationsNSS.PatchResource()",
        "BuiltInCompilationFailedFormat": "Wbudowana kompilacja nie powiodła się dla '{0}': {1}",
        "CouldNotCompileReturningUncompiledFormat": "Nie można skompilować '{0}'. Zwracanie nieskompilowanego źródła NSS.",
        "ExpectedMutableStringButGotFormat": "Oczekiwano MutableString dla ModificationsNSS, ale otrzymano {0}",
        "PatchingFromUnixCompilingFormat": "Stosowanie poprawek z systemu operacyjnego unix, kompilowanie '{0}' przy użyciu wbudowanych kompilatorów...",
        "ExpectedByteArrayButGotFormat": "Oczekiwano byte[] dla ModificationsNCS, ale otrzymano {0}",
        "GffPathNotFoundDefaultingToRootFormat": "Ścieżka GFF '{0}' nie znaleziona, domyślnie używana jest struktura główna gff.",
        "UnableToModifyGffFieldFormat": "Nie można zmodyfikować pola GFF '{0}'. Ścieżka '{1}' {2}",
        "PathDoesNotExist": "nie istnieje!",
        "PathIsNotGffStructInstance": "nie jest instancją GFFStruct.",
        "ExpectedGffObjectButGotFormat": "Oczekiwano obiektu GFF dla ModificationsGFF, ale otrzymano {0}",
        "ErrorOccurredWhileCompilingTryingExternalFormat": "Wystąpił błąd podczas kompilacji '{0}' z wbudowanym kompilatorem, próba zewnętrznego kompilatora...",
        "ExpectedSsfObjectButGotFormat": "Oczekiwano obiektu SSF dla ModificationsSSF, ale otrzymano {0}",
        "UnableToUseFieldPathFrom2DAMemoryFormat": "Nie można użyć !FieldPath z 2DAMEMORY. Pole nadrzędne w '{0}' {1}",
        "ExpectedLocalizedStringButGotFormat": "Oczekiwano LocalizedString, ale otrzymano {0}",
        "ExpectedLocalizedStringDeltaButGotFormat": "Oczekiwano LocalizedStringDelta dla istniejącego pola, ale otrzymano {0}",
        "ExpectedTlkObjectButGotFormat": "Oczekiwano obiektu TLK dla ModificationsTLK, ale otrzymano {0}",
        "ManagedCompilationFailedFormat": "Kompilacja zarządzana nie powiodła się dla '{0}': {1}",
        "CompiledUsingExternalNwnnsscompFormat": "Skompilowano '{0}' używając zewnętrznego nwnnsscomp.exe (kompilacja zarządzana nie powiodła się).",
        "ExternalNwnnsscompAlsoFailedFormat": "Zewnętrzny nwnnsscomp również nie powiódł się dla '{0}': {1}",
        "NwnnsscompNotExpectedVersionFormat": "nwnnsscomp.exe nie jest oczekiwaną wersją KPatcher (wykryto: {0}).",
        "ExpectedTwoDAObjectButGotFormat": "Oczekiwano obiektu TwoDA dla Modifications2DA, ale otrzymano {0}",
    },
}


def escape_xml(s: str) -> str:
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace('"', "&quot;")


def get_all_keys(english: dict) -> list:
    return sorted(english.keys())


def write_resx(path: Path, data: dict, all_keys: list, english: dict):
    lines = [HEADER.rstrip()]
    for key in all_keys:
        value = data.get(key, english.get(key, ""))
        v = escape_xml(value)
        lines.append(f'  <data name="{key}" xml:space="preserve"><value>{v}</value></data>')
    lines.append("</root>")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main():
    root = Path(__file__).resolve().parents[1] / "src" / "KPatcher.Core" / "Resources"
    english = _read_english_from_resx(root)
    all_keys = get_all_keys(english)
    for lang in ("es", "de", "fr", "ru", "pl"):
        # Merge: start from English, override with translations where present
        data = dict(english)
        data.update(TRANSLATIONS.get(lang, {}))
        write_resx(root / f"PatcherResources.{lang}.resx", data, all_keys, english)
    print("Wrote PatcherResources satellite resx files.")


if __name__ == "__main__":
    main()
