//------------------------------------------------------------------------------
// <auto-generated> — hand-maintained to match PatcherResources.resx
//------------------------------------------------------------------------------
#pragma warning disable CS1591

namespace KPatcher.Core.Resources
{
    using System.Globalization;
    using System.Resources;

    /// <summary>Localized strings for patcher parity messages and shared Core UI/log text.</summary>
    public static class PatcherResources
    {
        private static ResourceManager _resourceManager;
        private static CultureInfo _resourceCulture;

        public static ResourceManager ResourceManager
        {
            get
            {
                if (_resourceManager == null)
                {
                    _resourceManager = new ResourceManager(
                        "KPatcher.Core.Resources.PatcherResources",
                        typeof(PatcherResources).Assembly);
                }

                return _resourceManager;
            }
        }

        public static CultureInfo Culture
        {
            get => _resourceCulture;
            set => _resourceCulture = value;
        }

        public static string ActionIdOutOfRange => ResourceManager.GetString(nameof(ActionIdOutOfRange), _resourceCulture);
        public static string ActionInstructionRequiresTwoArgs => ResourceManager.GetString(nameof(ActionInstructionRequiresTwoArgs), _resourceCulture);
        public static string ApplyPatchFromIniSection => ResourceManager.GetString(nameof(ApplyPatchFromIniSection), _resourceCulture);
        public static string BackingUpFile => ResourceManager.GetString(nameof(BackingUpFile), _resourceCulture);
        public static string CannotAdvanceSameInstruction => ResourceManager.GetString(nameof(CannotAdvanceSameInstruction), _resourceCulture);
        public static string CapsuleNotFoundOrPermission => ResourceManager.GetString(nameof(CapsuleNotFoundOrPermission), _resourceCulture);
        public static string CapsuleNotFoundWhenAttempting => ResourceManager.GetString(nameof(CapsuleNotFoundWhenAttempting), _resourceCulture);
        public static string ChangesConfigFileNotFound => ResourceManager.GetString(nameof(ChangesConfigFileNotFound), _resourceCulture);
        public static string CleaningTemporaryScriptFolder => ResourceManager.GetString(nameof(CleaningTemporaryScriptFolder), _resourceCulture);
        public static string CliErrorCannotRunMultipleOperations => ResourceManager.GetString(nameof(CliErrorCannotRunMultipleOperations), _resourceCulture);
        public static string CliErrorFailedToLoadMod => ResourceManager.GetString(nameof(CliErrorFailedToLoadMod), _resourceCulture);
        public static string CliErrorFormat => ResourceManager.GetString(nameof(CliErrorFormat), _resourceCulture);
        public static string CliErrorInvalidGameDirectory => ResourceManager.GetString(nameof(CliErrorInvalidGameDirectory), _resourceCulture);
        public static string CliErrorInvalidModOrGamePaths => ResourceManager.GetString(nameof(CliErrorInvalidModOrGamePaths), _resourceCulture);
        public static string CliErrorMustSpecifyOperation => ResourceManager.GetString(nameof(CliErrorMustSpecifyOperation), _resourceCulture);
        public static string CliErrorNamespaceIndexOutOfRange => ResourceManager.GetString(nameof(CliErrorNamespaceIndexOutOfRange), _resourceCulture);
        public static string CliErrorNoGameDirectory => ResourceManager.GetString(nameof(CliErrorNoGameDirectory), _resourceCulture);
        public static string CliErrorNoModPath => ResourceManager.GetString(nameof(CliErrorNoModPath), _resourceCulture);
        public static string CliHelpUsage => ResourceManager.GetString(nameof(CliHelpUsage), _resourceCulture);
        public static string CliInfoInstallCompleted => ResourceManager.GetString(nameof(CliInfoInstallCompleted), _resourceCulture);
        public static string CliInfoInstallTime => ResourceManager.GetString(nameof(CliInfoInstallTime), _resourceCulture);
        public static string CliInfoInstallingMod => ResourceManager.GetString(nameof(CliInfoInstallingMod), _resourceCulture);
        public static string CliInfoUninstallCompletedSuccessfully => ResourceManager.GetString(nameof(CliInfoUninstallCompletedSuccessfully), _resourceCulture);
        public static string CliInfoUninstallingMod => ResourceManager.GetString(nameof(CliInfoUninstallingMod), _resourceCulture);
        public static string CliInfoUseHelpForOptions => ResourceManager.GetString(nameof(CliInfoUseHelpForOptions), _resourceCulture);
        public static string CliInfoValidatingMod => ResourceManager.GetString(nameof(CliInfoValidatingMod), _resourceCulture);
        public static string CliWarningDisplayDriverNotAvailable => ResourceManager.GetString(nameof(CliWarningDisplayDriverNotAvailable), _resourceCulture);
        public static string CliInfoValidationCompletedSuccessfully => ResourceManager.GetString(nameof(CliInfoValidationCompletedSuccessfully), _resourceCulture);
        public static string CliInnerException => ResourceManager.GetString(nameof(CliInnerException), _resourceCulture);
        public static string CompiledUsingExternalNwnnsscompFormat => ResourceManager.GetString(nameof(CompiledUsingExternalNwnnsscompFormat), _resourceCulture);
        public static string CliWarningUninstallCompletedWithWarnings => ResourceManager.GetString(nameof(CliWarningUninstallCompletedWithWarnings), _resourceCulture);
        public static string CompileListSectionMissing => ResourceManager.GetString(nameof(CompileListSectionMissing), _resourceCulture);
        public static string ConfigReaderFinishedLoadingIni => ResourceManager.GetString(nameof(ConfigReaderFinishedLoadingIni), _resourceCulture);
        public static string CouldNotCreateBackupFolder => ResourceManager.GetString(nameof(CouldNotCreateBackupFolder), _resourceCulture);
        public static string CouldNotCreateInstallLogFile => ResourceManager.GetString(nameof(CouldNotCreateInstallLogFile), _resourceCulture);
        public static string CouldNotDetermineEncoding => ResourceManager.GetString(nameof(CouldNotDetermineEncoding), _resourceCulture);
        public static string CouldNotFindChangesIniFile => ResourceManager.GetString(nameof(CouldNotFindChangesIniFile), _resourceCulture);
        public static string CouldNotFindDirectory => ResourceManager.GetString(nameof(CouldNotFindDirectory), _resourceCulture);
        public static string CouldNotFindFile => ResourceManager.GetString(nameof(CouldNotFindFile), _resourceCulture);
        public static string CouldNotInitializeUninstallDirectory => ResourceManager.GetString(nameof(CouldNotInitializeUninstallDirectory), _resourceCulture);
        public static string CouldNotLoadFileSaveAsMissing => ResourceManager.GetString(nameof(CouldNotLoadFileSaveAsMissing), _resourceCulture);
        public static string CouldNotLoadResourceFromCapsule => ResourceManager.GetString(nameof(CouldNotLoadResourceFromCapsule), _resourceCulture);
        public static string CouldNotLoadSourceFileFormat => ResourceManager.GetString(nameof(CouldNotLoadSourceFileFormat), _resourceCulture);
        public static string CouldNotLoadSourceFileMissing => ResourceManager.GetString(nameof(CouldNotLoadSourceFileMissing), _resourceCulture);
        public static string CouldNotRenameInOverrideFolder => ResourceManager.GetString(nameof(CouldNotRenameInOverrideFolder), _resourceCulture);
        public static string CouldNotWriteEquivalentYaml => ResourceManager.GetString(nameof(CouldNotWriteEquivalentYaml), _resourceCulture);
        public static string CriticalErrorUnableToLocateFileToPatch => ResourceManager.GetString(nameof(CriticalErrorUnableToLocateFileToPatch), _resourceCulture);
        public static string DeletedRestoredBackup => ResourceManager.GetString(nameof(DeletedRestoredBackup), _resourceCulture);
        public static string DoesNotExist => ResourceManager.GetString(nameof(DoesNotExist), _resourceCulture);
        public static string ErrorAddingNewLine2DA => ResourceManager.GetString(nameof(ErrorAddingNewLine2DA), _resourceCulture);
        public static string ErrorLookingUpColumnLabelForColumnIndex => ResourceManager.GetString(nameof(ErrorLookingUpColumnLabelForColumnIndex), _resourceCulture);
        public static string ErrorLookingUpRowLabelForRowIndex => ResourceManager.GetString(nameof(ErrorLookingUpRowLabelForRowIndex), _resourceCulture);
        public static string ErrorOccurredWhileCompilingTryingExternalFormat => ResourceManager.GetString(nameof(ErrorOccurredWhileCompilingTryingExternalFormat), _resourceCulture);
        public static string ErrorParsingIniFile => ResourceManager.GetString(nameof(ErrorParsingIniFile), _resourceCulture);
        public static string ExceptionInformationHeader => ResourceManager.GetString(nameof(ExceptionInformationHeader), _resourceCulture);
        public static string ExpectedGffStructButGot => ResourceManager.GetString(nameof(ExpectedGffStructButGot), _resourceCulture);
        public static string FailedToAddNewStructToList => ResourceManager.GetString(nameof(FailedToAddNewStructToList), _resourceCulture);
        public static string FailedToBuildModule => ResourceManager.GetString(nameof(FailedToBuildModule), _resourceCulture);
        public static string FailedToCopyLine2DA => ResourceManager.GetString(nameof(FailedToCopyLine2DA), _resourceCulture);
        public static string FailedToCreateBackup => ResourceManager.GetString(nameof(FailedToCreateBackup), _resourceCulture);
        public static string FileHasNoContent => ResourceManager.GetString(nameof(FileHasNoContent), _resourceCulture);
        public static string FileHasNoEntryPoint => ResourceManager.GetString(nameof(FileHasNoEntryPoint), _resourceCulture);
        public static string FileOperationErrorFormat => ResourceManager.GetString(nameof(FileOperationErrorFormat), _resourceCulture);
        public static string InvalidNssSourceProvided => ResourceManager.GetString(nameof(InvalidNssSourceProvided), _resourceCulture);
        public static string BuiltInCompilationFailedFormat => ResourceManager.GetString(nameof(BuiltInCompilationFailedFormat), _resourceCulture);
        public static string CouldNotCompileReturningUncompiledFormat => ResourceManager.GetString(nameof(CouldNotCompileReturningUncompiledFormat), _resourceCulture);
        public static string ExpectedMutableStringButGotFormat => ResourceManager.GetString(nameof(ExpectedMutableStringButGotFormat), _resourceCulture);
        public static string PatchingFromUnixCompilingFormat => ResourceManager.GetString(nameof(PatchingFromUnixCompilingFormat), _resourceCulture);
        public static string ExpectedByteArrayButGotFormat => ResourceManager.GetString(nameof(ExpectedByteArrayButGotFormat), _resourceCulture);
        public static string ExpectedGffObjectButGotFormat => ResourceManager.GetString(nameof(ExpectedGffObjectButGotFormat), _resourceCulture);
        public static string ExpectedLocalizedStringButGotFormat => ResourceManager.GetString(nameof(ExpectedLocalizedStringButGotFormat), _resourceCulture);
        public static string ExpectedLocalizedStringDeltaButGotFormat => ResourceManager.GetString(nameof(ExpectedLocalizedStringDeltaButGotFormat), _resourceCulture);
        public static string ExpectedSsfObjectButGotFormat => ResourceManager.GetString(nameof(ExpectedSsfObjectButGotFormat), _resourceCulture);
        public static string ExpectedTlkObjectButGotFormat => ResourceManager.GetString(nameof(ExpectedTlkObjectButGotFormat), _resourceCulture);
        public static string ExpectedTwoDAObjectButGotFormat => ResourceManager.GetString(nameof(ExpectedTwoDAObjectButGotFormat), _resourceCulture);
        public static string ExternalNwnnsscompAlsoFailedFormat => ResourceManager.GetString(nameof(ExternalNwnnsscompAlsoFailedFormat), _resourceCulture);
        public static string GffPathNotFoundDefaultingToRootFormat => ResourceManager.GetString(nameof(GffPathNotFoundDefaultingToRootFormat), _resourceCulture);
        public static string UnableToModifyGffFieldFormat => ResourceManager.GetString(nameof(UnableToModifyGffFieldFormat), _resourceCulture);
        public static string UnableToUseFieldPathFrom2DAMemoryFormat => ResourceManager.GetString(nameof(UnableToUseFieldPathFrom2DAMemoryFormat), _resourceCulture);
        public static string PathDoesNotExist => ResourceManager.GetString(nameof(PathDoesNotExist), _resourceCulture);
        public static string PathIsNotGffStructInstance => ResourceManager.GetString(nameof(PathIsNotGffStructInstance), _resourceCulture);
        public static string FileOperationErrorWithMessageFormat => ResourceManager.GetString(nameof(FileOperationErrorWithMessageFormat), _resourceCulture);
        public static string FileOperationFormat => ResourceManager.GetString(nameof(FileOperationFormat), _resourceCulture);
        public static string FilePatcherDescription => ResourceManager.GetString(nameof(FilePatcherDescription), _resourceCulture);
        public static string FileSetToPatchDoesNotExist => ResourceManager.GetString(nameof(FileSetToPatchDoesNotExist), _resourceCulture);
        public static string FoundPatchesToApply => ResourceManager.GetString(nameof(FoundPatchesToApply), _resourceCulture);
        public static string GameDetected => ResourceManager.GetString(nameof(GameDetected), _resourceCulture);
        public static string GamePath => ResourceManager.GetString(nameof(GamePath), _resourceCulture);
        public static string GffListSectionMissing => ResourceManager.GetString(nameof(GffListSectionMissing), _resourceCulture);
        public static string HackListSectionMissing => ResourceManager.GetString(nameof(HackListSectionMissing), _resourceCulture);
        public static string IOError => ResourceManager.GetString(nameof(IOError), _resourceCulture);
        public static string InfiniteLoopDetectedExecuted => ResourceManager.GetString(nameof(InfiniteLoopDetectedExecuted), _resourceCulture);
        public static string InfiniteLoopJumpsToItself => ResourceManager.GetString(nameof(InfiniteLoopJumpsToItself), _resourceCulture);
        public static string IniFileNotFound => ResourceManager.GetString(nameof(IniFileNotFound), _resourceCulture);
        public static string IniSectionThrewException => ResourceManager.GetString(nameof(IniSectionThrewException), _resourceCulture);
        public static string IniTextCannotBeNullOrEmpty => ResourceManager.GetString(nameof(IniTextCannotBeNullOrEmpty), _resourceCulture);
        public static string InstallListSectionMissing => ResourceManager.GetString(nameof(InstallListSectionMissing), _resourceCulture);
        public static string InstallationCompletedSuccessfully => ResourceManager.GetString(nameof(InstallationCompletedSuccessfully), _resourceCulture);
        public static string InstallationDate => ResourceManager.GetString(nameof(InstallationDate), _resourceCulture);
        public static string InstallationFailedFormat => ResourceManager.GetString(nameof(InstallationFailedFormat), _resourceCulture);
        public static string InstallationLogHeader => ResourceManager.GetString(nameof(InstallationLogHeader), _resourceCulture);
        public static string InstallationLogHeaderSeparator => ResourceManager.GetString(nameof(InstallationLogHeaderSeparator), _resourceCulture);
        public static string InstallationTerminationRequest => ResourceManager.GetString(nameof(InstallationTerminationRequest), _resourceCulture);
        public static string InstructionJumpsToNotInList => ResourceManager.GetString(nameof(InstructionJumpsToNotInList), _resourceCulture);
        public static string InstructionLimitExceeded => ResourceManager.GetString(nameof(InstructionLimitExceeded), _resourceCulture);
        public static string InstructionNotImplemented => ResourceManager.GetString(nameof(InstructionNotImplemented), _resourceCulture);
        public static string InstructionNotPresentInTable => ResourceManager.GetString(nameof(InstructionNotPresentInTable), _resourceCulture);
        public static string InternalErrorInvalidTLKFileType => ResourceManager.GetString(nameof(InternalErrorInvalidTLKFileType), _resourceCulture);
        public static string Invalid2DAMemoryToken => ResourceManager.GetString(nameof(Invalid2DAMemoryToken), _resourceCulture);
        public static string InvalidGameFolderDialogTlkNotFound => ResourceManager.GetString(nameof(InvalidGameFolderDialogTlkNotFound), _resourceCulture);
        public static string InvalidKotorDirectory => ResourceManager.GetString(nameof(InvalidKotorDirectory), _resourceCulture);
        public static string JumpInstructionNoTarget => ResourceManager.GetString(nameof(JumpInstructionNoTarget), _resourceCulture);
        public static string JumpTargetNotFound => ResourceManager.GetString(nameof(JumpTargetNotFound), _resourceCulture);
        public static string LanguageIntegerNotKnown => ResourceManager.GetString(nameof(LanguageIntegerNotKnown), _resourceCulture);
        public static string LoadingCompileListPatches => ResourceManager.GetString(nameof(LoadingCompileListPatches), _resourceCulture);
        public static string LoadingConfigurationFrom => ResourceManager.GetString(nameof(LoadingConfigurationFrom), _resourceCulture);
        public static string LoadingGffListPatches => ResourceManager.GetString(nameof(LoadingGffListPatches), _resourceCulture);
        public static string LoadingHackListPatches => ResourceManager.GetString(nameof(LoadingHackListPatches), _resourceCulture);
        public static string LoadingInstallListPatches => ResourceManager.GetString(nameof(LoadingInstallListPatches), _resourceCulture);
        public static string LoadingSettingsSection => ResourceManager.GetString(nameof(LoadingSettingsSection), _resourceCulture);
        public static string LoadingSsfListPatches => ResourceManager.GetString(nameof(LoadingSsfListPatches), _resourceCulture);
        public static string LoadingTlkListPatches => ResourceManager.GetString(nameof(LoadingTlkListPatches), _resourceCulture);
        public static string LoadingTwoDAListPatches => ResourceManager.GetString(nameof(LoadingTwoDAListPatches), _resourceCulture);
        public static string ManagedCompilationFailedFormat => ResourceManager.GetString(nameof(ManagedCompilationFailedFormat), _resourceCulture);
        public static string ModOvershadowedByExisting => ResourceManager.GetString(nameof(ModOvershadowedByExisting), _resourceCulture);
        public static string ModPath => ResourceManager.GetString(nameof(ModPath), _resourceCulture);
        public static string ModuleDidNotExistBuilding => ResourceManager.GetString(nameof(ModuleDidNotExistBuilding), _resourceCulture);
        public static string NoEncodingDefinedForLanguage => ResourceManager.GetString(nameof(NoEncodingDefinedForLanguage), _resourceCulture);
        public static string NoFileToInstallSpecified => ResourceManager.GetString(nameof(NoFileToInstallSpecified), _resourceCulture);
        public static string NoInstallPathSet => ResourceManager.GetString(nameof(NoInstallPathSet), _resourceCulture);
        public static string NoLineSetToBeModifiedFormat => ResourceManager.GetString(nameof(NoLineSetToBeModifiedFormat), _resourceCulture);
        public static string NoNewEntriesAppendedToTlk => ResourceManager.GetString(nameof(NoNewEntriesAppendedToTlk), _resourceCulture);
        public static string NoTLKFileLoaded => ResourceManager.GetString(nameof(NoTLKFileLoaded), _resourceCulture);
        public static string NoValidGameFolderSelected => ResourceManager.GetString(nameof(NoValidGameFolderSelected), _resourceCulture);
        public static string NoValueAssignedColumn2DA => ResourceManager.GetString(nameof(NoValueAssignedColumn2DA), _resourceCulture);
        public static string NwnnsscompNotExpectedVersionFormat => ResourceManager.GetString(nameof(NwnnsscompNotExpectedVersionFormat), _resourceCulture);
        public static string NwnnsscompNotFoundInTslPatchData => ResourceManager.GetString(nameof(NwnnsscompNotFoundInTslPatchData), _resourceCulture);
        public static string OperationTimedOut => ResourceManager.GetString(nameof(OperationTimedOut), _resourceCulture);
        public static string OperationWasCancelled => ResourceManager.GetString(nameof(OperationWasCancelled), _resourceCulture);
        public static string OrphanedIniSectionsFormat => ResourceManager.GetString(nameof(OrphanedIniSectionsFormat), _resourceCulture);
        public static string PatchOperationFormat => ResourceManager.GetString(nameof(PatchOperationFormat), _resourceCulture);
        public static string PatcherFinished => ResourceManager.GetString(nameof(PatcherFinished), _resourceCulture);
        public static string PatcherFinishedWithErrors => ResourceManager.GetString(nameof(PatcherFinishedWithErrors), _resourceCulture);
        public static string PatcherFinishedWithErrorsAndWarnings => ResourceManager.GetString(nameof(PatcherFinishedWithErrorsAndWarnings), _resourceCulture);
        public static string PatcherFinishedWithWarnings => ResourceManager.GetString(nameof(PatcherFinishedWithWarnings), _resourceCulture);
        public static string PatchingRimFileWarning => ResourceManager.GetString(nameof(PatchingRimFileWarning), _resourceCulture);
        public static string PathPointsToExpectedGffList => ResourceManager.GetString(nameof(PathPointsToExpectedGffList), _resourceCulture);
        public static string PermissionDenied => ResourceManager.GetString(nameof(PermissionDenied), _resourceCulture);
        public static string Processing2DAPatches => ResourceManager.GetString(nameof(Processing2DAPatches), _resourceCulture);
        public static string ProcessingGffPatches => ResourceManager.GetString(nameof(ProcessingGffPatches), _resourceCulture);
        public static string ProcessingInstallListEntries => ResourceManager.GetString(nameof(ProcessingInstallListEntries), _resourceCulture);
        public static string ProcessingNcsScriptPatches => ResourceManager.GetString(nameof(ProcessingNcsScriptPatches), _resourceCulture);
        public static string ProcessingNssScriptPatches => ResourceManager.GetString(nameof(ProcessingNssScriptPatches), _resourceCulture);
        public static string ProcessingSsfSoundPatches => ResourceManager.GetString(nameof(ProcessingSsfSoundPatches), _resourceCulture);
        public static string ProcessingTlkPatches => ResourceManager.GetString(nameof(ProcessingTlkPatches), _resourceCulture);
        public static string ReferencesTracebackMsg => ResourceManager.GetString(nameof(ReferencesTracebackMsg), _resourceCulture);
        public static string RemovedFormat => ResourceManager.GetString(nameof(RemovedFormat), _resourceCulture);
        public static string RenamedExistingOverrideFile => ResourceManager.GetString(nameof(RenamedExistingOverrideFile), _resourceCulture);
        public static string ResolvedGffListPath => ResourceManager.GetString(nameof(ResolvedGffListPath), _resourceCulture);
        public static string ResourceShadowingModChanges => ResourceManager.GetString(nameof(ResourceShadowingModChanges), _resourceCulture);
        public static string RestoringBackupOf => ResourceManager.GetString(nameof(RestoringBackupOf), _resourceCulture);
        public static string SectionNotFoundError => ResourceManager.GetString(nameof(SectionNotFoundError), _resourceCulture);
        public static string Set2DAMemory => ResourceManager.GetString(nameof(Set2DAMemory), _resourceCulture);
        public static string SettingsSectionMissing => ResourceManager.GetString(nameof(SettingsSectionMissing), _resourceCulture);
        public static string SkippingEmptyInstallListEntry => ResourceManager.GetString(nameof(SkippingEmptyInstallListEntry), _resourceCulture);
        public static string SkippingFileNoOverwriteDialogTlk => ResourceManager.GetString(nameof(SkippingFileNoOverwriteDialogTlk), _resourceCulture);
        public static string SkippingFilePatchResource => ResourceManager.GetString(nameof(SkippingFilePatchResource), _resourceCulture);
        public static string SsfListSectionMissing => ResourceManager.GetString(nameof(SsfListSectionMissing), _resourceCulture);
        public static string StackUnderflowPoppingArgument => ResourceManager.GetString(nameof(StackUnderflowPoppingArgument), _resourceCulture);
        public static string StackUnderflowPoppingVector => ResourceManager.GetString(nameof(StackUnderflowPoppingVector), _resourceCulture);
        public static string StartPatchingButton => ResourceManager.GetString(nameof(StartPatchingButton), _resourceCulture);
        public static string StartPatchingConfirmation => ResourceManager.GetString(nameof(StartPatchingConfirmation), _resourceCulture);
        public static string StartingInstallation => ResourceManager.GetString(nameof(StartingInstallation), _resourceCulture);
        public static string StoreStateCannotAccessInstruction => ResourceManager.GetString(nameof(StoreStateCannotAccessInstruction), _resourceCulture);
        public static string StoreStateReachedEndWithoutRetn => ResourceManager.GetString(nameof(StoreStateReachedEndWithoutRetn), _resourceCulture);
        public static string StrRefTokenNotInTLK => ResourceManager.GetString(nameof(StrRefTokenNotInTLK), _resourceCulture);
        public static string SuccessfullyCompletedFormat => ResourceManager.GetString(nameof(SuccessfullyCompletedFormat), _resourceCulture);
        public static string TlkListSectionMissing => ResourceManager.GetString(nameof(TlkListSectionMissing), _resourceCulture);
        public static string TwoDAListSectionMissing => ResourceManager.GetString(nameof(TwoDAListSectionMissing), _resourceCulture);
        public static string UnableToAddNewGffField => ResourceManager.GetString(nameof(UnableToAddNewGffField), _resourceCulture);
        public static string UnableToAddStructToList => ResourceManager.GetString(nameof(UnableToAddStructToList), _resourceCulture);
        public static string UnableToFind2DAFileToModify => ResourceManager.GetString(nameof(UnableToFind2DAFileToModify), _resourceCulture);
        public static string UnableToLoad2DAFileSkipping => ResourceManager.GetString(nameof(UnableToLoad2DAFileSkipping), _resourceCulture);
        public static string UnableToLoadInstructionsTslpatchdata => ResourceManager.GetString(nameof(UnableToLoadInstructionsTslpatchdata), _resourceCulture);
        public static string UnableToLocateTLKFileToPatch => ResourceManager.GetString(nameof(UnableToLocateTLKFileToPatch), _resourceCulture);
        public static string UnexpectedModifierType => ResourceManager.GetString(nameof(UnexpectedModifierType), _resourceCulture);
        public static string UnknownException => ResourceManager.GetString(nameof(UnknownException), _resourceCulture);
        public static string UsedAsIndexBut2DAHasNoLabel => ResourceManager.GetString(nameof(UsedAsIndexBut2DAHasNoLabel), _resourceCulture);
        public static string UsingBackupDirectory => ResourceManager.GetString(nameof(UsingBackupDirectory), _resourceCulture);
        public static string UsingBackupFolder => ResourceManager.GetString(nameof(UsingBackupFolder), _resourceCulture);
        public static string WouldRestoreFile => ResourceManager.GetString(nameof(WouldRestoreFile), _resourceCulture);
    }
}

#pragma warning restore CS1591
